
==  Key elements involved in the mapping process
In this section we will provide descriptions and references to the key elements (concepts or resources) that are involved in the creation of mappings or the mapping process itself.

The purpose of the mapping process is to generate a “mapping table” (described in the xref:methodology.adoc#_conceptual-mapping-structure[conceptual mapping artefact] section) that can be processed by an automated workflow of the https://github.com/OP-TED/ted-rdf-conversion-pipeline[TED-SWS system] to “execute” these mappings in order to convert the TED XML input data into an ePO conformant RDF graph (the output of the mapping). This “mapping table” will be encoded as a spreadsheet, with multiple worksheets, whose structure is described elsewhere.


=== Notices to be mapped

The input for the transformation process are *XML files* that contain TED notice data. These data are structured according to the https://simap.ted.europa.eu/web/simap/standard-forms-for-public-procurement[“Standard Forms”]  published by the European Commission. There are 23 standard forms defined (numbered 1-8, 12-25, T1 and T2), whose PDF versions can be found here: https://simap.ted.europa.eu/standard-forms-for-public-procurement[https://simap.ted.europa.eu/standard-forms-for-public-procurement].

The XML files need to conform to the official TED XML format defined by https://op.europa.eu/en/web/eu-vocabularies/e-procurement/tedschemas[TED XML Schema] (XSD). Over the years, multiple versions of this TED XML Schema were released, and there is a significant amount of XML data published that conform to these various versions. The latest XML notices are conformant to the https://op.europa.eu/en/web/eu-vocabularies/e-procurement/tedschemas[*versions R2.0.8 (more precisely R2.0.8.S05.E01_002-20201027 - in case of forms 16-19) and R2.0.9 (more precisely R2.0.9.S05 - for all the other forms)]* of the TED XML Schema.

=== Considered resources

To create these mappings, we rely on a number of different resources that were produced by earlier or currently running projects that aim to provide solutions in the TED landscape. The following table contains a non-comprehensive enumeration of these resources, with their short descriptions and links to where they can be found. This table is provided as a quick reference only. More detailed description of the key resources can be found in a dedicated section below.

|===
|*Resource Name*|*Description*
|ePO - dev version|The e-Procurement Ontology (currently under development) https://docs.ted.europa.eu/EPO/dev/[link]
|TED_EXPORT.xsd|The XML Schema defined for the TED XML Notices. Download and extract the versions R2.0.9 and R2.0.8 of the TED XML schema from the links named _Reception: TED eSenders XML schema_ on this page: https://op.europa.eu/en/web/eu-vocabularies/e-procurement/tedschemas[link]
|TED forms PDFs|PDF files representing the physical forms that are to be completed with the relevant data according to each notice. https://simap.ted.europa.eu/standard-forms-for-public-procurement[link]
|Deloitte & OP - TED_XML_Mapping|Excel spreadsheets that map elements (fields, sections, etc.) found in the Standard Forms to elements in the eForms. These tables provide the full list of elements and also XPaths to identify the corresponding information TED-XML files.
|Ontology_eForms_NEW_Mapping_New Regulation|
|Mappings by Everis|Just for reference. Various parts might be out of date.
|Test data set by Everis|A set of approx. 300 XML files (6 batches of about 50 files each, for the forms F02, F03, F05, F06, F24 and F25)
|RDF results by Everis|Just for reference. Various parts might be out of date.
|XML Data analysis|Contains various tables, each summarising certain aspects  (e.g. XML elements related to certain fields in the form) of the data extracted from test notice files. https://docs.google.com/spreadsheets/d/1EoHUDDjvx62wXa-LKnDkvolN6dVIeZ_rgm3nNZ91gQo[link]
|XML Elements to Vocabulary Mapping|
|TED Mappings to ePO terms| https://github.com/OP-TED/ePO/tree/master/analysis_and_design/ted_mappings[link]
|conventions_report.html|Overview of ePO Terms generated from the UML model. https://github.com/OP-TED/ePO/blob/feature/model-refactoring/analysis_and_design/transformation_output/owl_ontology/conventions_report[conventions_report] (to be checked out and open in a browser)
|===


=== Transformation output

The output of the XML notice transformation will be an *RDF graph* instantiating the https://docs.ted.europa.eu/EPO/dev/index.html[eProcurement Ontology], containing a number of RDF triples where the subjects, predicates and objects of the triples are either:

* *unique IRIs*, generated in a deterministic fashion, that can identify the notice or the different component parts of a notice; these IRIs (or less frequently blank nodes) are used in multiple triples (either as subjects or object) to build an *RDF graph*;
* *IRIs* representing *controlled vocabulary terms* or *entities in the ePO ontology*;
* *Literals* representing numbers, boolean values, or strings. The string values are often encoded as multilingual strings of type +rdf:langString+., to enable the representation of textual values in multiple European languages.

=== Mapping files produced

The key element enabling transformation automation are the mapping files: *conceptual* and *technical* mappings. They are developed according to the <<_mapping_creation_method,mapping creation methodology>>.

The mapping rules are organised in mapping suites, described xref:mapping-suite-structure.adoc[here].

