[#_technical-mapping-modularisation-chapter]
=== Create RML Rules Modules
Forms tend to have similar or identical sections, i.e., represent the same information. For example form F03 and F06 have the same section 1 which is the information about the contract authority.

In order to not write transformation rules twice (for section 1 of F03 and section 1 of F06), we have set up a module system which consists of writing transformation rules that are reusable by several forms. This gives us the following advantages:

* Not to rewrite several times the same rules for different forms (avoid duplication of rules).

* In the case of an update of the ePO ontology, we will have to implement the modification only once in the module(s) affected by the modification which, and the modififacation will be passed into all the forms.


As explained in xref:methodology.adoc#_mapping_creation_method[technical mapping creation] section, a TripleMap represent a mapping of an XML element and its content with one class in the ontology and a set of its predicates objects. In order to have a module that can be reused on many forms we only define in these module files the predicates objects of a TripleMap. The logical sources and subjects map, needed in every TripleMap object, are described separately in the main file as they contain information specific to every form, making these parts of the TripleMap object non-reusable. For example a module that contain an organisation looked like that:

----
<#OrganisationMapping> a rr:TriplesMap ;
	rr:predicateObjectMap
		[
		rr:predicate epo:hasName ;
		rr:objectMap
				[
					rml:reference "OFFICIALNAME"
				]
		] ;

----

This module is extended in the main file of F03 by adding the logicalSource and the SubjectMap in this way:


----
<#OrganisationMapping> a rr:TriplesMap ;
	rml:logicalSource
		[
			rml:source "source.xml" ;
			rml:referenceFormulation ql:XPath
			rml:iterator "/TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/ADDRESS_CONTRACTING_BODY" ;

		] ;
	rr:subjectMap
		[
			rr:template
				"http://data.europa.eu/a4g/resource/Organisation/uuid_generation_function ;
			rr:class epo:Organisation

		] ;
----

The modules are stored in the ted-rdf-mapping project in the `src/mappings` folder.
For the moment we covered seven sections of F03, F06, F13, F20, F21, F22, F23, and F25, and three Annexes,
Annex D1, Annex D2, and Annex D4. The mapping is performed with the generic mapping rules, i.e., those that are applicable across mapping suite packages:

* s1_contracting_authority.rml.ttl
* s2_object.rml.ttl
* s3_legal_economic_financial.rml.ttl
* s4_procedure.rml.ttl
* s5_award_of_contract.rml.ttl
* s6_complementary_information.rml.ttl
* s7_modifications_to_contract.rml.ttl
* annex_d1.rml.ttl
* annex_d2.rml.ttl
* annex_d4.rml.ttl

and with the specific mapping rule, i.e., those that are applicable only on one package:

* technical_mapping_F03.rml.ttl
* technical_mapping_F06.rml.ttl
* technical_mapping_F13.rml.ttl
* technical_mapping_F20.rml.ttl
* technical_mapping_F21.rml.ttl
* technical_mapping_F22.rml.ttl
* technical_mapping_F23.rml.ttl
* technical_mapping_F25.rml.ttl

The project contains one `src/mappings` folder containing all the mapping rule files and one "main" entry point mapping file for each form mapping suite package.
The main entry point `package_FXX/transformation/mappings` contains the mapping rules which are related with the mapping suite package, either generic or
specific. Below one can see a representation of the described architecture:

----
/ted-rdf-mapping
	/mappings
		/package_F03
			/transformation
				/resources
				/mappings
                    annex_d1.rml.ttl
					...
					technical_mapping_F03.rml.ttl
        ...
		/package_F25
			/transformation
				/resources
				/mappings
                    annex_d4.rml.ttl
					...
					technical_mapping_F25.rml.ttl
	/src
		/mappings
            s1_contracting_authority.rml.ttl
            s2_object.rml.ttl
            s3_legal_economic_financial.rml.ttl
            s4_procedure.rml.ttl
            s5_award_of_contract.rml.ttl
            s6_complementary_information.rml.ttl
            s7_modifications_to_contract.rml.ttl
            annex_d1.rml.ttl
            annex_d2.rml.ttl
            annex_d4.rml.ttl
            technical_mapping_F03.rml.ttl
            technical_mapping_F06.rml.ttl
            technical_mapping_F13.rml.ttl
            technical_mapping_F20.rml.ttl
            technical_mapping_F21.rml.ttl
            technical_mapping_F22.rml.ttl
            technical_mapping_F23.rml.ttl
            technical_mapping_F25.rml.ttl
----


