#title: VII.2.2.2 - Description of the economic or technical reasons and the inconvenience or duplication of cost preventing a change of contractor:
#description: “VII.2.2.2 - Description of the economic or technical reasons and the inconvenience or duplication of cost preventing a change of contractor:” in SF corresponds to “BT-201 Modification Reason Description” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F20_2014/MODIFICATIONS_CONTRACT/INFO_MODIFICATIONS/ADDITIONAL_NEED. The expected ontology instances are epo: epo:ContractModification / epo:ElementModificationDescription / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F20_2014/MODIFICATIONS_CONTRACT/INFO_MODIFICATIONS/ADDITIONAL_NEED

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ContractModification .
		?this epo:hasElementModification / epo:hasModificationReasonDescription ?value }