#title: VII.2.2.1 - Need for additional works, services or supplies by the original contractor/concessionaire (Art. 43(1)(b) of Directive 2014/23/EU, Art. 72(1)(b) of Directive 2014/24/EU, Art. 89(1)(b) of Directive 2014/25/EU)
#description: “VII.2.2.1 - Need for additional works, services or supplies by the original contractor/concessionaire (Art. 43(1)(b) of Directive 2014/23/EU, Art. 72(1)(b) of Directive 2014/24/EU, Art. 89(1)(b) of Directive 2014/25/EU)” in SF corresponds to “BT-200 Modification Reason Code” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F20_2014/MODIFICATIONS_CONTRACT/INFO_MODIFICATIONS/ADDITIONAL_NEED. The expected ontology instances are epo: epo:ContractModification / epo:ElementModificationDescription /  at-voc:modification-justification .
#xpath: /TED_EXPORT/FORM_SECTION/F20_2014/MODIFICATIONS_CONTRACT/INFO_MODIFICATIONS/ADDITIONAL_NEED

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ContractModification .
		?this epo:hasElementModification / epo:hasModificationJustification <http://publications.europa.eu/resource/authority/modification-justification/add-wss> }