#title: VII.2.2.4 - Description of the circumstances which rendered the modification necessary and explanation of the unforeseen nature of these circumstances:
#description: “VII.2.2.4 - Description of the circumstances which rendered the modification necessary and explanation of the unforeseen nature of these circumstances:” in SF corresponds to “BT-201 Modification Reason Description” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F20_2014/MODIFICATIONS_CONTRACT/INFO_MODIFICATIONS/UNFORESEEN_CIRCUMSTANCE. The expected ontology instances are epo: epo:ContractModification / epo:ElementModificationDescription / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F20_2014/MODIFICATIONS_CONTRACT/INFO_MODIFICATIONS/UNFORESEEN_CIRCUMSTANCE

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ContractModification .
		?this epo:hasElementModification / epo:hasModificationReasonDescription ?value }