#title: VII.1.6 - Information on value of the contract/lot/concession
#description: “VII.1.6 - Information on value of the contract/lot/concession” in SF corresponds to “--- nan” in eForms. The corresponding XML element is . The expected ontology instances are epo: epo:LotAwardOutcome / epo:Lot .
#xpath: 

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LotAwardOutcome .
		?this epo:describesLot ?value }