#title: VII.2.1.1 - Nature and extent of the modifications (with indication of possible earlier changes to the contract)
#description: “VII.2.1.1 - Nature and extent of the modifications (with indication of possible earlier changes to the contract)” in SF corresponds to “BT-202 Modification Description” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F20_2014/MODIFICATIONS_CONTRACT/INFO_MODIFICATIONS/SHORT_DESCR. The expected ontology instances are epo: epo:ContractModification / epo:ElementModificationDescription / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F20_2014/MODIFICATIONS_CONTRACT/INFO_MODIFICATIONS/SHORT_DESCR

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ContractModification .
		?this epo:hasElementModification / epo:hasModificationDescription ?value }