#title: IV.1.1.1 - Award procedure with prior publication of a concession notice
#description: “IV.1.1.1 - Award procedure with prior publication of a concession notice” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014/PROCEDURE/PT_AWARD_CONTRACT_WITH_PRIOR_PUBLICATION. The expected ontology instances are epo: epo:ResultNotice / epo:CompetitionNotice .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:refersToPrevious ?value . }