#title: IV.1.11 - Main features of the award procedure
#description: “IV.1.11 - Main features of the award procedure” in SF corresponds to “BT-88 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014/PROCEDURE/MAIN_FEATURES_AWARD. The expected ontology instances are epo: epo:Procedure / xsd:string .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasMainFeature ?value . }