#title: II.1.5.1 - Value excluding VAT
#description: “II.1.5.1 - Value excluding VAT” in SF corresponds to “BT-161 Estimated Value” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014/OBJECT_CONTRACT/VAL_ESTIMATED_TOTAL. The expected ontology instances are epo: epo:Procedure / epo:MonetaryValue / xsd:decimal .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasEstimatedValue / epo:hasAmountValue ?value . }