#title: II.2.7.2 - Start
#description: “II.2.7.2 - Start” in SF corresponds to “BT-536 Duration Start Date” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014/OBJECT_CONTRACT/OBJECT_DESCR/DATE_START. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / epo:Period / xsd:datetime .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014/OBJECT_CONTRACT/OBJECT_DESCR/DATE_START

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:definesContractPeriod / epo:hasBeginning ?value . }