#title: II.2.7.1 - Duration in months or days
#description: “II.2.7.1 - Duration in months or days” in SF corresponds to “BT-36 Duration Period” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014/OBJECT_CONTRACT/OBJECT_DESCR/DURATION. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / epo:Duration / xsd:decimal .

PREFIX time: <http://www.w3.org/2006/time#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 

?this epo:foreseesContractSpecificTerm / epo:definesConcessionDuration / time:numericDuration ?value . }