#title: V.2.1 - Date of concession award decision
#description: “V.2.1 - Date of concession award decision” in SF corresponds to “BT-1451 Winner Decision Date Winner Decision Date” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014/AWARD_CONTRACT/AWARDED_CONTRACT/DATE_CONCLUSION_CONTRACT. The expected ontology instances are epo: epo:LotAwardOutcome / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014/AWARD_CONTRACT/AWARDED_CONTRACT/DATE_CONCLUSION_CONTRACT

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LotAwardOutcome .
		?this epo:hasAwardDecisionDate ?value . }