#title: V.2.4.2 - Total value of the concession/lot
#description: “V.2.4.2 - Total value of the concession/lot” in SF corresponds to “BT-720 Tender Value” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014/AWARD_CONTRACT/AWARDED_CONTRACT/VALUES/VAL_TOTAL. The expected ontology instances are epo: epo:Tender / epo:MonetaryValue / xsd:decimal .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasFinancialOfferValue / epo:hasAmountValue ?value . }