#title: MetaData
#description: “MetaData” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/CODED_DATA_SECTION/REF_OJS/DATE_PUB. The expected ontology instances are epo: epo:Notice / xsd:string .
#xpath: /TED_EXPORT/CODED_DATA_SECTION/REF_OJS/DATE_PUB

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Notice .
		?this epo:hasPublicationDate ?value }