#title: I.1 - Name and addresses
#description: “I.1 - Name and addresses” in SF corresponds to “nan nan” in eForms. The corresponding XML element is . The expected ontology instances are epo: epo:ResultNotice / epo:Buyer .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:refersToRole ?value }