#title: II.2.7.1.1 - nan
#description: “II.2.7.1.1 - nan” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014/OBJECT_CONTRACT/OBJECT_DESCR/DURATION/@TYPE. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / epo:Duration / time:TemporalUnit .

PREFIX time: <http://www.w3.org/2006/time#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:foreseesContractSpecificTerm / epo:definesConcessionDuration / time:unitType time:unitDay . }