#title: IV.1.6.1 - An electronic auction will be used
#description: “IV.1.6.1 - An electronic auction will be used” in SF corresponds to “BT-767 Electronic Auction” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F06_2014/PROCEDURE/EAUCTION_USED. The expected ontology instances are epo: epo:Procedure / epo:EAuctionTechniqueUsage .
#xpath: /TED_EXPORT/FORM_SECTION/F06_2014/PROCEDURE/EAUCTION_USED

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:usesTechnique ?value . }