#title: II.2.5.0.1 - Agree to publish
#description: “II.2.5.0.1 - Agree to publish” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F06_2014/OBJECT_CONTRACT/OBJECT_DESCR/AC/@PUBLICATION. The expected ontology instances are epo: epo:PublicationProvision / epo:ElementConfidentialityDescription / xsd:anyURI (epo:AwardCriterion ) .
#xpath: /TED_EXPORT/FORM_SECTION/F06_2014/OBJECT_CONTRACT/OBJECT_DESCR/AC/@PUBLICATION

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this rdf:type epo:PublicationProvision .
		?this epo:hasElementConfidentiality / epo:hasClassReference ?value . }