#title: V.2.6.1 - Value excluding VAT
#description: “V.2.6.1 - Value excluding VAT” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F06_2014/AWARD_CONTRACT/AWARDED_CONTRACT/VAL_BARGAIN_PURCHASE. The expected ontology instances are epo: epo:LotAwardOutcome / epo:MonetaryValue / xsd:decimal .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasAwardedValue / epo:hasAmountValue ?value . }