#title: V.2.8.1 - Community origin
#description: “V.2.8.1 - Community origin” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F06_2014/AWARD_CONTRACT/AWARDED_CONTRACT/COUNTRY_ORIGIN/COMMUNITY_ORIGIN. The expected ontology instances are epo: epo:Tender /  at-voc:country (from country.json) .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasItemCountryOfOrigin <http://publications.europa.eu/resource/authority/country/EUR> . }