#title: V.2.6.2 - Currency
#description: “V.2.6.2 - Currency” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F06_2014/AWARD_CONTRACT/AWARDED_CONTRACT/VAL_BARGAIN_PURCHASE/@CURRENCY. The expected ontology instances are epo: epo:LotAwardOutcome / epo:MonetaryValue /at-voc:currency (from currency.json) .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasAwardedValue / epo:hasCurrency ?value . }