#title: V.2.9 - The contract was awarded to a tenderer who submitted a variant
#description: “V.2.9 - The contract was awarded to a tenderer who submitted a variant” in SF corresponds to “BT-193 Tender Variant” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F06_2014/AWARD_CONTRACT/AWARDED_CONTRACT/AWARDED_TENDERER_VARIANT. The expected ontology instances are epo: epo:Tender / xsd:boolean .
#xpath: /TED_EXPORT/FORM_SECTION/F06_2014/AWARD_CONTRACT/AWARDED_CONTRACT/AWARDED_TENDERER_VARIANT

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this rdf:type epo:Tender .
		?this epo:isVariant ?value . }