#title: I.1.12 - Internet Addresses
#description: “I.1.12 - Internet Addresses” in SF corresponds to “nan nan” in eForms. The corresponding XML element is . The expected ontology instances are epo: epo:AgentInRole (from CL1) / cpov:ContactPoint / xsd:anyURI .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasContactPointInRole / epo:hasInternetAddress ?value . }