#title: V.2.2.1 - Agree to publish
#description: “V.2.2.1 - Agree to publish” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F06_2014/AWARD_CONTRACT/AGREE_TO_PUBGLICATION_MAN/@PUBLICATION. The expected ontology instances are epo: epo:PublicationProvision / epo:ElementConfidentialityDescription / xsd:anyURI (epo:OrganisationGroup  ) .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this hasElementConfidentiality / epo:hasClassReference ?value . }