#title: I.6 - Main activity
#description: “I.6 - Main activity” in SF corresponds to “BT-10 Activity Authority” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F06_2014/CONTRACTING_BODY/CE_ACTIVITY. The expected ontology instances are epo: org:Organization / at-voc:main-activity (from CL6) .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { ?this rdf:type / epo:hasMainActivityType ?value . }