#title: V.2.8.2.1 - Country
#description: “V.2.8.2.1 - Country” in SF corresponds to “BT-191 Country Origin” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F06_2014/AWARD_CONTRACT/AWARDED_CONTRACT/COUNTRY_ORIGIN/NON_COMMUNITY_ORIGIN. The expected ontology instances are epo: epo:Tender /  at-voc:country (from country.json) .
#xpath: /TED_EXPORT/FORM_SECTION/F06_2014/AWARD_CONTRACT/AWARDED_CONTRACT/COUNTRY_ORIGIN/NON_COMMUNITY_ORIGIN

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Tender .
		?this epo:hasItemCountryOfOrigin ?value . }