#title: nan - nan
#description: “nan - nan” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F06_2014/AWARD_CONTRACT. The expected ontology instances are epo: epo:PublicationProvision / epo:ElementConfidentialityDescription / xsd:anyURI (epo:isVariant ) .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasElementConfidentiality / epo:haPreficateReference ?value . }