#title: V.2.7 - Number of contracts awarded
#description: “V.2.7 - Number of contracts awarded” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F06_2014/AWARD_CONTRACT. The expected ontology instances are epo: epo:PublicationProvision / epo:ElementConfidentialityDescription / xsd:anyURI (epo:XXX) .
#xpath: /TED_EXPORT/FORM_SECTION/F06_2014/AWARD_CONTRACT

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:PublicationProvision .
		?this epo:hasElementConfidentiality / epo:haPreficateReference ?value . }