#title: V.2.8.2.1 - Country
#description: “V.2.8.2.1 - Country” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F06_2014/AWARD_CONTRACT. The expected ontology instances are epo: epo:PublicationProvision / epo:ElementConfidentialityDescription / xsd:anyURI (epo:isVariant ) .
#xpath: /TED_EXPORT/FORM_SECTION/F06_2014/AWARD_CONTRACT

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this rdf:type epo:PublicationProvision .
		?this epo:hasElementConfidentiality / epo:haPreficateReference ?value . }