#TED 929/TED 933
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
ask {
    {
select ?this (COUNT(?someValue) as ?pCount) where {
  ?this ?property ?someValue.
  filter (?property != rdf:type)
  filter strstarts(str(?this),str(epd:)).

} group by ?this
    }
    filter (?pCount = 0)
}