#TED-929/TED-1151 Generic query but also GH issue 273
#Finds instances with multiple IDs on any of the generated individuals (e.g. epo:Contract)

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

SELECT ?sub ?pCount WHERE {
      {
       SELECT ?sub (COUNT(?obj) AS ?pCount) WHERE {
         ?sub epo:hasID ?obj .
         ?obj a epo:Identifier .
       }
       GROUP BY ?sub
      }
      FILTER (?pCount > 1)
}