#title: Generic query checking for presence of language tags TED-929/TED-1157
#description: Ask if all properties whose values need to have a language tag, have one. Return True if they do, False if some does not.

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX cccev: <http://data.europa.eu/m8g/>

ASK {
  {
    SELECT (COUNT(?s) AS ?cNoLangTag) WHERE {
      VALUES ?property {epo:hasLegalName epo:hasContactName
            epo:hasTitle epo:hasDescription epo:hasAdditionalInformation epo:hasOptionsDescription
            locn:fullAddress cccev:name cccev:weight cccev:description}
      ?s ?property ?value
      FILTER (lang(?value) = "")
    }
  }
  FILTER (?cNoLangTag = 0)
}

