#TED 929/Geraud's query
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
ask {
   {
select (COUNT(?sub) as ?instanceCount) {
    {
select ?sub (COUNT(?obj) as ?pCount) where {
    ?sub epo:hasID ?obj .
    ?obj rdf:type epo:Identifier .
    }
    GROUP BY ?sub
    }
    filter (?pCount > 1)
}
   }
    filter(?instanceCount = 0)
}