#title: TED-1302 GH issue 303
#description: Ask query that check if tedm:ContractTermProcedure is connected to epo:Procedure


PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX org: <http://www.w3.org/ns/org#>

SELECT (COUNT(?s) AS ?count) WHERE {
   ?s rdf:type epo:ContractTerm .
   FILTER CONTAINS(STR(?s), "ContractTermProcedure")
   FILTER NOT EXISTS { ?s ?t epo:Lot }
}
HAVING (?count > 1)