#title: TED-929/TED-1132 GH issue 237
#Checks that there are no instances of epo:SubmissionStatisticalInformation whose connection was not updated as specified in GH issue 237, i.e. which are still connected to an epo:Lot instance and/or with a epo:concernsSubmissionsForLot property instead of to an epo:LotAwardOutcome instance with the epo:summarisesInformationForLotAwardOutcome property

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK {
  {
    SELECT (COUNT(?instance) AS ?cAllInst) {
      ?instance a epo:SubmissionStatisticalInformation.
    }
  }

  {
    SELECT (COUNT(?instance) AS ?cInstancesWithNewLinks) {
      SELECT ?instance WHERE {
        ?instance a epo:SubmissionStatisticalInformation.
        ?instance epo:summarisesInformationForLotAwardOutcome ?value.
        ?value a epo:LotAwardOutcome.
      } GROUP BY ?instance
    }
  }

  {
    SELECT (COUNT(?instance) AS ?cInstancesWithOldLinks) {
      SELECT ?instance WHERE {
        VALUES ?p {epo:summarisesInformationForLotAwardOutcome epo:concernsSubmissionsForLot}
        ?instance a epo:SubmissionStatisticalInformation.
        ?instance ?p ?value.
        ?value a ?class
        FILTER (?class = epo:Lot || ?p = epo:concernsSubmissionsForLot)
      } GROUP BY ?instance
    }
  }

  FILTER (?cAllInst = ?cInstancesWithNewLinks && ?cInstancesWithOldLinks = 0)
}