#title: TED-1302 GH issue 384
#description: Select query that checks if epo:Notice and epo:AgentInRole are connected with epo:announcesRole


PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT (count(?type) as ?count) (count(?typeCompare) as ?countCompare) WHERE {
   VALUES ?s { epo:ResultNotice epo:Notice epo:PlanningNotice epo:CompetitionNotice}
   ?t rdf:type ?s .
   ?t epo:announcesRole ?r .

   ?r rdf:type ?type .
   ?r rdf:type ?typeCompare .

   VALUES ?type {
      epo:Buyer epo:OfflineAccessProvider epo:ProcurementProcedureInformationProvider
      epo:ReviewProcedureInformationProvider epo:Reviewer epo:Mediator epo:ParticipationRequestReceiver
      epo:ParticipationRequestProcessor epo:PaymentExecutor epo:BudgetProvider epo:TenderReceiver epo:TenderProcessor
      epo:AcquiringParty epo:Awarder epo:CatalogueReceiver epo:ProcurementServiceProvider epo:LeadBuyer
      epo:CentralPurchasingBody epo:AwardingCentralPurchasingBody epo:AcquiringCentralPurchasingBody
      epo:AuxiliaryParty epo:EmploymentInformationProvider epo:TaxInformationProvider
      epo:EnvironmentalProtectionInformationProvider epo:OfferingParty epo:OtherEntity epo:ReviewRequester
      epo:CatalogueProvider epo:Tenderer epo:Winner epo:Contractor epo:Subcontractor epo:AgentInRole
   }
}
HAVING (?count = ?countCompare)