#title: TED-1302 GH issue 331
#description: Ask query that checks if there are no instances of epo:ProcedureSpecificTerm

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK {
   SELECT * WHERE {
      filter exists{ ?s rdf:type epo:ProcedureSpecificTerm }
   }
}