#title: TED-1302 GH issue 342
#description: Ask query that checks for existance of NoticeIdentifier

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK {
   SELECT (COUNT(?t) AS ?notice) (COUNT(?r) AS ?identifier) WHERE {
      VALUES ?s { epo:ResultNotice epo:Notice epo:PlanningNotice epo:CompetitionNotice}
      ?t rdf:type ?s .
      ?t epo:hasID/epo:hasIdentifierValue ?r .
   }
   HAVING (?notice = ?identifier)
}