#title: TED-1302 GH issue 341
#description: Select query that checks if Subject and Object of epo:refersToPreviousNotice is the same

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

SELECT * WHERE {
   filter exists{ ?s epo:refersToPreviousNotice ?s }
}