#TED-929/TED-1133 GH issues 277
#Selects all the triples for which the epo:hasAcceleratedProcedureJustification does not have a language tag

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

select * where {
    values ?property {epo:hasAcceleratedProcedureJustification}
    ?s ?property ?value
  filter (lang(?value) = "")
}

