#TED 929/TED 275; TED 276; TED 277
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

select * where {
    values ?property {epo:hasJustification epo:hasCrossBorderLaw epo:hasAcceleratedProcedureJustification}
    ?s ?property ?value
    filter lang(?value)
}

