#title: Mandatory for AC_WEIGHTING
#description: A select SPARQL query that checks for the mandatory property cccev:weight of an epo:AwardCriterion

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX cccev: <http://data.europa.eu/m8g/>

SELECT * WHERE {
?value rdf:type epo:AwardCriterion .
    FILTER NOT EXISTS {?value cccev:weight ?t .}
} 

