#title: ND-Changes ND-RootExtension.ND-Changes - ND-Changes
#description: “ND-Changes ND-RootExtension.ND-Changes - ND-Changes” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Changes. The expected ontology instances are epo: epo:NoticeChange / epo:Notice .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Changes

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:NoticeChange .
		?this epo:describesNotice ?value }