#title: BT-766-Lot ND-Lot.ND-LotTenderingProcess.BT-766-Lot - BT-766-Lot
#description: “BT-766-Lot ND-Lot.ND-LotTenderingProcess.BT-766-Lot - BT-766-Lot” in SF corresponds to “BT-766 Dynamic Purchasing System” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingProcess/cac:ContractingSystem/cbc:ContractingSystemTypeCode[@listName='dps-usage']. The expected ontology instances are epo: epo:Lot / epo:DynamicPurchaseSystemTechniqueUsage  / at-voc:dps-usage .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingProcess/cac:ContractingSystem/cbc:ContractingSystemTypeCode[@listName='dps-usage']

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:usesTechnique  / epo:hasDPSScope ?value . }