#title: BT-36-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-PlannedDuration.GR-Lot-PlannedDuration-Period - Duration Period
#description: “BT-36-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-PlannedDuration.GR-Lot-PlannedDuration-Period - Duration Period” in SF corresponds to “BT-36 Duration Period” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/PlannedPeriod/DurationMeasure. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / epo:SpecificDuration / xsd:decimal .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/PlannedPeriod/DurationMeasure

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX time: <http://www.w3.org/2006/time#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:definesContractDuration / time:numericDuration ?value }