#title: BT-1311(d)-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-Deadlines1 - Deadline Receipt Requests
#description: “BT-1311(d)-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-Deadlines1 - Deadline Receipt Requests” in SF corresponds to “BT-1311 Deadline Receipt Requests” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/ParticipationRequestReceptionPeriod/EndDate. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / xsd:dateTime .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/ParticipationRequestReceptionPeriod/EndDate

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm  / epo:hasReceiptDeadline ?value . }