#title: ND-ProcedureTenderingProcess ND-ProcedureTenderingProcess - OPT-030-Procedure-SProvider
#description: “ND-ProcedureTenderingProcess ND-ProcedureTenderingProcess - OPT-030-Procedure-SProvider” in SF corresponds to “OPT-030 nan” in eForms. The corresponding XML element is /ContractNotice/ContractingParty/Party/ServiceProviderParty/ServiceTypeCode. The expected ontology instances are epo: epo:AgentInRole (from CL1) / rdf:langString .
#xpath: /ContractNotice/ContractingParty/Party/ServiceProviderParty/ServiceTypeCode

PREFIX cccev: <http://data.europa.eu/m8g/>

ASK WHERE { 
		?this cccev:description ?value }