#title: BT-60-Lot ND-Lot.ND-LotTenderingTerms.BT-60-Lot - BT-60-Lot
#description: “BT-60-Lot ND-Lot.ND-LotTenderingTerms.BT-60-Lot - BT-60-Lot” in SF corresponds to “BT-60 EU Funds” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cbc:FundingProgramCode[@listName='eu-funded']. The expected ontology instances are epo: epo:Lot / xsd:boolean .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cbc:FundingProgramCode[@listName='eu-funded']

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isUsingEUFunds ?value . }