#title: BT-765-Lot ND-Lot.ND-LotTenderingProcess.BT-765-Lot - BT-765-Lot
#description: “BT-765-Lot ND-Lot.ND-LotTenderingProcess.BT-765-Lot - BT-765-Lot” in SF corresponds to “BT-765 Framework Agreement” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingProcess/cac:ContractingSystem/cbc:ContractingSystemTypeCode[@listName='framework-agreement']. The expected ontology instances are epo: epo:Lot /  epo:FrameworkAgreementTechniqueUsage / at-voc:usage .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingProcess/cac:ContractingSystem/cbc:ContractingSystemTypeCode[@listName='framework-agreement']

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:usesTechnique  / epo:hasUsage ?value . }