#title: BT-7532-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-SelectionCriteria.GR-Lot-SelectionCriteria-SecondStageInvite - Selection Criteria Second Stage Invite Number Threshold
#description: “BT-7532-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-SelectionCriteria.GR-Lot-SelectionCriteria-SecondStageInvite - Selection Criteria Second Stage Invite Number Threshold” in SF corresponds to “BT-7532 Selection Criteria Second Stage Invite Number Threshold” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/SelectionCriteria/CriterionParameter/ParameterCode/@listName. The expected ontology instances are epo: epo:Lot / epo:SelectionCriterion / cccev:Constraint / xsd:decimal .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/SelectionCriteria/CriterionParameter/ParameterCode/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:specifiesSelectionCriterion / epo:hasConstraint / epo:hasThresholdValue ?value }