#title: ND-LocalLegalBasisNoID ND-ProcedureTerms.ND-LocalLegalBasisNoID - ND-LocalLegalBasisNoID
#description: “ND-LocalLegalBasisNoID ND-ProcedureTerms.ND-LocalLegalBasisNoID - ND-LocalLegalBasisNoID” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/TenderingTerms/ProcurementLegislationDocumentReference. The expected ontology instances are epo: epo:Procedure .
#xpath: /ContractNotice/TenderingTerms/ProcurementLegislationDocumentReference

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this a epo:Procedure }