#title: BT-122-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-AuctionTerms - Electronic Auction Description
#description: “BT-122-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-AuctionTerms - Electronic Auction Description” in SF corresponds to “BT-122 Electronic Auction Description” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/AuctionTerms/Description. The expected ontology instances are epo: epo:Lot / epo:EAuctionTechniqueUsage / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/AuctionTerms/Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:usesTechnique / epo:hasDescription ?value }