#title: ND-PublicOpening ND-Lot.ND-LotTenderingProcess.ND-PublicOpening - BT-97-Lot
#description: “ND-PublicOpening ND-Lot.ND-LotTenderingProcess.ND-PublicOpening - BT-97-Lot” in SF corresponds to “BT-97 Submission Language” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/Language/ID. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / at-voc:language .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/Language/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm  / epo:hasLanguage ?value . }