#title: BT-508-Procedure-Buyer content.GR-Buyer.GR-ContractingAuthority.GR-ContractingAuthority-Buyer - Buyer Profile URL
#description: “BT-508-Procedure-Buyer content.GR-Buyer.GR-ContractingAuthority.GR-ContractingAuthority-Buyer - Buyer Profile URL” in SF corresponds to “BT-508 Buyer Profile URL” in eForms. The corresponding XML element is /ContractNotice/ContractingParty/BuyerProfileURI. The expected ontology instances are epo: epo:AgentInRole (from CL1) / xsd:anyURI .
#xpath: /ContractNotice/ContractingParty/BuyerProfileURI

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:hasBuyerProfile ?value . }