#title: BT-18-Lot ND-Lot.ND-LotTenderingTerms.ND-TenderRecipient.BT-18-Lot - BT-18-Lot
#description: “BT-18-Lot ND-Lot.ND-LotTenderingTerms.ND-TenderRecipient.BT-18-Lot - BT-18-Lot” in SF corresponds to “BT-18 Submission URL” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:TenderRecipientParty/cbc:EndpointID. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / xsd:anyURI .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:TenderRecipientParty/cbc:EndpointID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasSubmissionURL ?value . }