#title: GR-LotsGroup content - LotsGroup related information covering Tendering Terms, Tendering Process and Purpose
#description: “GR-LotsGroup content - LotsGroup related information covering Tendering Terms, Tendering Process and Purpose” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot. The expected ontology instances are epo: epo:LotGroup .
#xpath: /ContractNotice/ProcurementProjectLot

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LotGroup .
		?this a epo:LotGroup }