#title: BT-76-Lot ND-Lot.ND-LotTenderingTerms.ND-TendererLegalForm.BT-76-Lot - BT-761-Lot
#description: “BT-76-Lot ND-Lot.ND-LotTenderingTerms.ND-TendererLegalForm.BT-76-Lot - BT-761-Lot” in SF corresponds to “BT-761 Tenderer Legal Form” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/TendererQualificationRequest/CompanyLegalFormCode. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / xsd:boolean .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/TendererQualificationRequest/CompanyLegalFormCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:hasContractorLegalFormRequirement ?value }