#title: BT-70-Lot ND-Lot.ND-LotTenderingTerms.ND-ExecutionRequirements.BT-70-Lot - BT-70-Lot
#description: “BT-70-Lot ND-Lot.ND-LotTenderingTerms.ND-ExecutionRequirements.BT-70-Lot - BT-70-Lot” in SF corresponds to “BT-70 Terms Performance” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/ContractExecutionRequirement/Description. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/ContractExecutionRequirement/Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:hasPerformanceConditions ?value }