#title: ND-LotReservedParticipation ND-Lot.ND-LotTenderingTerms.ND-LotReservedParticipation - BT-772-Lot
#description: “ND-LotReservedParticipation ND-Lot.ND-LotTenderingTerms.ND-LotReservedParticipation - BT-772-Lot” in SF corresponds to “BT-772 Late Tenderer Information Description” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/TendererQualificationRequest/SpecificTendererRequirement/Description. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/TendererQualificationRequest/SpecificTendererRequirement/Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm  / epo:hasLateSubmissionInformationDescription ?value . }