#title: BT-300-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-AdditionalInformation - Additional Information
#description: “BT-300-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-AdditionalInformation - Additional Information” in SF corresponds to “BT-300 Additional Information” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/Note. The expected ontology instances are epo: epo:Lot / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/Note

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:hasAdditionalInformation ?value . }