#title: BT-632-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-SubmissionTool - Tool Name
#description: “BT-632-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-SubmissionTool - Tool Name” in SF corresponds to “BT-632 Tool Name” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/AccessToolName. The expected ontology instances are epo: epo:Lot / cv:Channel / rddf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/AccessToolName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:usesChannel  / epo:hasName ?value . }