#title: GR-Organisations-Section content - Organisations
#description: “GR-Organisations-Section content - Organisations” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations. The expected ontology instances are epo: epo:OrganisationGroup (from CL2) .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this a epo:OrganisationGroup }