#title: OPT-130-Lot-EmployLegis content.GR-Lot.GR-Lot-Purpose.GR-Lot-EmployLegis - URL to Employment Legislation
#description: “OPT-130-Lot-EmployLegis content.GR-Lot.GR-Lot-Purpose.GR-Lot-EmployLegis - URL to Employment Legislation” in SF corresponds to “OPT-130 nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/EmploymentLegislationDocumentReference/Attachment/ExternalReference/URI. The expected ontology instances are epo: epo:Document / xsd:anyURI .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/EmploymentLegislationDocumentReference/Attachment/ExternalReference/URI

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Document .
		?this epo:hasAccessURL ?value }