#title: BT-578-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-SecurityClearance2 - Security Clearance
#description: “BT-578-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-SecurityClearance2 - Security Clearance” in SF corresponds to “BT-578 Security Clearance” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/SecurityClearanceTerm/Code. The expected ontology instances are epo: epo:Lot / epo:SecurityClearanceTerm .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/SecurityClearanceTerm/Code

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasTitle  ?value . }