#title: BT-141(a)-notice ND-RootExtension.ND-Changes.ND-Change.BT-141(a)-notice - BT-13716-notice
#description: “BT-141(a)-notice ND-RootExtension.ND-Changes.ND-Change.BT-141(a)-notice - BT-13716-notice” in SF corresponds to “BT-13716 Change Previous Notice Section Identifier” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Changes/Change/ChangedSectionIdentifier. The expected ontology instances are epo: epo:ElementChangeDescription / xsd:anyURI .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Changes/Change/ChangedSectionIdentifier

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ElementChangeDescription .
		?this epo:hasPreviousVersionOfElementReference ?value }