#title: BT-510(a)-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress.BT-510(a)-Organization-Company - BT-510(a)-Organization-Company
#description: “BT-510(a)-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress.BT-510(a)-Organization-Company - BT-510(a)-Organization-Company” in SF corresponds to “BT-510 Organisation Street” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/PostalAddress/StreetName. The expected ontology instances are epo: org:Organization (from CL2) /  locn:Address / rdf:langString .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/PostalAddress/StreetName

PREFIX cv: <http://data.europa.eu/m8g/>
PREFIX locn: <http://www.w3.org/ns/locn#>

ASK WHERE { 
		?this cv:registeredAddress / locn:thoroughfare ?value . }