#title: BT-31-Procedure content.GR-Procedure.GR-Procedure-TenderingTerms.GR-Procedure-MaxLots - Lots Max Allowed
#description: “BT-31-Procedure content.GR-Procedure.GR-Procedure-TenderingTerms.GR-Procedure-MaxLots - Lots Max Allowed” in SF corresponds to “BT-31 Lots Max Allowed” in eForms. The corresponding XML element is /ContractNotice/TenderingTerms/LotDistribution/MaximumLotsSubmittedNumeric. The expected ontology instances are epo: epo:Procedure / xsd:integer .
#xpath: /ContractNotice/TenderingTerms/LotDistribution/MaximumLotsSubmittedNumeric

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasMaximumLotSubmissionAllowed ?value }