#title: ND-ProcedureMainClassification ND-ProcedureProcurementScope.ND-ProcedureMainClassification - BT-271-Procedure
#description: “ND-ProcedureMainClassification ND-ProcedureProcurementScope.ND-ProcedureMainClassification - BT-271-Procedure” in SF corresponds to “BT-271 Framework Maximum Value” in eForms. The corresponding XML element is /ContractNotice/ProcurementProject/RequestedTenderTotal/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/FrameworkMaximumAmount. The expected ontology instances are epo: epo:Procedure / epo:Lot / xsd:MonetaryValue / xsd:decimal .
#xpath: /ContractNotice/ProcurementProject/RequestedTenderTotal/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/FrameworkMaximumAmount

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasProcurementScopeDividedIntoLot / epo:hasFrameworkAgreementMaximumValue / epo:hasAmountValue ?value }