#title: GR-Lot-ProcurementType-Strategic content.GR-Lot.GR-Lot-Purpose.GR-Lot-ProcurementType - Information (Description) about Strategic Procurement Type
#description: “GR-Lot-ProcurementType-Strategic content.GR-Lot.GR-Lot-Purpose.GR-Lot-ProcurementType - Information (Description) about Strategic Procurement Type” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/ProcurementAdditionalType. The expected ontology instances are epo: epo:StrategicProcurement .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/ProcurementAdditionalType

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:StrategicProcurement .
		?this a  epo:StrategicProcurement }