#title: BT-728-Lot ND-Lot.ND-LotProcurementScope.ND-LotPlacePerformance.BT-728-Lot - BT-728-Lot
#description: “BT-728-Lot ND-Lot.ND-LotProcurementScope.ND-LotPlacePerformance.BT-728-Lot - BT-728-Lot” in SF corresponds to “BT-728 Place Performance Additional Information” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:RealizedLocation/cbc:Description. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / dct:Location / rdf:langString .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:RealizedLocation/cbc:Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:hasPlaceOfPerformanceAdditionalInformation ?value . }