#title: BT-751-Lot ND-Lot.ND-LotTenderingTerms.ND-FinancialGuarantee.BT-751-Lot - BT-751-Lot
#description: “BT-751-Lot ND-Lot.ND-LotTenderingTerms.ND-FinancialGuarantee.BT-751-Lot - BT-751-Lot” in SF corresponds to “BT-751 Guarantee Required” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/RequiredFinancialGuarantee/GuaranteeTypeCode/@listName. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / xsd:boolean .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/RequiredFinancialGuarantee/GuaranteeTypeCode/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:isGuaranteeRequired ?value . }