#title: BT-758-notice ND-RootExtension.ND-Changes.BT-758-notice - BT-762-notice
#description: “BT-758-notice ND-RootExtension.ND-Changes.BT-758-notice - BT-762-notice” in SF corresponds to “BT-762 Change Reason Description” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Changes/ChangeReason/ReasonDescription. The expected ontology instances are epo: epo:ElementChangeDescription / rdf:langString .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Changes/ChangeReason/ReasonDescription

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ElementChangeDescription .
		?this epo:hasChangeReasonDescription ?value }