#title: BT-16-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress.BT-16-Organization-Company - BT-16-Organization-Company
#description: “BT-16-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress.BT-16-Organization-Company - BT-16-Organization-Company” in SF corresponds to “BT-16 Organisation Part Name” in eForms. The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company/cac:PostalAddress/cbc:Department. The expected ontology instances are epo: org:Organization (from CL2) / rdf:langString .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company/cac:PostalAddress/cbc:Department

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:hasOrganisationUnit ?value . }