#title: BT-541-Lot ND-Lot.ND-LotTenderingTerms.ND-AwardingTerms.ND-LotAwardCriteria.ND-LotAwardCriterion.ND-LotAwardCriterionParameters.ND-LotAwardCriterionParameter.BT-541-Lot - BT-541-Lot
#description: “BT-541-Lot ND-Lot.ND-LotTenderingTerms.ND-AwardingTerms.ND-LotAwardCriteria.ND-LotAwardCriterion.ND-LotAwardCriterionParameters.ND-LotAwardCriterionParameter.BT-541-Lot - BT-541-Lot” in SF corresponds to “BT-541 Award Criterion Number” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion/cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter/efbc:ParameterNumeric. The expected ontology instances are epo: epo:Lot / epo:AwardCriterion / xsd:decimal OR epo:Lot / epo:AwardCriterion / xsd:decimal OR epo:Lot / epo:AwardCriterion / cccev:Constraint / xsd:decimal .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:AwardingTerms/cac:AwardingCriterion/cac:SubordinateAwardingCriterion/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:AwardCriterionParameter/efbc:ParameterNumeric

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		{?this epo:specifiesAwardCriterion / cccev:weight ?value} UNION {?this epo:specifiesAwardCriterion / epo:hasFixedValue ?value} UNION  {?this epo:specifiesAwardCriterion / epo:hasConstraint / epo:hasThresholdValue ?value} }