#title: BT-1311(t)-Lot ND-Lot.ND-LotTenderingProcess.ND-ParticipationRequestPeriod.BT-1311(t)-Lot - BT-1311(t)-Lot
#description: “BT-1311(t)-Lot ND-Lot.ND-LotTenderingProcess.ND-ParticipationRequestPeriod.BT-1311(t)-Lot - BT-1311(t)-Lot” in SF corresponds to “BT-1311 Deadline Receipt Requests” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/ParticipationRequestReceptionPeriod/EndTime. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / xsd:dateTime .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/ParticipationRequestReceptionPeriod/EndTime

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm  / epo:hasReceiptExpressionDeadline ?value . }