#title: ND-SecondStage ND-Lot.ND-LotTenderingProcess.ND-SecondStage - BT-52-Lot
#description: “ND-SecondStage ND-Lot.ND-LotTenderingProcess.ND-SecondStage - BT-52-Lot” in SF corresponds to “BT-52 Successive Reduction” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/CandidateReductionConstraintIndicator. The expected ontology instances are epo: epo:Lot / epo:MultipleStageProcedureTerm / xsd:boolean .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/CandidateReductionConstraintIndicator

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasSuccessiveReduction ?value }