#title: BT-92-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-PostAwardProcess - Electronic Ordering
#description: “BT-92-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-PostAwardProcess - Electronic Ordering” in SF corresponds to “BT-92 Electronic Ordering” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/PostAwardProcess/ElectronicOrderUsageIndicator. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / xsd:boolean .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/PostAwardProcess/ElectronicOrderUsageIndicator

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:hasEOrdering true . }