#title: BT-745-Lot ND-Lot.ND-LotTenderingProcess.ND-NoESubmission.BT-745-Lot - BT-745-Lot
#description: “BT-745-Lot ND-Lot.ND-LotTenderingProcess.ND-NoESubmission.BT-745-Lot - BT-745-Lot” in SF corresponds to “BT-745 Submission Non-electronic Description” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingProcess/cac:ProcessJustification[cbc:ProcessReasonCode/@listName='no-esubmission-justification']/cbc:Description. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / rdf:langString .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingProcess/cac:ProcessJustification[cbc:ProcessReasonCode/@listName='no-esubmission-justification']/cbc:Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasNonElectronicSubmissionDescription ?value }