#title: ND-ProcedureProcurementScope ND-ProcedureProcurementScope - BT-01(f)-Procedure
#description: “ND-ProcedureProcurementScope ND-ProcedureProcurementScope - BT-01(f)-Procedure” in SF corresponds to “BT-01 Procedure Legal Basis” in eForms. The corresponding XML element is /ContractNotice/TenderingTerms/ProcurementLegislationDocumentReference/DocumentDescription. The expected ontology instances are epo: epo:Procedure / rdf:langString .
#xpath: /ContractNotice/TenderingTerms/ProcurementLegislationDocumentReference/DocumentDescription

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this cccev:description ?value . }