#title: BT-52-Lot ND-Lot.ND-LotTenderingProcess.BT-52-Lot - BT-752-Lot
#description: “BT-52-Lot ND-Lot.ND-LotTenderingProcess.BT-52-Lot - BT-752-Lot” in SF corresponds to “BT-752 Selection Criteria Second Stage Invite Number” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/SelectionCriteria/CriterionParameter/ParameterNumeric. The expected ontology instances are epo: epo:Lot / epo:SelectionCriterion / xsd:decimal
OR
epo:Lot / epo:SelectionCriterion / cccev:Constraint / xsd:decimal .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/SelectionCriteria/CriterionParameter/ParameterNumeric

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:specifiesSelectionCriterion / cccev:weight ?value
OR
?this epo:specifiesSelectionCriterion / epo:hasConstraint / epo:hasThresholdValue ?value }