#title: BT-625-Lot ND-Lot.ND-LotProcurementScope.BT-625-Lot - BT-625-Lot
#description: “BT-625-Lot ND-Lot.ND-LotProcurementScope.BT-625-Lot - BT-625-Lot” in SF corresponds to “BT-625 Unit” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/EstimatedOverallContractQuantity/@unitCode. The expected ontology instances are epo: epo:Lot / epo:Purpose / epo:Quantity / at-voc:measurement-unit .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/EstimatedOverallContractQuantity/@unitCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:hasPurpose / epo:hasTotalQuantity / epo:hasUnitCode ?value . }