#title: BT-113-Lot ND-Lot.ND-LotTenderingProcess.ND-FA.BT-113-Lot - ND-FA
#description: “BT-113-Lot ND-Lot.ND-LotTenderingProcess.ND-FA.BT-113-Lot - ND-FA” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/FrameworkAgreement. The expected ontology instances are epo: epo:Lot / epo:FrameworkAgreementTerm .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/FrameworkAgreement

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToProcedureSpecificTerm ?value . }