#title: BT-726-LotsGroup ND-LotsGroup.ND-LotsGroupProcurementScope.BT-726-LotsGroup - BT-726-LotsGroup
#description: “BT-726-LotsGroup ND-LotsGroup.ND-LotsGroupProcurementScope.BT-726-LotsGroup - BT-726-LotsGroup” in SF corresponds to “BT-726 Suitable For SMEs” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/SMESuitableIndicator. The expected ontology instances are epo: epo:LotGroup / xsd:boolean .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/SMESuitableIndicator

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LotGroup .
		?this epo:isSMESuitable ?value }