#title: BT-113-Lot ND-Lot.ND-LotTenderingProcess.ND-FA.BT-113-Lot - BT-113-Lot
#description: “BT-113-Lot ND-Lot.ND-LotTenderingProcess.ND-FA.BT-113-Lot - BT-113-Lot” in SF corresponds to “BT-113 Framework Maximum Participants Number” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingProcess/cac:FrameworkAgreement/cbc:MaximumOperatorQuantity. The expected ontology instances are epo: epo:Lot / epo:FrameworkAgreementTerm / rdf:langString .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingProcess/cac:FrameworkAgreement/cbc:MaximumOperatorQuantity

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasMaximumParticipantsNumber ?value . }