#title: GR-Lot-Scope-AdditionalClassification content.GR-Lot.GR-Lot-Purpose.GR-Lot-Scope - Classification for an Additional Commodity of a Lot
#description: “GR-Lot-Scope-AdditionalClassification content.GR-Lot.GR-Lot-Purpose.GR-Lot-Scope - Classification for an Additional Commodity of a Lot” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/AdditionalCommodityClassification. The expected ontology instances are epo: epo:Purpose .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/AdditionalCommodityClassification

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Purpose .
		?this a epo:Purpose }