#title: BT-503-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyContact.BT-503-Organization-Company - BT-503-Organization-Company
#description: “BT-503-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyContact.BT-503-Organization-Company - BT-503-Organization-Company” in SF corresponds to “BT-503 Organisation Contact Telephone Number” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/Contact/Telephone. The expected ontology instances are epo: epo:AgentInRole (from CL1) / org:Organization (from CL2) / cpov:ContactPoint / rdf:langString .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/Contact/Telephone

PREFIX cpov: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:hasPrimaryContactPoint / cpov:telephone ?value . }