#title: OPT-113-Lot-EmployLegis content.GR-Lot.GR-Lot-Purpose.GR-Lot-EmployLegis - Employment Legislation Document ID
#description: “OPT-113-Lot-EmployLegis content.GR-Lot.GR-Lot-Purpose.GR-Lot-EmployLegis - Employment Legislation Document ID” in SF corresponds to “OPT-113 nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/EmploymentLegislationDocumentReference/ID. The expected ontology instances are epo: epo:Document / epo:Identifier / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/EmploymentLegislationDocumentReference/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Document .
		?this epo:hasID / epo:hasIdentifierValue ?value }