#title: ND-ExclusionGrounds ND-ProcedureTerms.ND-TendererQualificationRequest.ND-ExclusionGrounds - ND-ExclusionGrounds
#description: “ND-ExclusionGrounds ND-ProcedureTerms.ND-TendererQualificationRequest.ND-ExclusionGrounds - ND-ExclusionGrounds” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /*/cac:TenderingTerms/cac:TendererQualificationRequest/cac:SpecificTendererRequirement. The expected ontology instances are epo: epo:ExclusionGround .
#xpath: /*/cac:TenderingTerms/cac:TendererQualificationRequest/cac:SpecificTendererRequirement

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ExclusionGround .
		?this a epo:ExclusionGround }