#title: BT-17-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-SubmissionMethod - SubmissionElectronic
#description: “BT-17-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-SubmissionMethod - SubmissionElectronic” in SF corresponds to “BT-17 Submission Electronic” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/SubmissionMethodCode/@listName. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / at-voc:permission .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/SubmissionMethodCode/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasESubmissionPermission ?value . }