#title: metadata - Notice Preferred Publication Date
#description: “metadata - Notice Preferred Publication Date” in SF corresponds to “BT-738 Notice Preferred Publication Date” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:RequestedPublicationDate. The expected ontology instances are epo: Metadata not Mapped .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:RequestedPublicationDate



ASK WHERE { 
		Metadata not Mapped }