#title: BT-11-Procedure-Buyer ND-ContractingParty.BT-11-Procedure-Buyer - BT-11-Procedure-Buyer
#description: “BT-11-Procedure-Buyer ND-ContractingParty.BT-11-Procedure-Buyer - BT-11-Procedure-Buyer” in SF corresponds to “BT-11 Buyer Legal Type” in eForms. The corresponding XML element is /*/cac:ContractingParty/cac:ContractingPartyType/cbc:PartyTypeCode[@listName='buyer-legal-type']. The expected ontology instances are epo: org:Organization / at-voc:buyer-legal-type (from buyer_legal_type.csv) .
#xpath: /*/cac:ContractingParty/cac:ContractingPartyType/cbc:PartyTypeCode[@listName='buyer-legal-type']

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type org:Organization .
		?this epo:hasBuyerLegalType ?value . }