#title: BT-727-Procedure ND-ProcedureProcurementScope.ND-ProcedurePlacePerformanceAdditionalInformation.ND-ProcedurePlacePerformance.BT-727-Procedure - BT-727-Procedure
#description: “BT-727-Procedure ND-ProcedureProcurementScope.ND-ProcedurePlacePerformanceAdditionalInformation.ND-ProcedurePlacePerformance.BT-727-Procedure - BT-727-Procedure” in SF corresponds to “BT-727 Place Performance Services Other” in eForms. The corresponding XML element is /*/cac:ProcurementProject/cac:RealizedLocation/cac:Address/cbc:Region. The expected ontology instances are epo: epo:Procedure / epo:ContractTerm / at-voc:other-place-service .
#xpath: /*/cac:ProcurementProject/cac:RealizedLocation/cac:Address/cbc:Region

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:foreseesContractSpecificTerm / epo:hasBroadPlaceOfPerformance ?value . }