#title: BT-539-LotsGroup ND-LotsGroup.ND-LotsGroupAwardingTerms.ND-LotsGroupAwardCriteria.ND-LotsGroupAwardCriterion.BT-539-LotsGroup - BT-539-LotsGroup
#description: “BT-539-LotsGroup ND-LotsGroup.ND-LotsGroupAwardingTerms.ND-LotsGroupAwardCriteria.ND-LotsGroupAwardCriterion.BT-539-LotsGroup - BT-539-LotsGroup” in SF corresponds to “BT-539 Award Criterion Type” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/AwardingCriterionTypeCode/@listName. The expected ontology instances are epo: epo:AwardCriterion / at-voc:award-criterion-type .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/AwardingCriterionTypeCode/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AwardCriterion .
		?this epo:hasAwardCriterionType ?value }