#title: ND-CompanyContact ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyContact - ND-CompanyContact
#description: “ND-CompanyContact ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyContact - ND-CompanyContact” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company/cac:Contact. The expected ontology instances are epo: org:Organization (from CL2) / cpov:ContactPoint .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company/cac:Contact

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:hasPrimaryContactPoint ?value . }