#title: BT-765-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-ContractingSystem - Framework Agreement
#description: “BT-765-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-ContractingSystem - Framework Agreement” in SF corresponds to “BT-765 Framework Agreement” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/ContractingSystem/ContractingSystemTypeCode@listName. The expected ontology instances are epo: epo:Lot /  epo:TechniqueUsage / at-voc:usage .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/ContractingSystem/ContractingSystemTypeCode@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:usesTechnique  / epo:hasUsage ?value . }