#title: BT-719-notice ND-RootExtension.ND-Changes.ND-Change.BT-719-notice - BT-718-notice
#description: “BT-719-notice ND-RootExtension.ND-Changes.ND-Change.BT-719-notice - BT-718-notice” in SF corresponds to “BT-718 Change Procurement Documents” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Changes/Change/ProcurementDocumentsChangeIndicator. The expected ontology instances are epo: epo:ElementChangeDescription / xsd:boolean .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Changes/Change/ProcurementDocumentsChangeIndicator

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ElementChangeDescription .
		?this epo:isProcurementDocumentChanged ?value }