#title: BT-263-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-Scope.GR-Lot-Scope-AdditionalClassification - Additional Classification Code
#description: “BT-263-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-Scope.GR-Lot-Scope-AdditionalClassification - Additional Classification Code” in SF corresponds to “BT-263 Additional Classification Codes” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/AdditionalCommodityClassification/ItemClassificationCode. The expected ontology instances are epo: epo:Lot / epo:Purpose / at-voc:cpvsuppl (from cpvsuppl.json) .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/AdditionalCommodityClassification/ItemClassificationCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:hasPurpose / epo:hasAdditionalClassification ?value . }