#title: BT-79-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-Requirements2SecurityClearance1 - Performing Staff Qualification
#description: “BT-79-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-Requirements2SecurityClearance1 - Performing Staff Qualification” in SF corresponds to “BT-79 Performing Staff Qualification” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/RequiredCurriculaCode. The expected ontology instances are epo: epo:Lot / epo:SecurityClearanceTerm / at-voc:requirement-stage .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/RequiredCurriculaCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasPerformingStaffQualificationInformation ?value }