#title: BT-536-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-PlannedDuration.GR-Lot-PlannedDuration-Dates - Duration Start Date
#description: “BT-536-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-PlannedDuration.GR-Lot-PlannedDuration-Dates - Duration Start Date” in SF corresponds to “BT-536 Duration Start Date” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/PlannedPeriod/StartDate. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / epo:Period / xsd:dateTime .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/PlannedPeriod/StartDate

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:definesContractPeriod / epo:hasBeginning ?value . }