#title: ND-StrategicProcurementType ND-Lot.ND-LotProcurementScope.ND-StrategicProcurementType - BT-776-Lot
#description: “ND-StrategicProcurementType ND-Lot.ND-LotProcurementScope.ND-StrategicProcurementType - BT-776-Lot” in SF corresponds to “BT-776 Procurement of Innovation” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/ProcurementAdditionalType/ProcurementTypeCode/@listName. The expected ontology instances are epo: epo:Lot / epo:InnovativeProcurement / at-voc:innovative-acquisition .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/ProcurementAdditionalType/ProcurementTypeCode/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:fulfillsStrategicProcurement / epo:fulfillsRequirement ?value }