#title: BT-541-LotsGroup ND-LotsGroup.ND-LotsGroupAwardingTerms.ND-LotsGroupAwardCriteria.ND-LotsGroupAwardCriterion.ND-LotsGroupAwardCriterionParameters.ND-LotsGroupAwardCriterionParameter.BT-541-LotsGroup - ND-LotsGroupAwardCriterionParameter
#description: “BT-541-LotsGroup ND-LotsGroup.ND-LotsGroupAwardingTerms.ND-LotsGroupAwardCriteria.ND-LotsGroupAwardCriterion.ND-LotsGroupAwardCriterionParameters.ND-LotsGroupAwardCriterionParameter.BT-541-LotsGroup - ND-LotsGroupAwardCriterionParameter” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/AwardCriterionParameter. The expected ontology instances are epo: epo:AwardCriterion .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/AwardCriterionParameter

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AwardCriterion .
		?this a epo:AwardCriterion }