#title: BT-633-Organization ND-RootExtension.ND-Organizations.ND-Organization.BT-633-Organization - BT-633-Organization
#description: “BT-633-Organization ND-RootExtension.ND-Organizations.ND-Organization.BT-633-Organization - BT-633-Organization” in SF corresponds to “BT-633 Organisation Natural Person” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/NaturalPersonIndicator. The expected ontology instances are epo: epo:AgentInRole (from CL1) / org:Organization (from CL2) / rdf:langString .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/NaturalPersonIndicator

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

ASK WHERE { 
		?this epo:playedBy / foaf:name ?value . }