#title: GR-LateTendererInformation content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-TendererQualification - Information about late provision of information by the tenderer (possibility and description of the information)
#description: “GR-LateTendererInformation content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-TendererQualification - Information about late provision of information by the tenderer (possibility and description of the information)” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/TendererQualificationRequest/SpecificTendererRequirement. The expected ontology instances are epo: epo:SubmissionTerm .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/TendererQualificationRequest/SpecificTendererRequirement

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:SubmissionTerm .
		?this a epo:SubmissionTerm }