#title: BT-27-Procedure ND-ProcedureProcurementScope.ND-ProcedureValueEstimate.BT-27-Procedure - BT-27-Procedure
#description: “BT-27-Procedure ND-ProcedureProcurementScope.ND-ProcedureValueEstimate.BT-27-Procedure - BT-27-Procedure” in SF corresponds to “BT-27 Estimated Value” in eForms. The corresponding XML element is /ContractNotice/ProcurementProject/RequestedTenderTotal/EstimatedOverallContractAmount. The expected ontology instances are epo: epo:Procedure / epo:MonetaryValue / xsd:decimal .
#xpath: /ContractNotice/ProcurementProject/RequestedTenderTotal/EstimatedOverallContractAmount

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasEstimatedValue / epo:hasAmountValue ?value . }