#title: BT-97-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-Submission Language - Submission Language
#description: “BT-97-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-Submission Language - Submission Language” in SF corresponds to “BT-97 Submission Language” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/Language/ID. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / at-voc:language .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/Language/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm  / epo:hasLanguage ?value . }