#title: BT-758-notice ND-RootExtension.ND-Changes.BT-758-notice - BT-758-notice
#description: “BT-758-notice ND-RootExtension.ND-Changes.BT-758-notice - BT-758-notice” in SF corresponds to “BT-758 Change Notice Version Identifier” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Changes/ChangedNoticeIdentifier. The expected ontology instances are epo: epo:NoticeChange / epo:Notice / epo:Indentifier / rdf:langString .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Changes/ChangedNoticeIdentifier

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:NoticeChange .
		?this epo:refersToPreviousNotice /  epo:hasID / epo:hasIdentifierValue ?value }