#title: BT-67(a)-Procedure ND-ProcedureTerms.ND-TendererQualificationRequest.ND-ExclusionGrounds.BT-67(a)-Procedure - BT-67(a)-Procedure
#description: “BT-67(a)-Procedure ND-ProcedureTerms.ND-TendererQualificationRequest.ND-ExclusionGrounds.BT-67(a)-Procedure - BT-67(a)-Procedure” in SF corresponds to “BT-67 Exclusion Grounds” in eForms. The corresponding XML element is /*/cac:TenderingTerms/cac:TendererQualificationRequest/cac:SpecificTendererRequirement/cbc:TendererRequirementTypeCode[@listName='exclusion-ground']. The expected ontology instances are epo: epo:Procedure / epo:ExclusionGround / at-voc:criterion .
#xpath: /*/cac:TenderingTerms/cac:TendererQualificationRequest/cac:SpecificTendererRequirement/cbc:TendererRequirementTypeCode[@listName='exclusion-ground']

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:specifiesExclusionGround / cccev:type ?value }