#title: BT-330-Procedure ND-ProcedureTerms.ND-LotDistribution.ND-GroupComposition.BT-330-Procedure - BT-330-Procedure
#description: “BT-330-Procedure ND-ProcedureTerms.ND-LotDistribution.ND-GroupComposition.BT-330-Procedure - BT-330-Procedure” in SF corresponds to “BT-330 Group Identifier” in eForms. The corresponding XML element is /*/cac:TenderingTerms/cac:LotDistribution/cac:LotsGroup/cbc:LotsGroupID. The expected ontology instances are epo: epo:LotGroup / epo:Identifier / xsd:string .
#xpath: /*/cac:TenderingTerms/cac:LotDistribution/cac:LotsGroup/cbc:LotsGroupID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LotGroup .
		?this epo:hasID / epo:hasIdentifierValue ?value . }