#title: BT-539-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-AwardCriteria.GR-Lot-AwardCriteria-Criterion - Award Criterion Type
#description: “BT-539-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-AwardCriteria.GR-Lot-AwardCriteria-Criterion - Award Criterion Type” in SF corresponds to “BT-539 Award Criterion Type” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/AwardingCriterionTypeCode@listName. The expected ontology instances are epo: epo:Lot / epo:AwardCriterion / at-voc:award-criterion-type .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/AwardingCriterionTypeCode@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasAwardCriterionType ?value }