#title: BT-755-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-ProcurementType.GR-Lot-ProcurementType-Accessibility - Accessibility Justification
#description: “BT-755-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-ProcurementType.GR-Lot-ProcurementType-Accessibility - Accessibility Justification” in SF corresponds to “BT-755 Accessibility Justification” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/ProcurementAdditionalType/ProcurementType. The expected ontology instances are epo: epo:Lot / epo:StrategicProcurement / at-voc:accessibility .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/ProcurementAdditionalType/ProcurementType

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:fulfillsStrategicProcurement / epo:hasNonAccessibilityCriterionJustification ?value }