#title: BT-615-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-ProcurementDocuments - Documents Restricted URL
#description: “BT-615-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-ProcurementDocuments - Documents Restricted URL” in SF corresponds to “BT-615 Documents Restricted URL” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/Attachment/ExternalReference/URI. The expected ontology instances are epo: epo:AccessTerm / xsd:anyURI .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/Attachment/ExternalReference/URI

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AccessTerm .
		?this epo:hasRestrictedAccessURL ?value }