#title: OPT-301-Lot-ReviewInfo ND-Lot.ND-LotTenderingTerms.ND-LotReviewTerms.OPT-301-Lot-ReviewInfo - OPT-301-Lot-ReviewOrg
#description: “OPT-301-Lot-ReviewInfo ND-Lot.ND-LotTenderingTerms.ND-LotReviewTerms.OPT-301-Lot-ReviewInfo - OPT-301-Lot-ReviewOrg” in SF corresponds to “OPT-301 nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AppealTerms/AppealReceiverParty/PartyIdentification/ID. The expected ontology instances are epo: epo:AgentInRole (from CL1) / org:Organization (from CL2) / epo:Identifier / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AppealTerms/AppealReceiverParty/PartyIdentification/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:playedBy / epo:hasID / epo:hasIdentifierValue ?value . }