#title: GR-Procedure-PlaceOfPerformance content.GR-Procedure.GR-Procedure-Purpose - Additional Information about the location where the Procurement, for the Procedure as a whole, should take place
#description: “GR-Procedure-PlaceOfPerformance content.GR-Procedure.GR-Procedure-Purpose - Additional Information about the location where the Procurement, for the Procedure as a whole, should take place” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProject/RealizedLocation. The expected ontology instances are epo: epo:ContractTerm .
#xpath: /ContractNotice/ProcurementProject/RealizedLocation

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ContractTerm .
		?this a epo:ContractTerm }