#title: BT-130-Lot ND-Lot.ND-LotTenderingProcess.BT-130-Lot - BT-130-Lot
#description: “BT-130-Lot ND-Lot.ND-LotTenderingProcess.BT-130-Lot - BT-130-Lot” in SF corresponds to “BT-130 Dispatch Invitation Tender” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/InvitationSubmissionPeriod/StartDate. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / xsd:date .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/InvitationSubmissionPeriod/StartDate

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm  / epo:hasEstimatedInvitationToTenderDate ?value . }