#title: GR-LotsGroup-AwardCriteria-Criterion-Parameters content.GR-LotsGroup.GR-LotsGroup-TenderingTerms.GR-LotsGroup-AwardCriteria.GR-LotsGroup-AwardCriteria-Criterion - Non UBL Native Subordinate Award Criteria elements for a Group of Lots
#description: “GR-LotsGroup-AwardCriteria-Criterion-Parameters content.GR-LotsGroup.GR-LotsGroup-TenderingTerms.GR-LotsGroup-AwardCriteria.GR-LotsGroup-AwardCriteria-Criterion - Non UBL Native Subordinate Award Criteria elements for a Group of Lots” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension. The expected ontology instances are epo: epo:AwardCriterion .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AwardCriterion .
		?this a epo:AwardCriterion }