#title: metadata - Notice Type
#description: “metadata - Notice Type” in SF corresponds to “BT-02 Notice Type” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:NoticeTypeCode. The expected ontology instances are epo: Metadata not Mapped .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:NoticeTypeCode



ASK WHERE { 
		Metadata not Mapped }