#title: ND-LotTenderingProcess ND-Lot.ND-LotTenderingProcess - BT-137-Lot
#description: “ND-LotTenderingProcess ND-Lot.ND-LotTenderingProcess - BT-137-Lot” in SF corresponds to “BT-137 Purpose Lot Identifier” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ID. The expected ontology instances are epo: epo:Lot / epo:Identifier / xsd:string .
#xpath: /ContractNotice/ProcurementProjectLot/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:hasID / epo:hasIdentifierValue ?value . }