#title: GR-Nda content.GR-Lot.GR-Lot-TenderingTerms - Description of the NDA
#description: “GR-Nda content.GR-Lot.GR-Lot-TenderingTerms - Description of the NDA” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/ContractExecutionRequirement. The expected ontology instances are epo: epo:Business .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/ContractExecutionRequirement

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Business .
		?this a epo:Business }