#title: BT-728-Procedure content.GR-Procedure.GR-Procedure-Purpose.GR-Procedure-PlaceOfPerformance - Place Performance Additional Information
#description: “BT-728-Procedure content.GR-Procedure.GR-Procedure-Purpose.GR-Procedure-PlaceOfPerformance - Place Performance Additional Information” in SF corresponds to “BT-728 Place Performance Additional Information” in eForms. The corresponding XML element is /ContractNotice/ProcurementProject/RealizedLocation/Description. The expected ontology instances are epo: epo:Procedure / epo:ContractTerm / locn:Address / rdf:langString .
#xpath: /ContractNotice/ProcurementProject/RealizedLocation/Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:foreseesContractSpecificTerm /  locn:address / locn:hasDescription ?value . }