#title: BT-719-notice content.GR-Change.GR-ChangeSections - Change Procurement Documents Date
#description: “BT-719-notice content.GR-Change.GR-ChangeSections - Change Procurement Documents Date” in SF corresponds to “BT-719 Change Procurement Documents Date” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Changes/Change/ProcurementDocumentsChangeDate. The expected ontology instances are epo: epo:ElementChangeDescription / xsd:date .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Changes/Change/ProcurementDocumentsChangeDate

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ElementChangeDescription .
		?this epo:hasProcurementDocumentChangeDate ?value }