#title: BT-633-Organization ND-RootExtension.ND-Organizations.ND-Organization.BT-633-Organization - BT-633-Organization
#description: “BT-633-Organization ND-RootExtension.ND-Organizations.ND-Organization.BT-633-Organization - BT-633-Organization” in SF corresponds to “BT-633 Organisation Natural Person” in eForms. The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efbc:NaturalPersonIndicator. The expected ontology instances are epo: cpv:Person .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efbc:NaturalPersonIndicator

PREFIX cpv: <^>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type cpv:Person .
		?this a cpv:Person }