#title: BT-774-Lot ND-Lot.ND-LotProcurementScope.BT-774-Lot - BT-774-Lot
#description: “BT-774-Lot ND-Lot.ND-LotProcurementScope.BT-774-Lot - BT-774-Lot” in SF corresponds to “BT-774 Green Procurement” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/ProcurementAdditionalType/ProcurementTypeCode/@listName. The expected ontology instances are epo: epo:Lot / epo:GreenProcurement / at-voc:environmental-impact .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/ProcurementAdditionalType/ProcurementTypeCode/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:fulfillsStrategicProcurement / epo:fulfillsRequirement ?value }