#title: ND-ChangeReason ND-RootExtension.ND-Changes.ND-ChangeReason - ND-ChangeReason
#description: “ND-ChangeReason ND-RootExtension.ND-Changes.ND-ChangeReason - ND-ChangeReason” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Changes/efac:ChangeReason. The expected ontology instances are epo: epo:NoticeChange / epo:ElementChangeDescription .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Changes/efac:ChangeReason

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:NoticeChange .
		?this epo:hasElementChange ?value }