#title: BT-10-Procedure-Buyer content.GR-Buyer.GR-ContractingAuthority.GR-ContractingAuthority-Buyer - Activity Authority
#description: “BT-10-Procedure-Buyer content.GR-Buyer.GR-ContractingAuthority.GR-ContractingAuthority-Buyer - Activity Authority” in SF corresponds to “BT-10 Activity Authority” in eForms. The corresponding XML element is /ContractNotice/ContractingParty/ContractingActivity/ActivityTypeCode@listName. The expected ontology instances are epo: epo:AgentInRole / at-voc:main-activity (from main_activity.csv) .
#xpath: /ContractNotice/ContractingParty/ContractingActivity/ActivityTypeCode@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AgentInRole .
		?this epo:hasMainActivity ?value . }