#title: GR-Lot-ProcurementDocuments content.GR-Lot.GR-Lot-SubmissionInfo - Procurement Document information for a Lot, independent from the restricted aspect
#description: “GR-Lot-ProcurementDocuments content.GR-Lot.GR-Lot-SubmissionInfo - Procurement Document information for a Lot, independent from the restricted aspect” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference. The expected ontology instances are epo: epo:AccessTerm .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AccessTerm .
		?this a epo:AccessTerm }