#title: BT-507-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress.BT-507-Organization-Company - BT-507-Organization-Company
#description: “BT-507-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress.BT-507-Organization-Company - BT-507-Organization-Company” in SF corresponds to “BT-507 Organisation Country Subdivision” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/PostalAddress/CountrySubentityCode. The expected ontology instances are epo: org:Organization (from CL2) / locn:Address / at-voc:nuts (from nuts.json) .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/PostalAddress/CountrySubentityCode

PREFIX cv: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this cv:registeredAddress / epo:hasNutsCode ?value . }