#title: BT-538-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-PlannedDuration - Duration Other
#description: “BT-538-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-PlannedDuration - Duration Other” in SF corresponds to “BT-538 Duration Other” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/PlannedPeriod/DescriptionCode. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / epo:Period /  rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/PlannedPeriod/DescriptionCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:definesContractPeriod / epo:hasDescription ?value . }