#title: OPP-052-Organization ND-RootExtension.ND-Organizations.ND-Organization.OPP-052-Organization - OPP-052-Organization
#description: “OPP-052-Organization ND-RootExtension.ND-Organizations.ND-Organization.OPP-052-Organization - OPP-052-Organization” in SF corresponds to “OPP-052 nan” in eForms. The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efbc:AwardingCPBIndicator. The expected ontology instances are epo: epo:AcquiringCentralPurchasingBody / org:Organization (from CL2) .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efbc:AwardingCPBIndicator

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AcquiringCentralPurchasingBody .
		?this epo:playedBy ?value }