#title: BT-531-Procedure ND-ProcedureProcurementScope.BT-531-Procedure - BT-531-Procedure
#description: “BT-531-Procedure ND-ProcedureProcurementScope.BT-531-Procedure - BT-531-Procedure” in SF corresponds to “BT-531 Additional Nature” in eForms. The corresponding XML element is /*/cac:ProcurementProject/cac:ProcurementAdditionalType/cbc:ProcurementTypeCode[not(@listName='transport-service')]. The expected ontology instances are epo: epo:ContractTerm / at-voc:contract-nature .
#xpath: /*/cac:ProcurementProject/cac:ProcurementAdditionalType/cbc:ProcurementTypeCode[not(@listName='transport-service')]

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ContractTerm .
		?this epo:hasAdditionalContractNature ?value }