#title: OPT-301-Lot-DocProvider ND-Lot.ND-LotTenderingTerms.OPT-301-Lot-DocProvider - OPT-301-Lot-AddInfo
#description: “OPT-301-Lot-DocProvider ND-Lot.ND-LotTenderingTerms.OPT-301-Lot-DocProvider - OPT-301-Lot-AddInfo” in SF corresponds to “OPT-301 nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AdditionalInformationParty/PartyIdentification/ID. The expected ontology instances are epo: epo:AgentInRole (from CL1) / org:Organization (from CL2) / epo:Identifier / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AdditionalInformationParty/PartyIdentification/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:playedBy / epo:hasID / epo:hasIdentifierValue ?value . }