#title: BT-134-Lot ND-Lot.ND-LotTenderingProcess.ND-PublicOpening.BT-134-Lot - BT-134-Lot
#description: “BT-134-Lot ND-Lot.ND-LotTenderingProcess.ND-PublicOpening.BT-134-Lot - BT-134-Lot” in SF corresponds to “BT-134 Public Opening Description” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/OpenTenderEvent/Description. The expected ontology instances are epo: epo:Lot / epo:OpeningTerm / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/OpenTenderEvent/Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasOpeningDescription ?value }