#title: OPT-301-Lot-AddInfo ND-Lot.ND-LotTenderingTerms.OPT-301-Lot-AddInfo - BT-124-Lot
#description: “OPT-301-Lot-AddInfo ND-Lot.ND-LotTenderingTerms.OPT-301-Lot-AddInfo - BT-124-Lot” in SF corresponds to “BT-124 Tool Atypical URL” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/AccessToolsURI. The expected ontology instances are epo: epo:AccessTerm / xsd:anyURI .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/AccessToolsURI

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AccessTerm .
		?this epo:hasPublicAccessURL ?value . }