#title: BT-98-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-TenderValidity - Tender Validity Deadline
#description: “BT-98-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-TenderValidity - Tender Validity Deadline” in SF corresponds to “BT-98 Tender Validity Deadline” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/TenderValidityPeriod/DurationMeasure. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / epo:Period .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/TenderValidityPeriod/DurationMeasure

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm  / epo:hasValidityPeriod ?value . }