#title: BT-88-Procedure ND-ProcedureTenderingProcess.BT-88-Procedure - BT-88-Procedure
#description: “BT-88-Procedure ND-ProcedureTenderingProcess.BT-88-Procedure - BT-88-Procedure” in SF corresponds to “BT-88 Procedure Features” in eForms. The corresponding XML element is /ContractNotice/TenderingProcess/Description. The expected ontology instances are epo: epo:Procedure / rdf:langString .
#xpath: /ContractNotice/TenderingProcess/Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasMainFeature ?value }