#title: BT-512-Organization-TouchPoint ND-RootExtension.ND-Organizations.ND-Organization.ND-Touchpoint.ND-TouchpointAddress.BT-512-Organization-TouchPoint - BT-512-Organization-TouchPoint
#description: “BT-512-Organization-TouchPoint ND-RootExtension.ND-Organizations.ND-Organization.ND-Touchpoint.ND-TouchpointAddress.BT-512-Organization-TouchPoint - BT-512-Organization-TouchPoint” in SF corresponds to “BT-512 Organisation Post Code” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/TouchPoint/PostalAddress/PostalZone. The expected ontology instances are epo: epo:AgentInRole (from CL1)  / org:Organization (from CL2) / locn:Address / rdf:langString .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/TouchPoint/PostalAddress/PostalZone

PREFIX cv: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX locn: <http://www.w3.org/ns/locn#>

ASK WHERE { 
		?this epo:playedBy / cv:registeredAddress / locn:postCode ?value . }