#title: BT-24-LotsGroup ND-LotsGroup.ND-LotsGroupProcurementScope.BT-24-LotsGroup - BT-21-LotsGroup
#description: “BT-24-LotsGroup ND-LotsGroup.ND-LotsGroupProcurementScope.BT-24-LotsGroup - BT-21-LotsGroup” in SF corresponds to “BT-21 Title” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/Name. The expected ontology instances are epo: epo:LotGroup / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/Name

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LotGroup .
		?this cccev:title ?value . }