#title: BT-33-Procedure ND-ProcedureTerms.ND-LotDistribution.BT-33-Procedure - BT-33-Procedure
#description: “BT-33-Procedure ND-ProcedureTerms.ND-LotDistribution.BT-33-Procedure - BT-33-Procedure” in SF corresponds to “BT-33 Lots Max Awarded” in eForms. The corresponding XML element is /ContractNotice/TenderingTerms/LotDistribution/MaximumLotsAwardedNumeric. The expected ontology instances are epo: epo:Procedure / epo:ProcedureTerm / rdf:langString .
#xpath: /ContractNotice/TenderingTerms/LotDistribution/MaximumLotsAwardedNumeric

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:isSubjectToProcedureSpecificTerm / epo:hasMaximumNumberOfLotsToBeAwarded ?value }