#title: BT-5131-Lot ND-Lot.ND-LotProcurementScope.ND-LotPlacePerformance.ND-LotPerformanceAddress.BT-5131-Lot - BT-5131-Lot
#description: “BT-5131-Lot ND-Lot.ND-LotProcurementScope.ND-LotPlacePerformance.ND-LotPerformanceAddress.BT-5131-Lot - BT-5131-Lot” in SF corresponds to “BT-5131 Place Performance City” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:RealizedLocation/cac:Address/cbc:CityName. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / dct:Location / locn:Address / rdf:langString .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:RealizedLocation/cac:Address/cbc:CityName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:definesSpecificPlaceOfPerformance / locn:address / locn:addressArea ?value . }