#title: ND-CompanyAddress ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress - ND-CompanyAddress
#description: “ND-CompanyAddress ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress - ND-CompanyAddress” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company/cac:PostalAddress. The expected ontology instances are epo: org:Organization (from CL2) / locn:Address .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company/cac:PostalAddress

PREFIX cv: <http://data.europa.eu/m8g/>

ASK WHERE { 
		?this cv:registeredAddress ?value . }