#title: BT-505-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.BT-505-Organization-Company - BT-505-Organization-Company
#description: “BT-505-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.BT-505-Organization-Company - BT-505-Organization-Company” in SF corresponds to “BT-505 Organisation Internet Address” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/WebsiteURI. The expected ontology instances are epo: org:Organization (from CL2) / cpov:ContactPoint / xsd:anyURI .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/WebsiteURI

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:hasPrimaryContactPoint / epo:hasInternetAddress ?value . }