#title: GR-TouchPoint-Address content.GR-Organisations-Section.GR-Organisations-Subsection.GR-Organisations.GR-Touch-Point - TouchPoint Address
#description: “GR-TouchPoint-Address content.GR-Organisations-Section.GR-Organisations-Subsection.GR-Organisations.GR-Touch-Point - TouchPoint Address” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/TouchPoint/PostalAddress. The expected ontology instances are epo: epo:AgentInRole (from CL1) / org:Organization (from CL2) .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/TouchPoint/PostalAddress

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:playedBy / epo:hasEndpoint ?value . }