#title: ND-LotValueEstimate ND-Lot.ND-LotProcurementScope.ND-LotValueEstimate - BT-111-Lot
#description: “ND-LotValueEstimate ND-Lot.ND-LotProcurementScope.ND-LotValueEstimate - BT-111-Lot” in SF corresponds to “BT-111 Framework Buyer Categories” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/FrameworkAgreement/SubsequentProcessTenderRequirement/Description. The expected ontology instances are epo: epo:Lot / epo:FrameworkAgreementTerm / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/FrameworkAgreement/SubsequentProcessTenderRequirement/Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToProcedureSpecificTerm / epo:hasBuyerCategoryDescription ?value . }