#title: BT-733-LotsGroup ND-LotsGroup.ND-LotsGroupAwardingTerms.ND-LotsGroupAwardCriteria.BT-733-LotsGroup - BT-733-LotsGroup
#description: “BT-733-LotsGroup ND-LotsGroup.ND-LotsGroupAwardingTerms.ND-LotsGroupAwardCriteria.BT-733-LotsGroup - BT-733-LotsGroup” in SF corresponds to “BT-733 Award Criteria Order Justification” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/Description. The expected ontology instances are epo: epo:Lot / epo:AwardEvaluationTerm / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasAwardCriteriaOrderJustification ?value }