#title: BT-633-Organization ND-RootExtension.ND-Organizations.ND-Organization.BT-633-Organization - OPT-200-Organization-Company
#description: “BT-633-Organization ND-RootExtension.ND-Organizations.ND-Organization.BT-633-Organization - OPT-200-Organization-Company” in SF corresponds to “OPT-200 nan” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/PartyIdentification/ID. The expected ontology instances are epo: epo:AgentInRole (from CL1) / org:Organization (from CL2) / epo:Identifier / rdf:langString .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/PartyIdentification/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:playedBy / epo:hasID / epo:hasIdentifierValue ?value . }