#title: BT-57-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-ContractExtension.GR-OptionsDescription - Renewal Description
#description: “BT-57-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-ContractExtension.GR-OptionsDescription - Renewal Description” in SF corresponds to “BT-57 Renewal Description” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/ContractExtension/Renewal/Period/Description. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/ContractExtension/Renewal/Period/Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm /  epo:hasDescription ?value }