#title: ND-LotsGroupValueEstimate ND-LotsGroup.ND-LotsGroupProcurementScope.ND-LotsGroupValueEstimate - BT-157-LotsGroup
#description: “ND-LotsGroupValueEstimate ND-LotsGroup.ND-LotsGroupProcurementScope.ND-LotsGroupValueEstimate - BT-157-LotsGroup” in SF corresponds to “BT-157 Group Framework Maximum Value” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/FrameworkAgreement/EstimatedMaximumValueAmount. The expected ontology instances are epo: epo:LotGroup / xsd:MonetaryValue / xsd:decimal .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/FrameworkAgreement/EstimatedMaximumValueAmount

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LotGroup .
		?this epo:hasEstimatedValue / epo:hasAmountValue ?value . }