#title: ND-ServiceProviderParty ND-ContractingParty.ND-ServiceProvider.ND-ServiceProviderParty - ND-ServiceProviderParty
#description: “ND-ServiceProviderParty ND-ContractingParty.ND-ServiceProvider.ND-ServiceProviderParty - ND-ServiceProviderParty” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /*/cac:ContractingParty/cac:Party/cac:ServiceProviderParty. The expected ontology instances are epo: epo:Notice / epo:AgentInRole (from CL1) .
#xpath: /*/cac:ContractingParty/cac:Party/cac:ServiceProviderParty

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX epo-not: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Notice .
		?this epo-not:announcesRole ?value }