#title: BT-801-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Nda - Non Disclosure Agreement
#description: “BT-801-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Nda - Non Disclosure Agreement” in SF corresponds to “BT-801 Non-Disclosure Agreement” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/ContractExecutionRequirement/ExecutionRequirementCode/@listName. The expected ontology instances are epo: epo:Business / xsd:boolean .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/ContractExecutionRequirement/ExecutionRequirementCode/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Business .
		?this epo:isListedCompany ?value . }