#title: BT-67(a)-Procedure ND-ProcedureTerms.ND-TendererQualificationRequest.ND-ExclusionGrounds.BT-67(a)-Procedure - ND-ExclusionGrounds
#description: “BT-67(a)-Procedure ND-ProcedureTerms.ND-TendererQualificationRequest.ND-ExclusionGrounds.BT-67(a)-Procedure - ND-ExclusionGrounds” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/TenderingTerms/TendererQualificationRequest/SpecificTendererRequirement. The expected ontology instances are epo: epo:ExclusionGround .
#xpath: /ContractNotice/TenderingTerms/TendererQualificationRequest/SpecificTendererRequirement

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ExclusionGround .
		?this a epo:ExclusionGround }