#title: BT-22-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-Description - Internal Identifier
#description: “BT-22-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-Description - Internal Identifier” in SF corresponds to “BT-22 Internal Identifier” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/ID. The expected ontology instances are epo: epo:Lot / epo:Purpose / epo:Identifier / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:hasPurpose / epo:hasID / epo:hasIdentifierValue ?value . }