#title: ND-ServiceProvider ND-ContractingParty.ND-ServiceProvider - ND-ServiceProvider
#description: “ND-ServiceProvider ND-ContractingParty.ND-ServiceProvider - ND-ServiceProvider” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /*/cac:ContractingParty/cac:Party. The expected ontology instances are epo: org:Organization .
#xpath: /*/cac:ContractingParty/cac:Party

PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type org:Organization .
		?this a org:Organization. }