#title: BT-94-Lot ND-Lot.ND-LotTenderingTerms.BT-94-Lot - BT-63-Lot
#description: “BT-94-Lot ND-Lot.ND-LotTenderingTerms.BT-94-Lot - BT-63-Lot” in SF corresponds to “BT-63 Variants” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/VariantConstraintCode. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / at-voc:permission .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/VariantConstraintCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm  / epo:hasVariantPermission ?value . }