#title: metadata - Notice Subtype
#description: “metadata - Notice Subtype” in SF corresponds to “OPP-070 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014//*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeSubType/cbc:SubTypeCode. The expected ontology instances are epo: Metadata not Mapped .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014//*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeSubType/cbc:SubTypeCode



ASK WHERE { 
		Metadata not Mapped }