#title: BT-732-Lot ND-Lot.ND-LotTenderingTerms.ND-SecurityClearanceTerms.BT-732-Lot - BT-732-Lot
#description: “BT-732-Lot ND-Lot.ND-LotTenderingTerms.ND-SecurityClearanceTerms.BT-732-Lot - BT-732-Lot” in SF corresponds to “BT-732 Security Clearance Description” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/SecurityClearanceTerm/Description. The expected ontology instances are epo: epo:Lot / epo:SecurityClearanceTerm / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/SecurityClearanceTerm/Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm  / epo:hasDescription ?value . }