#title: BT-14-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-ProcurementDocuments - Documents Restricted
#description: “BT-14-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-ProcurementDocuments - Documents Restricted” in SF corresponds to “BT-14 Documents Restricted” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/DocumentType. The expected ontology instances are epo: epo:AccessTerm / xsd:boolean .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/DocumentType

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AccessTerm .
		?this epo:isProcurementDocumentRestricted ?value . }