#title: BT-21-Procedure ND-ProcedureProcurementScope.BT-21-Procedure - BT-22-Procedure
#description: “BT-21-Procedure ND-ProcedureProcurementScope.BT-21-Procedure - BT-22-Procedure” in SF corresponds to “BT-22 Internal Identifier” in eForms. The corresponding XML element is /ContractNotice/ProcurementProject/ID. The expected ontology instances are epo: epo:Procedure / epo:Identifier / rdf:langString .
#xpath: /ContractNotice/ProcurementProject/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasID / epo:hasIdentifierValue ?value . }