#title: BT-5421-LotsGroup ND-LotsGroup.ND-LotsGroupAwardingTerms.ND-LotsGroupAwardCriteria.ND-LotsGroupAwardCriterion.ND-LotsGroupAwardCriterionParameters.ND-LotsGroupAwardCriterionParameter.BT-5421-LotsGroup - BT-5421-LotsGroup
#description: “BT-5421-LotsGroup ND-LotsGroup.ND-LotsGroupAwardingTerms.ND-LotsGroupAwardCriteria.ND-LotsGroupAwardCriterion.ND-LotsGroupAwardCriterionParameters.ND-LotsGroupAwardCriterionParameter.BT-5421-LotsGroup - BT-5421-LotsGroup” in SF corresponds to “BT-5421 Award Criterion Number Weight” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/AwardCriterionParameter/ParameterCode/@listName. The expected ontology instances are epo: epo:AwardCriterion / xsd:decimal .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/AwardCriterionParameter/ParameterCode/@listName

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AwardCriterion .
		?this cccev:weight ?value }