#title: BT-506-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyContact.BT-506-Organization-Company - BT-506-Organization-Company
#description: “BT-506-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyContact.BT-506-Organization-Company - BT-506-Organization-Company” in SF corresponds to “BT-506 Organisation Contact Email Address” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/Contact/ElectronicMail. The expected ontology instances are epo: cpov:ContactPoint / xsd:anyURI .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/Contact/ElectronicMail

PREFIX cpov: <http://data.europa.eu/m8g/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type cpov:ContactPoint .
		?this cpov:email ?value . }