#title: BT-18-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-SubmissionMethod - Submission URL
#description: “BT-18-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-SubmissionMethod - Submission URL” in SF corresponds to “BT-18 Submission URL” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/TenderRecipientParty/EndpointID. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / xsd:anyURI .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/TenderRecipientParty/EndpointID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasSubmissionURL ?value . }