#title: metadata - Notice Dispatch Date
#description: “metadata - Notice Dispatch Date” in SF corresponds to “BT-05 Notice Dispatch Date” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:IssueDate. The expected ontology instances are epo: Metadata not Mapped .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:IssueDate



ASK WHERE { 
		Metadata not Mapped }