#title: BT-1351-Procedure content.GR-Procedure.GR-Procedure-Procedure-subsection.GR-Procedure-Procedure - Procedure Accelerated Justification
#description: “BT-1351-Procedure content.GR-Procedure.GR-Procedure-Procedure-subsection.GR-Procedure-Procedure - Procedure Accelerated Justification” in SF corresponds to “BT-1351 Procedure Accelerated Justification” in eForms. The corresponding XML element is /ContractNotice/TenderingProcess/ProcessJustification/ProcessReason. The expected ontology instances are epo: epo:Procedure / rdf:langString .
#xpath: /ContractNotice/TenderingProcess/ProcessJustification/ProcessReason

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasAcceleratedProcedureJustification ?value . }