#title: OPT-301-Lot-EnvironLegis content.GR-Lot.GR-Lot-Purpose.GR-Lot-EnvironLegis - Environmental Legislation Organization Technical Identifier Reference
#description: “OPT-301-Lot-EnvironLegis content.GR-Lot.GR-Lot-Purpose.GR-Lot-EnvironLegis - Environmental Legislation Organization Technical Identifier Reference” in SF corresponds to “OPT-301 nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/EnvironmentalLegislationDocumentReference/IssuerParty/PartyIdentification/ID. The expected ontology instances are epo: epo:Document / epo:Identifier / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/EnvironmentalLegislationDocumentReference/IssuerParty/PartyIdentification/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Document .
		?this epo:hasID / epo:hasIdentifierValue ?value }