#title: BT-71-Lot ND-Lot.ND-LotTenderingTerms.ND-LotReservedParticipation.ND-LotReservedProcurement.BT-71-Lot - BT-71-Lot
#description: “BT-71-Lot ND-Lot.ND-LotTenderingTerms.ND-LotReservedParticipation.ND-LotReservedProcurement.BT-71-Lot - BT-71-Lot” in SF corresponds to “BT-71 Reserved Participation” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/TendererQualificationRequest/SpecificTendererRequirement/TendererRequirementTypeCode/@listName. The expected ontology instances are epo: epo:Lot / at-voc:reserved-procurement .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/TendererQualificationRequest/SpecificTendererRequirement/TendererRequirementTypeCode/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:hasReservedProcurement ?value . }