#title: BT-514-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress.BT-514-Organization-Company - BT-514-Organization-Company
#description: “BT-514-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress.BT-514-Organization-Company - BT-514-Organization-Company” in SF corresponds to “BT-514 Organisation Country Code” in eForms. The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company/cac:PostalAddress/cac:Country/cbc:IdentificationCode. The expected ontology instances are epo: org:Organization (from CL2) / locn:Address / at-voc:country (from country.json) .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company/cac:PostalAddress/cac:Country/cbc:IdentificationCode

PREFIX cv: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this cv:registeredAddress / epo:hasCountryCode ?value . }