#title: BT-21-Lot ND-Lot.ND-LotProcurementScope.BT-21-Lot - BT-21-Lot
#description: “BT-21-Lot ND-Lot.ND-LotProcurementScope.BT-21-Lot - BT-21-Lot” in SF corresponds to “BT-21 Title” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cbc:Name. The expected ontology instances are epo: epo:Lot /  rdf:langString .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cbc:Name

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this cccev:title ?value . }