#title: BT-23-Procedure content.GR-Procedure.GR-Procedure-Purpose.GR-Procedure-Description - Main Nature
#description: “BT-23-Procedure content.GR-Procedure.GR-Procedure-Purpose.GR-Procedure-Description - Main Nature” in SF corresponds to “BT-23 Main Nature” in eForms. The corresponding XML element is /ContractNotice/ProcurementProject/ProcurementTypeCode. The expected ontology instances are epo: epo:Procedure / rdf:langString .
#xpath: /ContractNotice/ProcurementProject/ProcurementTypeCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasMainFeature ?value . }