#title: BT-540-LotsGroup ND-LotsGroup.ND-LotsGroupAwardingTerms.ND-LotsGroupAwardCriteria.ND-LotsGroupAwardCriterion.BT-540-LotsGroup - BT-540-LotsGroup
#description: “BT-540-LotsGroup ND-LotsGroup.ND-LotsGroupAwardingTerms.ND-LotsGroupAwardCriteria.ND-LotsGroupAwardCriterion.BT-540-LotsGroup - BT-540-LotsGroup” in SF corresponds to “BT-540 Award Criterion Description” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/Description. The expected ontology instances are epo: epo:AwardCriterion / rdf:langStrin .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/Description

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AwardCriterion .
		?this cccev:description ?value }