#title: metadata - Procedure Identifier
#description: “metadata - Procedure Identifier” in SF corresponds to “BT-04 Procedure Identifier” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:ContractFolderID. The expected ontology instances are epo: Metadata not Mapped .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:ContractFolderID



ASK WHERE { 
		Metadata not Mapped }