#title: OPT-301-Lot-ReviewInfo ND-Lot.ND-LotTenderingTerms.ND-LotReviewTerms.OPT-301-Lot-ReviewInfo - OPT-301-Lot-ReviewInfo
#description: “OPT-301-Lot-ReviewInfo ND-Lot.ND-LotTenderingTerms.ND-LotReviewTerms.OPT-301-Lot-ReviewInfo - OPT-301-Lot-ReviewInfo” in SF corresponds to “OPT-301 nan” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:AppealTerms/cac:AppealInformationParty/cac:PartyIdentification/cbc:ID. The expected ontology instances are epo: epo:Notice / epo:ReviewProcedureInformationProvider .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:AppealTerms/cac:AppealInformationParty/cac:PartyIdentification/cbc:ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX epo-not: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Notice .
		?this epo-not:announcesRole ?value }