#title: BT-271-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-FrameworkAgreement - Framework Maximum Value
#description: “BT-271-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-FrameworkAgreement - Framework Maximum Value” in SF corresponds to “BT-271 Framework Maximum Value” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/RequestedTenderTotal/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/FrameworkMaximumAmount. The expected ontology instances are epo: epo:Lot / epo:FrameworkAgreementTerm / epo:MonetaryValue / xsd:decimal .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/RequestedTenderTotal/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/FrameworkMaximumAmount

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToProcedureSpecificTerm / epo:hasFrameworkAgreementMaximumValue / epo:hasAmountValue ?value . }