#title: BT-508-Procedure-Buyer ND-ContractingParty.BT-508-Procedure-Buyer - BT-508-Procedure-Buyer
#description: “BT-508-Procedure-Buyer ND-ContractingParty.BT-508-Procedure-Buyer - BT-508-Procedure-Buyer” in SF corresponds to “BT-508 Buyer Profile URL” in eForms. The corresponding XML element is /*/cac:ContractingParty/cbc:BuyerProfileURI. The expected ontology instances are epo: epo:AgentInRole (from CL1) / xsd:anyURI .
#xpath: /*/cac:ContractingParty/cbc:BuyerProfileURI

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Buyer .
		?this epo:hasBuyerProfile ?value . }