#title: BT-707-Lot ND-Lot.ND-LotTenderingTerms.ND-LotRestrictedDocuments.BT-707-Lot - OPT-050-Lot
#description: “BT-707-Lot ND-Lot.ND-LotTenderingTerms.ND-LotRestrictedDocuments.BT-707-Lot - OPT-050-Lot” in SF corresponds to “OPT-050 nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/DocumentStatusCode. The expected ontology instances are epo: epo:LotAwardOutcome /  at-voc:winner-selection-status .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/DocumentStatusCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LotAwardOutcome .
		?this epo:hasAwardStatus ?value }