#title: ND-OptionsDescription ND-Lot.ND-LotProcurementScope.ND-OptionsAndRenewals.ND-OptionsDescription - ND-OptionsDescription
#description: “ND-OptionsDescription ND-Lot.ND-LotProcurementScope.ND-OptionsAndRenewals.ND-OptionsDescription - ND-OptionsDescription” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/ContractExtension/Renewal/Period. The expected ontology instances are epo: epo:ContractTerm .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/ContractExtension/Renewal/Period

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ContractTerm .
		?this a epo:ContractTerm }