#title: BT-24-Procedure ND-ProcedureProcurementScope.BT-24-Procedure - BT-24-Procedure
#description: “BT-24-Procedure ND-ProcedureProcurementScope.BT-24-Procedure - BT-24-Procedure” in SF corresponds to “BT-24 Description” in eForms. The corresponding XML element is /*/cac:ProcurementProject/cbc:Description. The expected ontology instances are epo: epo:Procedure / rdf:langString .
#xpath: /*/cac:ProcurementProject/cbc:Description

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this cccev:description ?value . }