#title: BT-5141-Procedure ND-ProcedureProcurementScope.ND-ProcedurePlacePerformanceAdditionalInformation.ND-ProcedurePlacePerformance.BT-5141-Procedure - BT-5141-Procedure
#description: “BT-5141-Procedure ND-ProcedureProcurementScope.ND-ProcedurePlacePerformanceAdditionalInformation.ND-ProcedurePlacePerformance.BT-5141-Procedure - BT-5141-Procedure” in SF corresponds to “BT-5141 Place Performance Country Code” in eForms. The corresponding XML element is /*/cac:ProcurementProject/cac:RealizedLocation/cac:Address/cac:Country/cbc:IdentificationCode. The expected ontology instances are epo: epo:Procedure / epo:ContractTerm / dct:Location / at-voc:nuts .
#xpath: /*/cac:ProcurementProject/cac:RealizedLocation/cac:Address/cac:Country/cbc:IdentificationCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:foreseesContractSpecificTerm / epo:definesSpecificPlaceOfPerformance / epo:hasCountryCode ?value . }