#title: BT-01(d)-Procedure ND-ProcedureTerms.ND-LocalLegalBasisWithID.BT-01(d)-Procedure - BT-01(d)-Procedure
#description: “BT-01(d)-Procedure ND-ProcedureTerms.ND-LocalLegalBasisWithID.BT-01(d)-Procedure - BT-01(d)-Procedure” in SF corresponds to “BT-01 Procedure Legal Basis” in eForms. The corresponding XML element is /*/cac:TenderingTerms/cac:ProcurementLegislationDocumentReference[not(cbc:ID/text()=('CrossBorderLaw','LocalLegalBasis'))]/cbc:DocumentDescription. The expected ontology instances are epo: epo:Procedure / rdf:langString .
#xpath: /*/cac:TenderingTerms/cac:ProcurementLegislationDocumentReference[not(cbc:ID/text()=('CrossBorderLaw','LocalLegalBasis'))]/cbc:DocumentDescription

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this cccev:description ?value . }