#title: BT-732-Lot ND-Lot.ND-LotTenderingTerms.ND-SecurityClearanceTerms.BT-732-Lot - BT-578-Lot
#description: “BT-732-Lot ND-Lot.ND-LotTenderingTerms.ND-SecurityClearanceTerms.BT-732-Lot - BT-578-Lot” in SF corresponds to “BT-578 Security Clearance” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/SecurityClearanceTerm/Code. The expected ontology instances are epo: epo:Lot / epo:SecurityClearanceTerm .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/SecurityClearanceTerm/Code

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / cccev:title  ?value . }