#title: BT-124-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-SubmissionTool - Tool Atypical URL
#description: “BT-124-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-SubmissionTool - Tool Atypical URL” in SF corresponds to “BT-124 Tool Atypical URL” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/AccessToolsURI. The expected ontology instances are epo: epo:Lot / cv:Channel / xsd:anyURI .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/AccessToolsURI

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:usesChannel  / epo:hasURL ?value . }