#title: BT-01(c)-Procedure content.GR-Procedure.GR-Procedure-Purpose.GR-Procedure-LocalLegalBasisWithID - Procedure Legal Basis (ID)
#description: “BT-01(c)-Procedure content.GR-Procedure.GR-Procedure-Purpose.GR-Procedure-LocalLegalBasisWithID - Procedure Legal Basis (ID)” in SF corresponds to “BT-01 Procedure Legal Basis” in eForms. The corresponding XML element is /ContractNotice/TenderingTerms/ProcurementLegislationDocumentReference/ID. The expected ontology instances are epo: epo:ProcedureTerm / epo:Identifier / rdf:langString .
#xpath: /ContractNotice/TenderingTerms/ProcurementLegislationDocumentReference/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ProcedureTerm .
		?this epo:hasID / epo:hasIdentifierValue ?value . }