#title: BT-500-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.BT-500-Organization-Company - BT-500-Organization-Company
#description: “BT-500-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.BT-500-Organization-Company - BT-500-Organization-Company” in SF corresponds to “BT-500 Organisation Name” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/PartyName/Name. The expected ontology instances are epo: org:Organization (from CL2) / rdf:langString .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/Company/PartyName/Name

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:hasLegalName ?value . }