#title: BT-137-Lot ND-Lot.BT-137-Lot - BT-137-Lot
#description: “BT-137-Lot ND-Lot.BT-137-Lot - BT-137-Lot” in SF corresponds to “BT-137 Purpose Lot Identifier” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cbc:ID. The expected ontology instances are epo: epo:Lot / epo:Identifier / xsd:string .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cbc:ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:hasID / epo:hasIdentifierValue ?value . }