#title: BT-1251-Lot ND-Lot.ND-LotTenderingProcess.ND-LotPreviousPlanning.BT-1251-Lot - BT-1251-Lot
#description: “BT-1251-Lot ND-Lot.ND-LotTenderingProcess.ND-LotPreviousPlanning.BT-1251-Lot - BT-1251-Lot” in SF corresponds to “BT-1251 Previous Planning Part Identifier” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingProcess/cac:NoticeDocumentReference/cbc:ReferencedDocumentInternalAddress. The expected ontology instances are epo: epo-not:PlanningNotice / epo:PlannedProcurementPart / epo:Identifier / xsd:string .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingProcess/cac:NoticeDocumentReference/cbc:ReferencedDocumentInternalAddress

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX epo-not: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo-not:PlanningNotice .
		?this epo-not:announcesPlannedProcurementPart / epo:hasID / epo:hasIdentifierValue ?value }