#title: BT-771-Lot ND-Lot.ND-LotTenderingTerms.ND-LateTendererInformation.BT-771-Lot - BT-771-Lot
#description: “BT-771-Lot ND-Lot.ND-LotTenderingTerms.ND-LateTendererInformation.BT-771-Lot - BT-771-Lot” in SF corresponds to “BT-771 Late Tenderer Information” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:TendererQualificationRequest[not(cbc:CompanyLegalFormCode)]/cac:SpecificTendererRequirement[not(cbc:TendererRequirementTypeCode[@listName='reserved-procurement'])]/cbc:TendererRequirementTypeCode[@listName='missing-info-submission']. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / at-voc:missing-info-submission .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:TendererQualificationRequest[not(cbc:CompanyLegalFormCode)]/cac:SpecificTendererRequirement[not(cbc:TendererRequirementTypeCode[@listName='reserved-procurement'])]/cbc:TendererRequirementTypeCode[@listName='missing-info-submission']

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm  / epo:hasLateSubmissionPermission ?value . }