#title: ND-ProcedurePlacePerformanceAdditionalInformation ND-ProcedureProcurementScope.ND-ProcedurePlacePerformanceAdditionalInformation - BT-263-Procedure
#description: “ND-ProcedurePlacePerformanceAdditionalInformation ND-ProcedureProcurementScope.ND-ProcedurePlacePerformanceAdditionalInformation - BT-263-Procedure” in SF corresponds to “BT-263 Additional Classification Codes” in eForms. The corresponding XML element is /ContractNotice/ProcurementProject/AdditionalCommodityClassification/ItemClassificationCode. The expected ontology instances are epo: epo:Procedure / at-voc:cpvsuppl (from cpvsuppl.json) .
#xpath: /ContractNotice/ProcurementProject/AdditionalCommodityClassification/ItemClassificationCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasAdditionalClassification ?value . }