#title: GR-Lot-SelectionCriteria content.GR-Lot.GR-Lot-TenderingTerms - Selection Criteria including the ones for 2nd stage (Type, Name, Description, Use, Parameters)
#description: “GR-Lot-SelectionCriteria content.GR-Lot.GR-Lot-TenderingTerms - Selection Criteria including the ones for 2nd stage (Type, Name, Description, Use, Parameters)” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/SelectionCriteria. The expected ontology instances are epo: epo:SelectionCriterion .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/SelectionCriteria

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:SelectionCriterion .
		?this a epo:SelectionCriterion }