#title: metadata - Notice Version
#description: “metadata - Notice Version” in SF corresponds to “BT-757 Notice Version” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:VersionID. The expected ontology instances are epo: Metadata not Mapped .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:VersionID



ASK WHERE { 
		Metadata not Mapped }