#title: OPP-051-Organization ND-RootExtension.ND-Organizations.ND-Organization.OPP-051-Organization - OPP-050-Organization
#description: “OPP-051-Organization ND-RootExtension.ND-Organizations.ND-Organization.OPP-051-Organization - OPP-050-Organization” in SF corresponds to “OPP-050 nan” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/GroupLeadIndicator. The expected ontology instances are epo: epo:LeadBuyer / xsd:boolean .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/GroupLeadIndicator

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LeadBuyer .
		?this epo:isContractingEntity ?value }