#title: BT-701-notice BT-701-notice - BT-701-notice
#description: “BT-701-notice BT-701-notice - BT-701-notice” in SF corresponds to “BT-701 Notice Identifier” in eForms. The corresponding XML element is /*/cbc:ID[@schemeName='notice-id']. The expected ontology instances are epo: epo:Notice / epo:Indentifier / rdf:langString .
#xpath: /*/cbc:ID[@schemeName='notice-id']

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Notice .
		?this epo:hasID / epo:hasIdentifierValue ?value }