#title: BT-263-Procedure content.GR-Procedure.GR-Procedure-Purpose.GR-Procedure-Scope.GR-Procedure-Scope-AdditionalClassification - Additional Classification Code
#description: “BT-263-Procedure content.GR-Procedure.GR-Procedure-Purpose.GR-Procedure-Scope.GR-Procedure-Scope-AdditionalClassification - Additional Classification Code” in SF corresponds to “BT-263 Additional Classification Codes” in eForms. The corresponding XML element is /ContractNotice/ProcurementProject/AdditionalCommodityClassification/ItemClassificationCode. The expected ontology instances are epo: epo:Procedure / epo:Purpose / at-voc:cpvsuppl (from cpvsuppl.json) .
#xpath: /ContractNotice/ProcurementProject/AdditionalCommodityClassification/ItemClassificationCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasPurpose / epo:hasAdditionalClassification ?value . }