#title: BT-09(a)-Procedure content.GR-Procedure.GR-Procedure-TenderingTerms.GR-Procedure-CrossBorderLaw - Cross Border Law
#description: “BT-09(a)-Procedure content.GR-Procedure.GR-Procedure-TenderingTerms.GR-Procedure-CrossBorderLaw - Cross Border Law” in SF corresponds to “BT-09 Cross Border Law” in eForms. The corresponding XML element is /ContractNotice/TenderingTerms/ProcurementLegislationDocumentReference/ID. The expected ontology instances are epo: epo:ProcedureTerm / rdf:langString .
#xpath: /ContractNotice/TenderingTerms/ProcurementLegislationDocumentReference/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ProcedureTerm .
		?this epo:refersToProcedure / epo:hasCrossBorderLaw ?value . }