#title: BT-764-Lot ND-Lot.ND-LotTenderingTerms.BT-764-Lot - BT-802-Lot
#description: “BT-764-Lot ND-Lot.ND-LotTenderingTerms.BT-764-Lot - BT-802-Lot” in SF corresponds to “BT-802 Non-Disclosure Agreement Description” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/ContractExecutionRequirement/Description. The expected ontology instances are epo: epo:Business / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/ContractExecutionRequirement/Description

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Business .
		?this cccev:description ?value . }