#title: BT-21-LotsGroup content.GR-LotsGroup.GR-LotsGroup-Purpose.GR-LotsGroup-Description - Title
#description: “BT-21-LotsGroup content.GR-LotsGroup.GR-LotsGroup-Purpose.GR-LotsGroup-Description - Title” in SF corresponds to “BT-21 Title” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/Name. The expected ontology instances are epo: epo:LotGroup / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/Name

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LotGroup .
		?this epo:hasTitle ?value . }