#title: BT-51-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-Candidates - Maximum Candidates Number
#description: “BT-51-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-Candidates - Maximum Candidates Number” in SF corresponds to “BT-51 Maximum Candidates Number” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/EconomicOperatorShortList/MaximumQuantity. The expected ontology instances are epo: epo:Lot / epo:MultipleStageProcedureTerm / xsd:integer .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/EconomicOperatorShortList/MaximumQuantity

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:specifiesSelectionCriterion / epo:hasMaximumNumberOfCandidates ?value }