#title: OPP-050-Organization ND-RootExtension.ND-Organizations.ND-Organization.OPP-050-Organization - OPP-050-Organization
#description: “OPP-050-Organization ND-RootExtension.ND-Organizations.ND-Organization.OPP-050-Organization - OPP-050-Organization” in SF corresponds to “OPP-050 nan” in eForms. The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efbc:GroupLeadIndicator. The expected ontology instances are epo: epo:Notice / epo:LeadBuyer .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efbc:GroupLeadIndicator

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX epo-not: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Notice .
		?this epo-not:announcesRole ?value }