#title: BT-775-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-ProcurementType - Social Procurement
#description: “BT-775-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-ProcurementType - Social Procurement” in SF corresponds to “BT-775 Social Procurement” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/ProcurementAdditionalType/ProcurementTypeCode/@listName. The expected ontology instances are epo: epo:Lot / epo:SocialProcurement / at-voc:social-objective .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/ProcurementAdditionalType/ProcurementTypeCode/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:fulfillsStrategicProcurement / epo:fulfillsRequirement ?value }