#title: BT-15-Lot ND-Lot.ND-LotTenderingTerms.ND-LotDocumentsReference.BT-15-Lot - BT-15-Lot
#description: “BT-15-Lot ND-Lot.ND-LotTenderingTerms.ND-LotDocumentsReference.BT-15-Lot - BT-15-Lot” in SF corresponds to “BT-15 Documents URL” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/Attachment/ExternalReference/URI. The expected ontology instances are epo: epo:AccessTerm / xsd:anyURI .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/Attachment/ExternalReference/URI

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AccessTerm .
		?this epo:hasPublicAccessURL ?value }