#title: BT-754-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-ProcurementType.GR-Lot-ProcurementType-Accessibility - Accessibility
#description: “BT-754-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-ProcurementType.GR-Lot-ProcurementType-Accessibility - Accessibility” in SF corresponds to “BT-754 Accessibility” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/ProcurementAdditionalType/ProcurementTypeCode@listName. The expected ontology instances are epo: epo:Lot / epo:StrategicProcurement / at-voc:accessibility .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/ProcurementAdditionalType/ProcurementTypeCode@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:fulfillsStrategicProcurement / epo:includesAccessibilityCriterion ?value }