#title: BT-79-Lot ND-Lot.ND-LotTenderingTerms.BT-79-Lot - BT-79-Lot
#description: “BT-79-Lot ND-Lot.ND-LotTenderingTerms.BT-79-Lot - BT-79-Lot” in SF corresponds to “BT-79 Performing Staff Qualification” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cbc:RequiredCurriculaCode. The expected ontology instances are epo: epo:Lot / at-voc:requirement-stage .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cbc:RequiredCurriculaCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:hasPerformingStaffQualificationInformation ?value }