#title: GR-Touch-Point content.GR-Organisations-Section.GR-Organisations-Subsection.GR-Organisations - Contact details associated to a given role
#description: “GR-Touch-Point content.GR-Organisations-Section.GR-Organisations-Subsection.GR-Organisations - Contact details associated to a given role” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/TouchPoint. The expected ontology instances are epo: epo:AgentInRole (from CL1) / org:Organization (from CL2) / cpov:ContactPoint .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/TouchPoint

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:playedBy / epo:hasPrimaryContactPoint ?value . }