#title: BT-01(d)-Procedure content.GR-Procedure.GR-Procedure-Purpose.GR-Procedure-LocalLegalBasisWithID - Procedure Legal Basis (Description)
#description: “BT-01(d)-Procedure content.GR-Procedure.GR-Procedure-Purpose.GR-Procedure-LocalLegalBasisWithID - Procedure Legal Basis (Description)” in SF corresponds to “BT-01 Procedure Legal Basis” in eForms. The corresponding XML element is /ContractNotice/TenderingTerms/ProcurementLegislationDocumentReference/DocumentDescription. The expected ontology instances are epo: epo:ProcedureTerm / rdf:langString .
#xpath: /ContractNotice/TenderingTerms/ProcurementLegislationDocumentReference/DocumentDescription

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ProcedureTerm .
		?this epo:hasDescription ?value . }