#title: BT-26(m)-Procedure ND-ProcedureProcurementScope.ND-ProcedureMainClassification.ND-ProcedureMainClassificationCode.BT-26(m)-Procedure - ND-ProcedureMainClassificationCode
#description: “BT-26(m)-Procedure ND-ProcedureProcurementScope.ND-ProcedureMainClassification.ND-ProcedureMainClassificationCode.BT-26(m)-Procedure - ND-ProcedureMainClassificationCode” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProject/MainCommodityClassification/ItemClassificationCode. The expected ontology instances are epo: epo:Procedure / at-voc:cpv (from cpv.json) .
#xpath: /ContractNotice/ProcurementProject/MainCommodityClassification/ItemClassificationCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasMainClassification ?value . }