#title: BT-5422-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-AwardCriteria.GR-Lot-AwardCriteria-Criterion.GR-Lot-AwardCriteria-Criterion-Parameters.GR-Lot-AwardCriteria-Criterion-Parameter - Award Criterion Number Fixed
#description: “BT-5422-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-AwardCriteria.GR-Lot-AwardCriteria-Criterion.GR-Lot-AwardCriteria-Criterion-Parameters.GR-Lot-AwardCriteria-Criterion-Parameter - Award Criterion Number Fixed” in SF corresponds to “BT-5422 Award Criterion Number Fixed” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/AwardCriterionParameter/ParameterCode/@listName. The expected ontology instances are epo: epo:Lot / epo:AwardCriterion / at-voc:number-fixed .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/AwardCriterionParameter/ParameterCode/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasFixedValueType ?value }