#title: BT-98-Lot ND-Lot.ND-LotTenderingTerms.BT-98-Lot - BT-13(t)-Lot
#description: “BT-98-Lot ND-Lot.ND-LotTenderingTerms.BT-98-Lot - BT-13(t)-Lot” in SF corresponds to “BT-13 Additional Information Deadline” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/AdditionalInformationRequestPeriod/EndTime. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / xsd:dateTime .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/AdditionalInformationRequestPeriod/EndTime

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm  / epo:hasAdditionalInformationDeadline ?value . }