#title: BT-739-Organization-TouchPoint content.GR-Organisations-Section.GR-Organisations-Subsection.GR-Organisations.GR-Touch-Point.GR-TouchPoint-Contact - Contact Fax
#description: “BT-739-Organization-TouchPoint content.GR-Organisations-Section.GR-Organisations-Subsection.GR-Organisations.GR-Touch-Point.GR-TouchPoint-Contact - Contact Fax” in SF corresponds to “BT-739 Organisation Contact Fax” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/TouchPoint/Contact/Telefax. The expected ontology instances are epo: epo:AgentInRole (from CL1) / org:Organization (from CL2) / cpov:ContactPoint / rdf:langString .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/TouchPoint/Contact/Telefax

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:playedBy / epo:hasPrimaryContactPoint / epo:hasFax ?value . }