#title: metadata - Form Type
#description: “metadata - Form Type” in SF corresponds to “BT-03 Form Type” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:NoticeTypeCode/@listName. The expected ontology instances are epo: Metadata not Mapped .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:NoticeTypeCode/@listName



ASK WHERE { 
		Metadata not Mapped }