#title: BT-745-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-SubmissionMethod - Submission Nonelectronic Description
#description: “BT-745-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-SubmissionMethod - Submission Nonelectronic Description” in SF corresponds to “BT-745 Submission Non-electronic Description” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/ProcessJustification/Description. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm /  at-voc:non-publication-justification .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/ProcessJustification/Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasDescription ?value }