#title: BT-737-Lot ND-Lot.ND-LotTenderingTerms.ND-LotProcurementDocument.BT-737-Lot - BT-708-Lot
#description: “BT-737-Lot ND-Lot.ND-LotTenderingTerms.ND-LotProcurementDocument.BT-737-Lot - BT-708-Lot” in SF corresponds to “BT-708 Documents Official Language” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/LanguageID. The expected ontology instances are epo: epo:AccessTerm / at-voc:language .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/LanguageID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AccessTerm .
		?this epo:hasOfficialLanguage ?value }