#title: BT-131(d)-Lot ND-Lot.ND-LotTenderingProcess.ND-SubmissionDeadline.BT-131(d)-Lot - BT-131(d)-Lot
#description: “BT-131(d)-Lot ND-Lot.ND-LotTenderingProcess.ND-SubmissionDeadline.BT-131(d)-Lot - BT-131(d)-Lot” in SF corresponds to “BT-131 Deadline Receipt Tenders” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/TenderSubmissionDeadlinePeriod/EndDate. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / xsd:dateTime .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/TenderSubmissionDeadlinePeriod/EndDate

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm  / epo:hasReceiptDeadline ?value . }