#title: metadata - Notice Publication Number
#description: “metadata - Notice Publication Number” in SF corresponds to “OPP-010 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014//*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Publication/efbc:NoticePublicationID[@schemeName='ojs-notice-id']. The expected ontology instances are epo: Metadata not Mapped .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014//*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Publication/efbc:NoticePublicationID[@schemeName='ojs-notice-id']



ASK WHERE { 
		Metadata not Mapped }