#title: metadata - Customization ID (UBL)
#description: “metadata - Customization ID (UBL)” in SF corresponds to “OPT-002 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:CustomizationID. The expected ontology instances are epo: Metadata not Mapped .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:CustomizationID



ASK WHERE { 
		Metadata not Mapped }