#title: BT-743-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-ContractExecutionRequirements - Electronic Invoicing
#description: “BT-743-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-ContractExecutionRequirements - Electronic Invoicing” in SF corresponds to “BT-743 Electronic Invoicing” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/ContractExecutionRequirement/ExecutionRequirementCode@listName. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / at-voc:applicability .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/ContractExecutionRequirement/ExecutionRequirementCode@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:hasEInvoicing true . }