#title: BT-140-notice content.GR-Change - Change Reason Code
#description: “BT-140-notice content.GR-Change - Change Reason Code” in SF corresponds to “BT-140 Change Reason Code” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Changes/ChangeReason/ReasonCode. The expected ontology instances are epo: epo:ElementChangeDescription / at-voc:change-corrig-justification .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Changes/ChangeReason/ReasonCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ElementChangeDescription .
		?this epo:hasChangeJustification ?value }