#title: BT-513-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress.BT-513-Organization-Company - BT-513-Organization-Company
#description: “BT-513-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress.BT-513-Organization-Company - BT-513-Organization-Company” in SF corresponds to “BT-513 Organisation City” in eForms. The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company/cac:PostalAddress/cbc:CityName. The expected ontology instances are epo: org:Organization (from CL2) /  locn:Address / rdf:langString .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company/cac:PostalAddress/cbc:CityName

PREFIX cv: <http://data.europa.eu/m8g/>
PREFIX locn: <http://www.w3.org/ns/locn#>

ASK WHERE { 
		?this cv:registeredAddress / locn:postName ?value . }