#title: GR-TouchPoint-Contact content.GR-Organisations-Section.GR-Organisations-Subsection.GR-Organisations.GR-Touch-Point - TouchPoint Contact
#description: “GR-TouchPoint-Contact content.GR-Organisations-Section.GR-Organisations-Subsection.GR-Organisations.GR-Touch-Point - TouchPoint Contact” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/TouchPoint/Contact. The expected ontology instances are epo: epo:AgentInRole (from CL1) / org:Organization (from CL2) / cpov:ContactPoint .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/TouchPoint/Contact

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:playedBy / epo:hasPrimaryContactPoint ?value . }