#title: BT-728-Procedure ND-ProcedureProcurementScope.ND-ProcedurePlacePerformanceAdditionalInformation.BT-728-Procedure - BT-728-Procedure
#description: “BT-728-Procedure ND-ProcedureProcurementScope.ND-ProcedurePlacePerformanceAdditionalInformation.BT-728-Procedure - BT-728-Procedure” in SF corresponds to “BT-728 Place Performance Additional Information” in eForms. The corresponding XML element is /*/cac:ProcurementProject/cac:RealizedLocation/cbc:Description. The expected ontology instances are epo: epo:Procedure / epo:ContractTerm / rdf:langString .
#xpath: /*/cac:ProcurementProject/cac:RealizedLocation/cbc:Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:foreseesContractSpecificTerm / epo:hasPlaceOfPerformanceAdditionalInformation ?value . }