#title: BT-24-Procedure ND-ProcedureProcurementScope.BT-24-Procedure - BT-21-Procedure
#description: “BT-24-Procedure ND-ProcedureProcurementScope.BT-24-Procedure - BT-21-Procedure” in SF corresponds to “BT-21 Title” in eForms. The corresponding XML element is /ContractNotice/ProcurementProject/Name. The expected ontology instances are epo: epo:Procedure / rdf:langString .
#xpath: /ContractNotice/ProcurementProject/Name

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this cccev:title ?value . }