#title: BT-5421-Lot ND-Lot.ND-LotTenderingTerms.ND-AwardingTerms.ND-LotAwardCriteria.ND-LotAwardCriterion.ND-LotAwardCriterionParameters.ND-LotAwardCriterionParameter.BT-5421-Lot - BT-5421-Lot
#description: “BT-5421-Lot ND-Lot.ND-LotTenderingTerms.ND-AwardingTerms.ND-LotAwardCriteria.ND-LotAwardCriterion.ND-LotAwardCriterionParameters.ND-LotAwardCriterionParameter.BT-5421-Lot - BT-5421-Lot” in SF corresponds to “BT-5421 Award Criterion Number Weight” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/AwardCriterionParameter/ParameterCode/@listName. The expected ontology instances are epo: epo:Lot / epo:AwardCriterion / at-voc:number-weight .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/SubordinateAwardingCriterion/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/AwardCriterionParameter/ParameterCode/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:specifiesAwardCriterion / epo:hasWeightValueType ?value }