#title: BT-719-notice ND-RootExtension.ND-Changes.ND-Change.BT-719-notice - BT-719-notice
#description: “BT-719-notice ND-RootExtension.ND-Changes.ND-Change.BT-719-notice - BT-719-notice” in SF corresponds to “BT-719 Change Procurement Documents Date” in eForms. The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Changes/efac:Change/efbc:ProcurementDocumentsChangeDate. The expected ontology instances are epo: epo:ElementChangeDescription / xsd:date .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Changes/efac:Change/efbc:ProcurementDocumentsChangeDate

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ElementChangeDescription .
		?this epo:hasProcurementDocumentChangeDate ?value }