#title: BT-23-Procedure ND-ProcedureProcurementScope.BT-23-Procedure - BT-23-Procedure
#description: “BT-23-Procedure ND-ProcedureProcurementScope.BT-23-Procedure - BT-23-Procedure” in SF corresponds to “BT-23 Main Nature” in eForms. The corresponding XML element is /*/cac:ProcurementProject/cbc:ProcurementTypeCode. The expected ontology instances are epo: epo:ContractTerm / at-voc:contract-nature .
#xpath: /*/cac:ProcurementProject/cbc:ProcurementTypeCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ContractTerm .
		?this epo:hasContractNatureType ?value . }