#title: BT-1251-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-PreviousPlanning - Previous Planning Part Identifier
#description: “BT-1251-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-PreviousPlanning - Previous Planning Part Identifier” in SF corresponds to “BT-1251 Previous Planning Part Identifier” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/NoticeDocumentReference/ReferencedDocumentInternalAddress. The expected ontology instances are epo: epo:DirectAward / epo:Lot / epo:Identifier / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/NoticeDocumentReference/ReferencedDocumentInternalAddress

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:DirectAward .
		?this epo:refersToPreviousProcedureLot / epo:hasID / epo:hasIdentifierValue ?value }