#title: ND-LotPlacePerformance ND-Lot.ND-LotProcurementScope.ND-LotPlacePerformance - ND-LotPlacePerformance
#description: “ND-LotPlacePerformance ND-Lot.ND-LotProcurementScope.ND-LotPlacePerformance - ND-LotPlacePerformance” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:RealizedLocation. The expected ontology instances are epo: epo:ContractTerm .
#xpath: /*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:ProcurementProject/cac:RealizedLocation

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ContractTerm .
		?this a epo:ContractTerm }