#title: OPT-140-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-ProcurementDocuments - Procurement Documents ID
#description: “OPT-140-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-ProcurementDocuments - Procurement Documents ID” in SF corresponds to “OPT-140 nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/ID. The expected ontology instances are epo: epo:AccessTerm / epo:Identifier / rf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AccessTerm .
		?this epo:hasID / epo:hasIdentifierValue ?value }