#title: GR-Procedure-ExclusionGrounds content.GR-Procedure.GR-Procedure-TenderingTerms - Exclusion Grounds (Code & Description)
#description: “GR-Procedure-ExclusionGrounds content.GR-Procedure.GR-Procedure-TenderingTerms - Exclusion Grounds (Code & Description)” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/TenderingTerms/TendererQualificationRequest/SpecificTendererRequirement. The expected ontology instances are epo: epo:ExclusionGround .
#xpath: /ContractNotice/TenderingTerms/TendererQualificationRequest/SpecificTendererRequirement

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ExclusionGround .
		?this a epo:ExclusionGround }