#title: BT-77-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-FinancialTerms - Terms Financial
#description: “BT-77-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-FinancialTerms - Terms Financial” in SF corresponds to “BT-77 Terms Financial” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/PaymentTerms/Note. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / xsd:boolean .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/PaymentTerms/Note

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:hasPaymentArrangement ?value. }