#title: BT-733-Lot ND-Lot.ND-LotTenderingTerms.ND-AwardingTerms.ND-LotAwardCriteria.BT-733-Lot - BT-543-Lot
#description: “BT-733-Lot ND-Lot.ND-LotTenderingTerms.ND-AwardingTerms.ND-LotAwardCriteria.BT-733-Lot - BT-543-Lot” in SF corresponds to “BT-543 Award Criteria Complicated” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/CalculationExpression. The expected ontology instances are epo: epo:Lot / epo:AwardCriterion / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/CalculationExpression

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:specifiesAwardCriterion / epo:hasFormula ?value . }