#title: BT-01(e)-Procedure ND-ProcedureTerms.ND-LocalLegalBasisNoID.BT-01(e)-Procedure - BT-01(e)-Procedure
#description: “BT-01(e)-Procedure ND-ProcedureTerms.ND-LocalLegalBasisNoID.BT-01(e)-Procedure - BT-01(e)-Procedure” in SF corresponds to “BT-01 Procedure Legal Basis” in eForms. The corresponding XML element is /ContractNotice/TenderingTerms/ProcurementLegislationDocumentReference/ID. The expected ontology instances are epo: epo:Procedure / epo:Identifier / rdf:langString .
#xpath: /ContractNotice/TenderingTerms/ProcurementLegislationDocumentReference/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasLegalBasis ?value . }