#title: BT-5101(b)-Lot ND-Lot.ND-LotProcurementScope.ND-LotPlacePerformance.ND-LotPerformanceAddress.BT-5101(b)-Lot - BT-5101(b)-Lot
#description: “BT-5101(b)-Lot ND-Lot.ND-LotProcurementScope.ND-LotPlacePerformance.ND-LotPerformanceAddress.BT-5101(b)-Lot - BT-5101(b)-Lot” in SF corresponds to “BT-5101 Place Performance Street” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/RealizedLocation/Address/AdditionalStreetName. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / dct:Location / locn:Address / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/RealizedLocation/Address/AdditionalStreetName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:definesSpecificPlaceOfPerformance / locn:address / locn:adminUnitL2 ?value . }