#title: BT-774-Lot ND-Lot.ND-LotProcurementScope.BT-774-Lot - BT-263-Lot
#description: “BT-774-Lot ND-Lot.ND-LotProcurementScope.BT-774-Lot - BT-263-Lot” in SF corresponds to “BT-263 Additional Classification Codes” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/AdditionalCommodityClassification/ItemClassificationCode. The expected ontology instances are epo: epo:Lot / epo:Purpose / at-voc:cpvsuppl (from cpvsuppl.json) .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/AdditionalCommodityClassification/ItemClassificationCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:hasPurpose / epo:hasAdditionalClassification ?value . }