#title: BT-1375-Procedure ND-ProcedureTerms.ND-LotDistribution.ND-GroupComposition.BT-1375-Procedure - BT-1375-Procedure
#description: “BT-1375-Procedure ND-ProcedureTerms.ND-LotDistribution.ND-GroupComposition.BT-1375-Procedure - BT-1375-Procedure” in SF corresponds to “BT-1375 Group Lot Identifier” in eForms. The corresponding XML element is /ContractNotice/TenderingTerms/LotDistribution/LotsGroup/ProcurementProjectLotReference/ID/@schemeName. The expected ontology instances are epo: epo:LotGroup / epo:Identifier / xsd:string .
#xpath: /ContractNotice/TenderingTerms/LotDistribution/LotsGroup/ProcurementProjectLotReference/ID/@schemeName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LotGroup .
		?this epo:hasID / epo:hasIdentifierValue ?value . }