#title: OPP-051-Organization ND-RootExtension.ND-Organizations.ND-Organization.OPP-051-Organization - OPP-051-Organization
#description: “OPP-051-Organization ND-RootExtension.ND-Organizations.ND-Organization.OPP-051-Organization - OPP-051-Organization” in SF corresponds to “OPP-051 nan” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/AwardingCPBIndicator. The expected ontology instances are epo: epo:AwardingCentralPurchasingBody / xsd:boolean .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension/Organizations/Organization/AwardingCPBIndicator

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AwardingCentralPurchasingBody .
		?this epo:isContractingEntity ?value }