#title: BT-543-LotsGroup ND-LotsGroup.ND-LotsGroupAwardingTerms.ND-LotsGroupAwardCriteria.BT-543-LotsGroup - BT-543-LotsGroup
#description: “BT-543-LotsGroup ND-LotsGroup.ND-LotsGroupAwardingTerms.ND-LotsGroupAwardCriteria.BT-543-LotsGroup - BT-543-LotsGroup” in SF corresponds to “BT-543 Award Criteria Complicated” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/CalculationExpression. The expected ontology instances are epo: epo:AwardCriterion / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AwardingTerms/AwardingCriterion/CalculationExpression

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AwardCriterion .
		?this cccev:description ?value . }