#title: OPP-070-notice ND-RootExtension.OPP-070-notice - ND-RootExtension
#description: “OPP-070-notice ND-RootExtension.OPP-070-notice - ND-RootExtension” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension. The expected ontology instances are epo: epo:AwardCriterion .
#xpath: /ContractNotice/UBLExtensions/UBLExtension/ExtensionContent/EformsExtension

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AwardCriterion .
		?this a epo:AwardCriterion }