#title: BT-726-LotsGroup ND-LotsGroup.ND-LotsGroupProcurementScope.BT-726-LotsGroup - BT-24-LotsGroup
#description: “BT-726-LotsGroup ND-LotsGroup.ND-LotsGroupProcurementScope.BT-726-LotsGroup - BT-24-LotsGroup” in SF corresponds to “BT-24 Description” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/Description. The expected ontology instances are epo: epo:LotGroup / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/Description

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LotGroup .
		?this cccev:description ?value . }