#title: BT-132(d)-Lot ND-Lot.ND-LotTenderingProcess.ND-PublicOpening.BT-132(d)-Lot - BT-132(d)-Lot
#description: “BT-132(d)-Lot ND-Lot.ND-LotTenderingProcess.ND-PublicOpening.BT-132(d)-Lot - BT-132(d)-Lot” in SF corresponds to “BT-132 Public Opening Date” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/OpenTenderEvent/OccurrenceDate. The expected ontology instances are epo: epo:Lot / epo:OpeningTerm / at-voc:language .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/OpenTenderEvent/OccurrenceDate

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasOpeningDateTime ?value }