#title: BT-737-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-ProcurementDocuments - Documents Unofficial Language
#description: “BT-737-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-ProcurementDocuments - Documents Unofficial Language” in SF corresponds to “BT-737 Documents Unofficial Language” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/LanguageID. The expected ontology instances are epo: epo:AccessTerm / at-voc:language .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/CallForTendersDocumentReference/LanguageID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AccessTerm .
		?this epo:hasUnofficialLanguage ?value }