#title: OPT-301-Lot-Mediator content.GR-Lot.GR-Lot-Review.GR-Lot-Mediator - Mediator Technical Identifier Reference
#description: “OPT-301-Lot-Mediator content.GR-Lot.GR-Lot-Review.GR-Lot-Mediator - Mediator Technical Identifier Reference” in SF corresponds to “OPT-301 nan” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/AppealTerms/MediationParty/PartyIdentification/ID. The expected ontology instances are epo: epo:AgentInRole (from CL1) / org:Organization (from CL2) / epo:Identifier / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/AppealTerms/MediationParty/PartyIdentification/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:playedBy / epo:hasID / epo:hasIdentifierValue ?value . }