#title: OPT-300-Procedure-SProvider ND-ContractingParty.ND-ServiceProvider.ND-ServiceProviderParty.ND-ProviderParty.OPT-300-Procedure-SProvider - OPT-300-Procedure-SProvider
#description: “OPT-300-Procedure-SProvider ND-ContractingParty.ND-ServiceProvider.ND-ServiceProviderParty.ND-ProviderParty.OPT-300-Procedure-SProvider - OPT-300-Procedure-SProvider” in SF corresponds to “OPT-300 nan” in eForms. The corresponding XML element is /*/cac:ContractingParty/cac:Party/cac:ServiceProviderParty/cac:Party/cac:PartyIdentification/cbc:ID. The expected ontology instances are epo: epo:AgentInRole (from CL1) / foaf:Agent .
#xpath: /*/cac:ContractingParty/cac:Party/cac:ServiceProviderParty/cac:Party/cac:PartyIdentification/cbc:ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Buyer .
		?this epo:playedBy ?value }