#title: metadata - OJEU Publication Date
#description: “metadata - OJEU Publication Date” in SF corresponds to “OPP-012 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014//*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Publication/efbc:PublicationDate. The expected ontology instances are epo: Metadata not Mapped .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014//*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Publication/efbc:PublicationDate



ASK WHERE { 
		Metadata not Mapped }