#title: BT-10-Procedure-Buyer ND-ContractingParty.BT-10-Procedure-Buyer - BT-10-Procedure-Buyer
#description: “BT-10-Procedure-Buyer ND-ContractingParty.BT-10-Procedure-Buyer - BT-10-Procedure-Buyer” in SF corresponds to “BT-10 Activity Authority” in eForms. The corresponding XML element is /*/cac:ContractingParty/cac:ContractingActivity/cbc:ActivityTypeCode[@listName='authority-activity']. The expected ontology instances are epo: org:Organization / at-voc:main-activity (from main_activity.csv) .
#xpath: /*/cac:ContractingParty/cac:ContractingActivity/cbc:ActivityTypeCode[@listName='authority-activity']

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type org:Organization .
		?this epo:hasMainActivity ?value . }