#title: metadata - Notice Official Language
#description: “metadata - Notice Official Language” in SF corresponds to “BT-702 Notice Official Language” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:NoticeLanguageCode. The expected ontology instances are epo: Metadata not Mapped .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:NoticeLanguageCode



ASK WHERE { 
		Metadata not Mapped }