#title: BT-75-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-FinancialGuarantee - Guarantee Required Description
#description: “BT-75-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-FinancialGuarantee - Guarantee Required Description” in SF corresponds to “BT-75 Guarantee Required Description” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/RequiredFinancialGuarantee/Description. The expected ontology instances are epo: epo:Lot / epo:SubmissionTerm / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/RequiredFinancialGuarantee/Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasGuaranteeDescription ?value . }