#title: BT-01-notice BT-01-notice - OPP-090-Procedure
#description: “BT-01-notice BT-01-notice - OPP-090-Procedure” in SF corresponds to “OPP-090 nan” in eForms. The corresponding XML element is /ContractNotice/TenderingProcess/NoticeDocumentReference/ID. The expected ontology instances are epo: epo:Notice / epo:Notice / epo:Identifier / xsd:string .
#xpath: /ContractNotice/TenderingProcess/NoticeDocumentReference/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Notice .
		?this epo:refersToPrevious / epo:hasID / epo:hasIdentifierValue ?value }