#title: BT-60-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-EUFunds - EU Funds
#description: “BT-60-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-EUFunds - EU Funds” in SF corresponds to “BT-60 EU Funds” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/FundingProgramCode/@listName. The expected ontology instances are epo: epo:Lot / xsd:boolean .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/FundingProgramCode/@listName

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isUsingEUFunds ?value . }