#title: BT-58-Lot ND-Lot.ND-LotProcurementScope.ND-OptionsAndRenewals.BT-58-Lot - BT-58-Lot
#description: “BT-58-Lot ND-Lot.ND-LotProcurementScope.ND-OptionsAndRenewals.BT-58-Lot - BT-58-Lot” in SF corresponds to “BT-58 Renewal Maximum” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/ProcurementProject/ContractExtension/MaximumNumberNumeric. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / xsd:integer .
#xpath: /ContractNotice/ProcurementProjectLot/ProcurementProject/ContractExtension/MaximumNumberNumeric

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:hasMaximumNumberOfRenewals ?value }