#title: BT-133-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-PublicOpeningEvent - Public Opening Place
#description: “BT-133-Lot content.GR-Lot.GR-Lot-SubmissionInfo.GR-Lot-PublicOpeningEvent - Public Opening Place” in SF corresponds to “BT-133 Public Opening Place” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/OpenTenderEvent/OccurenceLocation/Description. The expected ontology instances are epo: epo:Lot / epo:OpeningTerm / locn:Location / rdf:langString .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/OpenTenderEvent/OccurenceLocation/Description

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:definesOpeningPlace / locn:postName ?value }