#title: BT-125(i)-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-PreviousPlanning - Previous Planning Identifier
#description: “BT-125(i)-Lot content.GR-Lot.GR-Lot-Purpose.GR-Lot-PreviousPlanning - Previous Planning Identifier” in SF corresponds to “BT-125 Previous Planning Identifier” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingProcess/NoticeDocumentReference/ID. The expected ontology instances are epo: epo-not:PlanningNotice / epo:Identifier / xsd:string .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingProcess/NoticeDocumentReference/ID

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo-not:PlanningNotice .
		?this epo:hasID / epo:hasIdentifierValue ?value }