#title: ND-ServiceProviderParty ND-ContractingParty.ND-ServiceProvider.ND-ServiceProviderParty - BT-508-Procedure-Buyer
#description: “ND-ServiceProviderParty ND-ContractingParty.ND-ServiceProvider.ND-ServiceProviderParty - BT-508-Procedure-Buyer” in SF corresponds to “BT-508 Buyer Profile URL” in eForms. The corresponding XML element is /ContractNotice/ContractingParty/BuyerProfileURI. The expected ontology instances are epo: epo:AgentInRole (from CL1) / xsd:anyURI .
#xpath: /ContractNotice/ContractingParty/BuyerProfileURI

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { 
		?this epo:hasBuyerProfile ?value . }