#title: BT-510(c)-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress.BT-510(c)-Organization-Company - BT-510(c)-Organization-Company
#description: “BT-510(c)-Organization-Company ND-RootExtension.ND-Organizations.ND-Organization.ND-Company.ND-CompanyAddress.BT-510(c)-Organization-Company - BT-510(c)-Organization-Company” in SF corresponds to “BT-510 Organisation Street” in eForms. The corresponding XML element is /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company/cac:PostalAddress/cac:AddressLine/cbc:Line. The expected ontology instances are epo: org:Organization (from CL2) /  locn:Address / rdf:langString .
#xpath: /*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company/cac:PostalAddress/cac:AddressLine/cbc:Line

PREFIX cv: <http://data.europa.eu/m8g/>
PREFIX locn: <http://www.w3.org/ns/locn#>

ASK WHERE { 
		?this cv:registeredAddress / locn:thoroughfare ?value . }