#title: ND-ProcedureValueEstimate ND-ProcedureProcurementScope.ND-ProcedureValueEstimate - BT-531-Procedure
#description: “ND-ProcedureValueEstimate ND-ProcedureProcurementScope.ND-ProcedureValueEstimate - BT-531-Procedure” in SF corresponds to “BT-531 Additional Nature” in eForms. The corresponding XML element is /ContractNotice/ProcurementProject/ProcurementAdditionalType/ProcurementTypeCode. The expected ontology instances are epo: epo:ContractTerm / at-voc:contract-nature .
#xpath: /ContractNotice/ProcurementProject/ProcurementAdditionalType/ProcurementTypeCode

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ContractTerm .
		?this epo:hasAdditionalContractNature ?value }