#title: BT-78-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-Requirements2SecurityClearance1 - Security Clearance Deadline
#description: “BT-78-Lot content.GR-Lot.GR-Lot-TenderingTerms.GR-Lot-Requirements2SecurityClearance1 - Security Clearance Deadline” in SF corresponds to “BT-78 Security Clearance Deadline” in eForms. The corresponding XML element is /ContractNotice/ProcurementProjectLot/TenderingTerms/LatestSecurityClearanceDate. The expected ontology instances are epo: epo:Lot / epo:SecurityClearanceTerm / xsd:dateTime .
#xpath: /ContractNotice/ProcurementProjectLot/TenderingTerms/LatestSecurityClearanceDate

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasDeadline ?value }