#title: metadata - UBL version ID (UBL)
#description: “metadata - UBL version ID (UBL)” in SF corresponds to “OPT-001 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:UBLVersionID. The expected ontology instances are epo: Metadata not Mapped .
#xpath: /TED_EXPORT/FORM_SECTION/F25_2014//*/cbc:UBLVersionID



ASK WHERE { 
		Metadata not Mapped }