#title: I.4 - Type of the contracting authority
#description: “I.4 - Type of the contracting authority” in SF corresponds to “BT-11 Buyer Legal Type” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/CA_TYPE. The expected ontology instances are epo: org:Organization / at-voc:buyer-legal-type (from buyer_legal_type.csv) .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasBuyerType ?value . }