#title: IV.2.8.1 - The notice involves the termination of the dynamic purchasing system published by the above contract notice
#description: “IV.2.8.1 - The notice involves the termination of the dynamic purchasing system published by the above contract notice” in SF corresponds to “BT-119 Dynamic Purchasing System Termination” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/TERMINATION_DPS. The expected ontology instances are epo: epo:ProcurementProcessInformation / xsd:boolean .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:isDPSTerminated ?value . }