#title: V.1.1.1 - No tenders or requests to participate were received or all were rejected
#description: “V.1.1.1 - No tenders or requests to participate were received or all were rejected” in SF corresponds to “BT-144 Not Awarded Reason” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/NO_AWARDED_CONTRACT/PROCUREMENT_UNSUCCESSFUL. The expected ontology instances are epo: epo:LotAwardOutcome / at-voc:non-award-justification .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasNonAwardJustification <http://publications.europa.eu/resource/authority/non-award-justification/all-rej> . }