#title: V.0.3 - Lot No
#description: “V.0.3 - Lot No” in SF corresponds to “BT-13713 Result Lot Identifier” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/LOT_NO. The expected ontology instances are epo: epo:Contract / epo:Lot / epo:Identifier / xsd:string .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:includesLot / epo:hasID / epo:hasIdentifierValue ?value . }