#title: IV.1.8 - Information about the Government Procurement Agreement (GPA)
#description: “IV.1.8 - Information about the Government Procurement Agreement (GPA)” in SF corresponds to “BT-115 GPA Coverage” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/CONTRACT_COVERED_GPA. The expected ontology instances are epo: epo:Procedure / xsd:boolean .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:isCoveredbyGPA ?value . }