#title: II.1.7 - Total value of the procurement (Excluding VAT)
#description: “II.1.7 - Total value of the procurement (Excluding VAT)” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT. The expected ontology instances are epo: epo:ResultNotice / epo:NoticeAwardInformation .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:announcesNoticeAwardInformation ?value . }