#title: V.2.5.4 - Currency
#description: “V.2.5.4 - Currency” in SF corresponds to “no direct match nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/AWARDED_CONTRACT/VAL_SUBCONTRACTING/@CURRENCY. The expected ontology instances are epo: epo:Tender / epo:SubcontractingEstimate / MonetaryValue /at-voc:currency (from currency.json) .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:foreseesSubcontracting / epo:hasSubcontractingEstimatedValue / epo:hasCurrency ?value . }