#title: II.2.13.2 - Identification of the project
#description: “II.2.13.2 - Identification of the project” in SF corresponds to “BT-5011 Contract EU Funds Identifier” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/EU_PROGR_RELATED/P. The expected ontology instances are epo: epo:Lot / epo:Fund / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:isFundedBy / epo:hasDescription ?value . }