= Toolchain used in the mapping development process

The mapping artefacts, including the various mapping suite packages that are being developed by the process described in this document, are stored and maintained in the https://github.com/OP-TED/ted-rdf-mapping[OP-TED/ted-rdf-mapping] GitHub repository.

To assist the semantic engineers in the development of mapping suites a toolchain has been developed. There are a number of command line tools (CLIs) available in the https://github.com/OP-TED/ted-rdf-conversion-pipeline[OP-TED/ted-rdf-conversion-pipeline] GitHub repository that can be run on these mapping suites to process them in various ways. In order to run these CLIs the ted-sws project needs to be installed in the rdf-mapping environment. This can be done by following the *installation instructions* provided https://github.com/OP-TED/ted-rdf-conversion-pipeline#installation[here].

After the installation, the following CLIs will be available (the name of the tools to be executed on the command line are specified in parentheses).

=== SPARQL Test Generator (sparql_generator)

This CLI generates a set of SPARQL queries from the conceptual mapping that will be executed by the `sparql_runner` CLI (described in the next section). Each generated query will be used to test if the related conceptual mapping is correctly generating RDF data or not.

For more detailed documentation on its usage please check out the https://github.com/OP-TED/ted-rdf-conversion-pipeline#cmd-sparql_generator[readme file].

=== SPARQL Queries Runner (sparql_runner)
This CLI  executes  all the sparql queries generated by sparql_generator into each RDF result file. The results of this execution are one report per RDF file that contains the queries associated to indicators (True, False or Error).

Each indicator helps semantic engineers and reviewers to figure out different information as it shown down below:

* True: the mapping corresponding to the sparql query does work.

* False: the mapping didn't generate RDF results that would match the query. This can happen either when an expected element is missing on the XML notice, or if there is a problem with the mapping rules.

* Error: the SPARQL query is incorrect. That means that the conceptual mapping has to be reviewed.

For more detailed take a look at the following example https://github.com/OP-TED/ted-rdf-mapping/blob/main/mappings/package_F03/output/002705-2021/test_suite_report/sparql_cm_assertions.html[here].

=== Resources Injector (resources_injector)
This CLI injects the requested resources listed on the "Resources" spreadsheet of the Conceptual Mappings into the MappingSuite. Each Form has resources list that represent the controlled value that are needed in the mapping process.

Consult the authority tables used in the EPO available from the https://op.europa.eu/en/web/eu-vocabularies/authority-tables[EU Vocabularies].

For more detailed documentation on its usage please check out the https://github.com/OP-TED/ted-rdf-conversion-pipeline#cmd-resources_injector[readme file].

=== RML Modules Injector (rml_modules_injector)
This CLI injects the technical mappings modules from the `src/mappings` folder (see xref:methodology.adoc#_technical-mapping-modularisation-chapter[modules chapter]) into the mapping suite. Each form has a module list that is needed in order to run the mapping_runner.
The modules name are listed on the "RML_Modules" spreadsheet of the Conceptual Mappings

For more detailed documentation on its usage please check out the https://github.com/OP-TED/ted-rdf-conversion-pipeline#cmd-rml_modules_injector[readme file].

=== Mapping Test Runner (mapping_runner)
This CLI applies the mapping on a certain test notice file, a batch of notice files (organised in a folder), or on all available test notices, and generates output files representing the corresponding RDF graph for each notice (see RDF output examples https://github.com/OP-TED/ted-rdf-mapping/tree/main/mappings/package_F03/output[here]).

For more detailed documentation on its usage please check out the https://github.com/OP-TED/ted-rdf-conversion-pipeline#cmd-mapping_runner[readme file].

=== Metadata generator (metadata_generator)
This tool extracts the relevant metadata from the conceptual mapping file (by default: `conceptual_mappings.xlsx`) and stores it in a JSON file (by default: `metadata.json`). This metadata file will be used by various other processes (both CLIs and DAGs), mainly to inform them about the applicability of this mapping to various notices.

For more detailed documentation on its usage please check out the https://github.com/OP-TED/ted-rdf-conversion-pipeline#cmd-metadata_generator[readme file].

=== YARRRML to RML Converter (yarrrml2rml_converter)
This command line tool allows the conversion of a mapping expressed in the more user-friendly YARRRML syntax to RML. This is a very useful tool, especially at initial phases of the mapping development, or for newcomers, as it is easier and faster to write YARRRML rules than RML rules.

For more detailed documentation on its usage please check out the https://github.com/OP-TED/ted-rdf-conversion-pipeline#cmd-yarrrml2rml_converter[readme file].

=== SHACL Validation Runner (shacl_runner)
Generates SHACL Validation Reports for RDF files.
For more detailed documentation on its usage please check out the https://github.com/OP-TED/ted-rdf-conversion-pipeline#cmd-shacl_runner[readme file].

=== Mapping Suite Processor (mapping_suite_processor)
This CLI runs all the necessary CLIs mentioned above in a logical order, to fully process a mapping suite, starting with the generation of metadata and up to running the mapping on all the (specified) tests data, and generating all the possible associated validation artefacts.

For more detailed documentation on its usage please check out the https://github.com/OP-TED/ted-rdf-conversion-pipeline#cmd-mapping_suite_processor[readme file].

=== Other relevant tools and libraries
Other relevant tools that are used in the mapping process that worth mentioning, are:

https://rml.io/yarrrml/matey/#[Matey]: a browser-based application that helps writing YARRRML rules, and converting them to RML rules that can be also executed online. Matey uses the yarrrml-parser (described next) in the backend.

The https://github.com/rmlio/yarrrml-parser[RMLio/yarrrml-parser] library, available on GitHub, allows the conversion of YARRRML rules to RML or R2RML rules.  Since this is a library, besides using it to power Matey, it can be also used independently, or as an integrated part of our CLI tools.

The https://github.com/RMLio/rmlmapper-java[RMLio/rmlmapper-java] library, available on GitHub, allows the execution of a set of RML mappings on a set of data sources, to generate high quality RDF data.





