= Mapping Methodology

The purpose of this guide is to describe a *methodology for creating mapping rules* that can be used for transforming XML data representing the content of the TED “Standard” Forms into RDF graphs that conform to the https://github.com/OP-TED/ePO[ePO ontology].

The methodology will rely on various resources generated by earlier attempts (e.g. those created by Everis), outcomes of projects that work on related issues (e.g. by Deloitte e.a.), as well as the input of a number of people with in-depth knowledge of the ePO ontology, XML, RML and expertise in Semantic Web technologies in general.

The mappings generated by this methodology are to be used as part of https://docs.ted.europa.eu/rdf-conversion/_attachments/ted-sws-architecture/index.html?goto=1:1:36[the notice transformation workflow] for *all* https://ted.europa.eu/TED/browse/browseByMap.do[Tenders Electronic Daily (TED)] notices conforming to "Standard" forms that are published in the TED XML format, into RDF format, in order to make it available for querying through a SPARQL endpoint.


include::partial$methodology/mapping-lifecycle.adoc[]

include::partial$methodology/key-elements-for-mapping.adoc[]

include::partial$methodology/conceptual-mapping-structure.adoc[]

include::partial$methodology/mapping-creation-method.adoc[]

include::partial$methodology/technical-mapping-modularisation.adoc[]

