= Repository structure

Transformation rules and other artefacts for the https://github.com/OP-TED/ted-rdf-conversion-pipeline[TED Semantic Web Services (TED-SWS)] system are organised in https://github.com/OP-TED/ted-rdf-mapping[this repository].

The repository is organised as presented below. Next, we describe the important folders and their purpose.

----
/cm_diffs
/docs
    /antora
/mappings
    /package_F03
    /package_F06
    ...
    /package_F25
/src
    /mappings
        *.rml.ttl
/test_data
    /sampling_2014_2022
    /sampling_2021
    /sampling_manual
LICENSE
Makefile
README.md
requirements.txt
----
`/cm_diffs` folder contains json files that indicate differences in the conceptual mapping of
a xref:mapping-suite-structure.adoc[mapping suite package]. More specifically, a json file from this folder will indicate what changes occured
between two immediate subsequent versions to the conceptual mapping of a mapping suite package.

`/docs` folder contains the documentation of the project. It is written in AsciiDoc format
https://asciidoc.org/[AsciiDoc format] and compiled with Antora system
read more about AsciiDoc and Antora on https://antora.org/[Antora system].

`/mappings` folder contains
xref:mapping-suite-structure.adoc[mapping suite packages]
organised based on the standard forms numbers.
Their name is formed based on the form number (e.g. `F03`, `F06`)
prefixed with `package_` for readability. For the eForms the same rationality was followed
as we attached the prefix `package_` to the eForm subtype (currently ef16).

`/src/mappings` folder represents the "single source of truth"
for the mapping rules across various mapping suite packages.
This is necessary because of the
xref:methodology.adoc#_technical-mapping-modularisation[modularisation and reuse method]
adopted in this project. The basic idea is that the mapping rules are
organised in modules and all are stored in the source folder.
Each mapping suite provides in the
xref:methodology.adoc#_conceptual-mapping-structure[conceptual mapping workbook]
the list of modules that are used to compose the complete set of transformation
rules of the mapped form number.

`/test_data` folder contains sample https://ted.europa.eu/TED/browse/browseByMap.do[TED notices]
generated by different selection methods. Some manually selected notices are available
in the `/sampling_manual` subfolder. The automatically generated notice samples that
are in the `/sampling_2021` subfolder are described xref:preparing-test-data.adoc[here].
In the `sampling_2014_2022` subfolder there are samples, generated from all available
notices in the 2014-2022 period that cover the various changes in the XML Schema over
the years.

`LICENSE` is the https://github.com/OP-TED/ted-rdf-mapping/blob/main/LICENSE[European Union Public License 1.2]
The European Union Public Licence (EUPL) is a copyleft free/open
source software license created on the initiative of and approved by the European Commission in 23 official languages of the European Union.

`Makefile` is a program building tool which runs on Unix, Linux, and their flavors. It aids in simplifying building program executables that may need various modules. To determine how the modules need to be compiled or recompiled together, make takes the help of user-defined makefiles.

`ReadMe.md` is the read me file from https://github.com/OP-TED/ted-rdf-mapping[this repository].

`requirements.txt` is the https://github.com/OP-TED/ted-rdf-conversion-pipeline[TED Semantic Web Services (TED-SWS)] project dependencies.