#title: Empty Individuals ASK TED-929/TED-933
#description: Checks that there are no "empty" individuals, i.e. individuals that do not have any property values attached other than their type

PREFIX epd: <http://data.europa.eu/a4g/resource/>

ASK {
SELECT ?this WHERE {
    {
      SELECT ?this (COUNT(?someValue) AS ?vCount)  WHERE {
        ?this ?property ?someValue.
  		FILTER strstarts(str(?this),str(epd:)).
      } GROUP BY ?this
    }
    FILTER ((EXISTS {?this a ?class}) && ?vCount > 1)
}
}