#title: IV.1.1.1.1 - Accelerated procedure
#description: “IV.1.1.1.1 - Accelerated procedure” in SF corresponds to “BT-106 Procedure Accelerated” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/ACCELERATED_PROC. The expected ontology instances are epo: epo:Procedure / xsd:boolean .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:isAccelerated ?value . }