#title: nan - nan
#description: “nan - nan” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/NOTICE_NUMBER_OJ. The expected ontology instances are epo: epo:ProcurementProcessInformation / epo:Procedure .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:concernsProcedure ?value }