#title: I.2.1.1 - In the case of joint procurement involving different countries, state applicable national procurement law
#description: “I.2.1.1 - In the case of joint procurement involving different countries, state applicable national procurement law” in SF corresponds to “BT-09 Cross Border Law” in eForms. The corresponding XML element is nanCONTRACTING_BODY/PROCUREMENT_LAW. The expected ontology instances are epo: epo:ResultNotice / epo:Procedure / at-voc:legal-basis .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:refersToProcedure / epo:hasLegalBasis ?value . }