#title: II.1.7 - Total value of the procurement (Excluding VAT)
#description: “II.1.7 - Total value of the procurement (Excluding VAT)” in SF corresponds to “nan nan” in eForms. The corresponding XML element is nannan. The expected ontology instances are epo: epo:SubmissionStatisticalInformation / epo:Lot .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:concernsSubmissionsForLot ?value . }