#title: I.1.9 - Telephone
#description: “I.1.9 - Telephone” in SF corresponds to “BT-503 Organisation Contact Telephone Number” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/ADDRESS_CONTRACTING_BODY/PHONE. The expected ontology instances are epo: epo:AgentInRole (from CL1) / cpov:ContactPoint / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX cpov: <http://data.europa.eu/m8g/>

ASK WHERE { ?this epo:hasContactPointInRole  / cpov:telephone ?value . }