#title: V.1.1.3 - Notice reference
#description: “V.1.1.3 - Notice reference” in SF corresponds to “no match nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/NO_AWARDED_CONTRACT/PROCUREMENT_DISCONTINUED/NO_DOC_EXT/@PUBLICATION. The expected ontology instances are epo: epo:LotAwardOutcome / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasAdditionalNonAwardJustification ?value . }