#title: II.1.1.1 - Reference number
#description: “II.1.1.1 - Reference number” in SF corresponds to “BT-22 Internal Identifier” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/REFERENCE_NUMBER. The expected ontology instances are epo: epo:Procedure / epo:Identifier / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasID / epo:hasIdentifierValue ?value . }