#title: IV.1.1.5 - Innovation partnership
#description: “IV.1.1.5 - Innovation partnership” in SF corresponds to “BT-105 Procedure Type” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/PT_INNOVATION_PARTNERSHIP. The expected ontology instances are epo: epo:Procedure / at-voc:procurement-procedure-type .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasProcedureType <http://publications.europa.eu/resource/authority/procurement-procedure-type/innovation> . }