#title: I.1.1 - Official name
#description: “I.1.1 - Official name” in SF corresponds to “BT-500 Organisation Name” in eForms. The corresponding XML element is nanADDRESS_CONTRACTING_BODY/OFFICIALNAME. The expected ontology instances are epo: epo:Role (from CL1) / epo:Organisation (from CL2) / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:playedBy / epo:hasName ?value . }