#title: V.2.0.1 - nan
#description: “V.2.0.1 - nan” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/AWARDED_CONTRACT. The expected ontology instances are epo: epo:LotAwardOutcome / epo:TenderAwardOutcome / epo:Tender .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:comprisesTenderAwardOutcome / epo:describesTender ?value }