#title: V.2.1 - Date of conclusion of the contract
#description: “V.2.1 - Date of conclusion of the contract” in SF corresponds to “BT-145 Contract Conclusion Date” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/AWARDED_CONTRACT/DATE_CONCLUSION_CONTRACT. The expected ontology instances are epo: epo:Contract / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasContractConclusionDate ?value . }