#title: V.2.5.1 - ⃞The contract is likely to be subcontracted
#description: “V.2.5.1 - ⃞The contract is likely to be subcontracted” in SF corresponds to “BT-773 Subcontracting” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/AWARDED_CONTRACT/LIKELY_SUBCONTRACTED. The expected ontology instances are epo: epo:Tender / epo:SubcontractingEstimate  .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:foreseesSubcontracting ?value }