#title: V.2.2.2 - Number of tenders received from SMEs
#description: “V.2.2.2 - Number of tenders received from SMEs” in SF corresponds to “BT-760 Received Submissions Type” in eForms. The corresponding XML element is nanAWARD_CONTRACT/AWARDED_CONTRACT/TENDERS/NB_TENDERS_RECEIVED_SME. The expected ontology instances are epo: epo:SubmissionStatisticalInformation / xsd:integer .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasReceivedSMETenders ?value . }