#title: V.2.5.4 - Currency
#description: “V.2.5.4 - Currency” in SF corresponds to “no direct match nan” in eForms. The corresponding XML element is nanVAL_SUBCONTRACTING/@CURRENCY. The expected ontology instances are epo: epo:Tender / epo:SubcontractingEstimate / MonetaryValue /at-voc:currency (from CL9) .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:forseesSubcontracting / epo:hasSubcontractingEstimatedValue / epo:hasCurrecy ?value . }