#title: V.2.3.5 - NUTS code
#description: “V.2.3.5 - NUTS code” in SF corresponds to “BT-507 Organisation Country Subdivision” in eForms. The corresponding XML element is nanAWARD_CONTRACT/AWARDED_CONTRACT/CONTRACTORS/CONTRACTOR/ADDRESS_CONTRACTOR/n2016:NUTS/@CODE. The expected ontology instances are epo: epo:Role (from CL1)  / org:Organization (from CL2) / locn:Address / at-voc:nuts (from CL3) .

PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:playedBy / epo:hasRegisteredAddress / locn:adminUnitL2 ?value . }