#title: II.1.7.4 - Currency
#description: “II.1.7.4 - Currency” in SF corresponds to “nan nan” in eForms. The corresponding XML element is nanVAL_TOTAL/@CURRENCY. The expected ontology instances are epo: epo:Procedure / epo:MonetaryValue / at-voc:currency (from CL9) .

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this rdf:type / epo:hasEstimatedValue / epo:hasCurrency ?value . }