#title: I.4 - Type of the contracting authority
#description: “I.4 - Type of the contracting authority” in SF corresponds to “BT-11 Buyer Legal Type” in eForms. The corresponding XML element is nanCONTRACTING_BODY/CA_TYPE. The expected ontology instances are epo: epo:Role / epo:Buyer / at-voc:buyer-legal-type (from CL5) .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasBuyerType ?value . }