#title: IV.1.8 - Information about the Government Procurement Agreement (GPA)
#description: “IV.1.8 - Information about the Government Procurement Agreement (GPA)” in SF corresponds to “BT-115 GPA Coverage” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/NO_CONTRACT_COVERED_GPA. The expected ontology instances are epo: epo:Procedure / xsd:boolean .
#xpath: /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/NO_CONTRACT_COVERED_GPA

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:isCoveredByGPA false . }