#title: V.2.3.5 - NUTS code
#description: “V.2.3.5 - NUTS code” in SF corresponds to “BT-507 Organisation Country Subdivision” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/AWARDED_CONTRACT/CONTRACTORS/CONTRACTOR/ADDRESS_CONTRACTOR/n2016:NUTS/@CODE. The expected ontology instances are epo: epo:AgentInRole (from CL1)  / org:Organization (from CL2) / locn:Address / at-voc:nuts (from nuts.json) .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX legal: <None>

ASK WHERE { ?this epo:playedBy / legal:registeredAddress / epo:hasNutsCode ?value . }