#title: V.1.1 - The contract/lot is not awarded
#description: “V.1.1 - The contract/lot is not awarded” in SF corresponds to “--- nan” in eForms. The corresponding XML element is . The expected ontology instances are epo: epo:LotAwardOutcome / epo:Lot .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:describesLot ?value }