#title: I.1.6 - Postal code
#description: “I.1.6 - Postal code” in SF corresponds to “BT-512 Place Performance Post Code” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/ADDRESS_CONTRACTING_BODY/POSTAL_CODE. The expected ontology instances are epo: epo:AgentInRole (from CL1)  / org:Organization (from CL2) / locn:Address / rdf:langString .

PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX legal: <None>

ASK WHERE { ?this epo:playedBy / legal:registeredAddress / locn:postCode ?value . }