#title: V.2.2.4 - Number of tenders received from tenderers from non-EU Member States
#description: “V.2.2.4 - Number of tenders received from tenderers from non-EU Member States” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/AWARDED_CONTRACT/TENDERS/NB_TENDERS_RECEIVED_NON_EU. The expected ontology instances are epo: epo:SubmissionStatisticalInformation / xsd:integer .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasReceivedNonEUTenders ?value . }