#title: V.2.3.9 - Telephone
#description: “V.2.3.9 - Telephone” in SF corresponds to “BT-503 Organisation Contact Telephone Number” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/AWARDED_CONTRACT/CONTRACTORS/CONTRACTOR/ADDRESS_CONTRACTOR/PHONE. The expected ontology instances are epo: epo:AgentInRole (from CL1) / org:Organization (from CL2) / cpov:ContactPoint / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX cpov: <http://data.europa.eu/m8g/>

ASK WHERE { ?this epo:playedBy / epo:hasPrimaryContactPoint / cpov:telephone ?value . }