#title: V.1.1 - The contract/lot is not awarded
#description: “V.1.1 - The contract/lot is not awarded” in SF corresponds to “--- nan” in eForms. The corresponding XML element is . The expected ontology instances are epo: epo:LotAwardOutcome / epo:Lot .
#xpath: 

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LotAwardOutcome .
		?value rdf:type epo:Lot .
		?this epo:describesLot ?value }