#title: VI.4.3 - Review procedure
#description: “VI.4.3 - Review procedure” in SF corresponds to “BT-99 Review Deadline Description” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/COMPLEMENTARY_INFO/REVIEW_PROCEDURE. The expected ontology instances are epo: epo:Procedure / epo:ReviewTerm / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F03_2014/COMPLEMENTARY_INFO/REVIEW_PROCEDURE

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:isSubjectToProcedureSpecificTerm / epo:hasReviewDeadlineInformation ?value . }