#title: V.0.1 - Contract No
#description: “V.0.1 - Contract No” in SF corresponds to “BT-150 Contract Identifier” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/CONTRACT_NO. The expected ontology instances are epo: epo:Contract / epo:Identifier / xsd:string .
#xpath: /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/CONTRACT_NO

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Contract .
		?this epo:hasID / epo:hasIdentifierValue ?value . }