#title: I.2.2 - The contract is awarded by a central purchasing body
#description: “I.2.2 - The contract is awarded by a central purchasing body” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/CENTRAL_PURCHASING. The expected ontology instances are epo: epo:AwardingCentralPurchasingBody / epo:OrganisationGroup .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:playedBy ?value }