#title: I.1.12.2 - Address of the buyer profile
#description: “I.1.12.2 - Address of the buyer profile” in SF corresponds to “BT-508 Buyer Profile URL” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/ADDRESS_CONTRACTING_BODY/URL_BUYER. The expected ontology instances are epo: epo:AgentInRole (from CL1) / epo:BuyerProfile / xsd:anyURI .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasBuyerProfile / epo:hasURL ?value . }