#title: I.4.1 - Type of the contracting authority
#description: “I.4.1 - Type of the contracting authority” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/CA_TYPE_OTHER. The expected ontology instances are epo: org:Organization / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/CA_TYPE_OTHER

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type org:Organization .
		?this epo:hasBuyerLegalTypeDescription ?value . }