#title: V.2.3.12 - The contractor is an SME
#description: “V.2.3.12 - The contractor is an SME” in SF corresponds to “BT-165 Winner Size” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/AWARDED_CONTRACT/CONTRACTORS/CONTRACTOR/SME. The expected ontology instances are epo: epo:AgentInRole (from CL1)  / epo:Business / at-voc:economic-operator-size .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:playedByBusiness / epo:hasBusinessSize <http://publications.europa.eu/resource/authority/economic-operator-size> }