#title: MetaData - nan
#description: “MetaData - nan” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/LEGAL_BASIS/@VALUE. The expected ontology instances are epo: epo:Procedure / at-voc:legal-basis .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasLegalBasis ?value }