#title: I.2.1 - The contract involves joint procurement
#description: “I.2.1 - The contract involves joint procurement” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/JOINT_PROCUREMENT_INVOLVED. The expected ontology instances are epo: epo:ResultNotice / epo:Procedure / xsd:boolean .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:refersToProcedure / epo:isJointProcurement ?value . }