#title: II.2.11.2 - Description of options
#description: “II.2.11.2 - Description of options” in SF corresponds to “BT-54 Options Description” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/OPTIONS_DESCR. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:foreseesContractSpecificTerm / epo:hasOptionsDescription ?value . }