#title: VI.4.4.9 - Fax
#description: “VI.4.4.9 - Fax” in SF corresponds to “BT-739 Organisation Contact Fax” in eForms. The corresponding XML element is nanCOMPLEMENTARY_INFO/ADDRESS_REVIEW_INFO/FAX. The expected ontology instances are epo: epo:Role (from CL1)  / org:Organization (from CL2) / epo:ContactPoint / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:playedBy / epo:hasPrimaryContactPoint  / epo:hasFax ?value . }