#title: II.2.5.2.2 - hasFormula
#description: “II.2.5.2.2 - hasFormula” in SF corresponds to “BT-543 Award Criterion complicated” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/AC/AC_COST/AC_WEIGHTING ;; /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/AC_COST/AC_WEIGHTING. The expected ontology instances are epo: epo:AwardCriterion / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/AC/AC_COST/AC_WEIGHTING ;; /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/AC_COST/AC_WEIGHTING

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AwardCriterion .
		?this cccev:weight ?value . }