#title: IV.1.3.1 - The procurement involves the establishment of a framework agreement
#description: “IV.1.3.1 - The procurement involves the establishment of a framework agreement” in SF corresponds to “BT-765 Framework Agreement” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/FRAMEWORK. The expected ontology instances are epo: epo:Procedure /  epo:FrameworkAgreementTechniqueUsage .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:usesTechnique ?value . }