#title: V.2.2.2 - Number of tenders received from SMEs
#description: “V.2.2.2 - Number of tenders received from SMEs” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/AWARDED_CONTRACT/TENDERS/NB_TENDERS_RECEIVED_SME. The expected ontology instances are epo: epo:SubmissionStatisticalInformation / xsd:integer .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasReceivedSMETenders ?value . }