#title: V.0.2 - nan
#description: “V.0.2 - nan” in SF corresponds to “nan nan” in eForms. The corresponding XML element is nanAWARD_CONTRACT. The expected ontology instances are epo: epo:Contract / epo:Contractor .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:bindsContractor ?value }