#title: II.2.5.1 - Quality criterion – Name: / Weighting:
#description: “II.2.5.1 - Quality criterion – Name: / Weighting:” in SF corresponds to “BT-539 Award Criterion Type” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/AC/AC_QUALITY. The expected ontology instances are epo: epo:AwardCriterion / at-voc:award-criterion-type .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasAwardCriterionType <http://publications.europa.eu/resource/authority/award-criterion-type/quality> . }