#title: D1.1.9.2 - From the liquidator in an insolvency procedure, an arrangement with creditors or a similar procedure under national laws and regulations
#description: “D1.1.9.2 - From the liquidator in an insolvency procedure, an arrangement with creditors or a similar procedure under national laws and regulations” in SF corresponds to “BT-136 Direct Award Justification Code” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/PT_AWARD_CONTRACT_WITHOUT_CALL/D_ACCORDANCE_ARTICLE/D_FROM_LIQUIDATOR_CREDITOR. The expected ontology instances are epo: epo:Procedure / epo:DirectAwardTerm / at-voc:direct-award-justification .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:isSubjectToProcedureSpecificTerm / epo:hasDirectAwardJustification <http://publications.europa.eu/resource/authority/direct-award-justification/liquidator> . }