#title: V.2.2.4 - Number of tenders received from tenderers from non-EU Member States
#description: “V.2.2.4 - Number of tenders received from tenderers from non-EU Member States” in SF corresponds to “BT-760 Received Submissions Type” in eForms. The corresponding XML element is nanAWARD_CONTRACT/AWARDED_CONTRACT/TENDERS/NB_TENDERS_RECEIVED_NON_EU. The expected ontology instances are epo: epo:SubmissionStatisticalInformation / xsd:integer .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasReceivedNonEEATenders ?value . }