#title: V.2.3.8 - E-mail
#description: “V.2.3.8 - E-mail” in SF corresponds to “BT-506 Organisation Contact Email Address” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/AWARDED_CONTRACT/CONTRACTORS/CONTRACTOR/ADDRESS_CONTRACTOR/E_MAIL. The expected ontology instances are epo: epo:AgentInRole (from CL1) / org:Organization (from CL2) / cpov:ContactPoint / xsd:anyURI .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX cpov: <http://data.europa.eu/m8g/>

ASK WHERE { ?this epo:playedBy / epo:hasPrimaryContactPoint / cpov:email ?value . }