#title: II.2.11.1 - Options
#description: “II.2.11.1 - Options” in SF corresponds to “BT-53 Options” in eForms. The corresponding XML element is nanOBJECT_DESCR/*[matches(name(),'OPTIONS')]. The expected ontology instances are epo: epo:Lot / epo:Purpose / xsd:boolean .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasPurpose / epo:hasOptions ?value . }