#title: IV.2.9.1 - The contracting authority will not award any further contracts based on the above prior information notice
#description: “IV.2.9.1 - The contracting authority will not award any further contracts based on the above prior information notice” in SF corresponds to “BT-756 PIN Competition Termination” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/TERMINATION_PIN. The expected ontology instances are epo: epo:ProcurementProcessInformation / xsd:boolean .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:isCompetitionTerminated ?value . }