#title: V.2.2.1 - Number of tenders received
#description: “V.2.2.1 - Number of tenders received” in SF corresponds to “BT-759 Received Submissions Count” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/AWARDED_CONTRACT/TENDERS/NB_TENDERS_RECEIVED. The expected ontology instances are epo:  epo:SubmissionStatisticalInformation / xsd:integer .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasReceivedTenders ?value . }