#title: II.2.5.3.1 - hasFormula
#description: “II.2.5.3.1 - hasFormula” in SF corresponds to “BT-543 Award Criterion complicated” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/AC/AC_PRICE/AC_CRITERION. The expected ontology instances are epo: epo:AwardCriterion  .

PREFIX cccev: <http://data.europa.eu/m8g/>

ASK WHERE { ?this cccev:name ?value . }