#title: D1.1.1.1 - Open procedure
#description: “D1.1.1.1 - Open procedure” in SF corresponds to “BT-1252 Direct Award Justification Previous Procedure Identifier” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/PT_AWARD_CONTRACT_WITHOUT_CALL/D_ACCORDANCE_ARTICLE/D_PROC_OPEN. The expected ontology instances are epo: epo:DirectAwardTerm / epo:Procedure / at-voc:procurement-procedure-type .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:refersToPreviousProcedure / epo:hasProcedureType <http://publications.europa.eu/resource/authority/procurement-procedure-type/open> . }