#title: Class type checker for the property
#description: A SPARQL query that checks if the values of the property epo:isSubjectToLotSpecificTerm are instances of the class epo:LotSpecificTerm. Currently all the values in our data are instances of the classes epo:ReviewTerm and epo:DesignContestRegimeTerm which are subclasses of the class epo:LotSpecificTerm.

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK {
    ?s epo:isSubjectToLotSpecificTerm ?o .
    ?o rdf:type ?type
    FILTER (?type = epo:ReviewTerm || ?type = epo:DesignContestRegimeTerm)
    }