#title: nan - Title
#description: “nan - Title” in SF corresponds to “BT-721 Contract Title” in eForms. The corresponding XML element is nanAWARD_CONTRACT/TITLE. The expected ontology instances are epo: epo:Contract / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasTitle ?value . }