#title: IV.2.8.1 - The notice involves the termination of the dynamic purchasing system published by the above contract notice
#description: “IV.2.8.1 - The notice involves the termination of the dynamic purchasing system published by the above contract notice” in SF corresponds to “BT-119 Dynamic Purchasing System Termination” in eForms. The corresponding XML element is nanTERMINATION_DPS. The expected ontology instances are epo: epo:Lot / epo:DynamicPurchaseSystemTechnique / xsd:boolean .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { ?this epo:usesTechnique ?value.
[?value rdf:type epo:DynamicPurchaseSystemTechnique.]
?value epo:hasDPSTermination "true"^^xsd:boolean. }