#title: IV.2.1 - Previous publication concerning this procedure
#description: “IV.2.1 - Previous publication concerning this procedure” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/NOTICE_NUMBER_OJ. The expected ontology instances are epo: epo:Notice / epo:Notice /  epo:Identifier / xsd:string .
#xpath: /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/NOTICE_NUMBER_OJ

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Notice .
		?this epo:refersToPrevious / epo:hasID / epo:hasIdentifierValue ?value . }