#title: V.2.3.3 - Postal address
#description: “V.2.3.3 - Postal address” in SF corresponds to “BT-510 Organisation Street” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/AWARDED_CONTRACT/CONTRACTORS/CONTRACTOR/ADDRESS_CONTRACTOR/ADDRESS. The expected ontology instances are epo: epo:AgentInRole (from CL1) / org:Organization (from CL2) /  locn:Address / rdf:langString .

PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX legal: <None>

ASK WHERE { ?this epo:playedBy / legal:registeredAddress / locn:thoroughfare ?value . }