#title: I.5 - Main activity
#description: “I.5 - Main activity” in SF corresponds to “BT-10 Activity Authority” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/CA_ACTIVITY. The expected ontology instances are epo: org:Organization / at-voc:main-activity (from main_activity.csv) .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasMainActivityType ?value . }