#title: II.2.1.1 - Lot no
#description: “II.2.1.1 - Lot no” in SF corresponds to “BT-137 Purpose Lot Identifier” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/LOT_NO. The expected ontology instances are epo: epo:Lot / epo:Identifier / xsd:string .
#xpath: /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/LOT_NO

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:hasID / epo:hasIdentifierValue ?value . }