#title: IV.1.3.2 - A dynamic purchasing system was set up
#description: “IV.1.3.2 - A dynamic purchasing system was set up” in SF corresponds to “BT-766 Dynamic Purchasing System” in eForms. The corresponding XML element is nanDPS. The expected ontology instances are epo: epo:Lot / epo:DynamicPurchaseSystemTechnique / at-voc:dfs-usage .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:usesTechnique / epo:hasDPSScope <http://publications.europa.eu/resource/authority/dps-usage> . }