#title: nan - nan
#description: “nan - nan” in SF corresponds to “nan nan” in eForms. The corresponding XML element is nannan. The expected ontology instances are epo: epo:SubmissionStatisticalInformation / MonetaryValue /at-voc:currency (from CL9) .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasLowestReceivedTenderLotValue / epo:hasCurrency ?value . }