#title: II.2.5.1.2 - hasFormula
#description: “II.2.5.1.2 - hasFormula” in SF corresponds to “BT-543 Award Criterion complicated” in eForms. The corresponding XML element is nannan. The expected ontology instances are epo: epo:AwardCriterion  .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasFormula ?value . }