#title: nan - nan
#description: “nan - nan” in SF corresponds to “nan nan” in eForms. The corresponding XML element is nannan. The expected ontology instances are epo: epo:Lot / epo:LotAwardOutcome .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:describesLot ?value }