#title: V.0.4 - Title
#description: “V.0.4 - Title” in SF corresponds to “BT-721 Contract Title” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/TITLE. The expected ontology instances are epo: epo:Contract / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasTitle ?value . }