#title: VI.4.3 - Review procedure
#description: “VI.4.3 - Review procedure” in SF corresponds to “BT-99 Review Deadline Description” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/COMPLEMENTARY_INFO/REVIEW_PROCEDURE. The expected ontology instances are epo: epo:Lot / epo:ReviewTerm .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:isSubjectToLotSpecificTerm / epo:hasReviewDeadlineInformation ?value . }