#title: VI.3 - Additional information
#description: “VI.3 - Additional information” in SF corresponds to “BT-300 nan” in eForms. The corresponding XML element is nanINFO_ADD. The expected ontology instances are epo: epo:Lot .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasAdditionalInformation ?value . }