#title: nan - nan
#description: “nan - nan” in SF corresponds to “nan nan” in eForms. The corresponding XML element is nanAWARD_CONTRACT/AWARDED_CONTRACT. The expected ontology instances are epo: epo:OrganisationGroup / org:Organization .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasMember ?value }