#title: nan - Lot No
#description: “nan - Lot No” in SF corresponds to “BT-13713 Result Lot Identifier” in eForms. The corresponding XML element is nanAWARD_CONTRACT/LOT_NO. The expected ontology instances are epo: epo:Contract / epo:Lot / epo:Identifier / xsd:string .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:includesLot / epo:hasID / epo:hasIdentifierValue ?value . }