#title: V.1.1.2 - Other reasons (discontinuation of procedure)
#description: “V.1.1.2 - Other reasons (discontinuation of procedure)” in SF corresponds to “BT-144 Not Awarded Reason” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/NO_AWARDED_CONTRACT/PROCUREMENT_DISCONTINUED. The expected ontology instances are epo: epo:LotAwardOutcome / at-voc:non-award-justification .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasNonAwardJustification <http://publications.europa.eu/resource/authority/non-award-justification/other> . }