#title: V.2.5.1 - ⃞The contract is likely to be subcontracted
#description: “V.2.5.1 - ⃞The contract is likely to be subcontracted” in SF corresponds to “BT-773 Subcontracting” in eForms. The corresponding XML element is nanAWARD_CONTRACT/AWARDED_CONTRACT/LIKELY_SUBCONTRACTED. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / at-voc:applicability  .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:foreseesContractTerm / epo:hasReservedExecution ?value . }