#title: D1.1.4 - Extreme urgency brought about by events unforeseeable for the contracting authority and in accordance with the strict conditions stated  in the directive
#description: “D1.1.4 - Extreme urgency brought about by events unforeseeable for the contracting authority and in accordance with the strict conditions stated  in the directive” in SF corresponds to “BT-136 Direct Award Justification Code” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/PT_AWARD_CONTRACT_WITHOUT_CALL/D_ACCORDANCE_ARTICLE/D_EXTREME_URGENCY. The expected ontology instances are epo: epo:Procedure / epo:DirectAwardTerm / at-voc:direct-award-justification .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:isSubjectToProcedureSpecificTerm / epo:hasDirectAwardJustification <http://publications.europa.eu/resource/authority/direct-award-justification/urgency> . }