#title: IV.1.3.2 - A dynamic purchasing system was set up
#description: “IV.1.3.2 - A dynamic purchasing system was set up” in SF corresponds to “BT-766 Dynamic Purchasing System” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/DPS. The expected ontology instances are epo: epo:Procedure / epo:DynamicPurchaseSystemTechniqueUsage .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:usesTechnique ?value . }