#title: V.2.2.6 - The contract has been awarded to a group of economic operators
#description: “V.2.2.6 - The contract has been awarded to a group of economic operators” in SF corresponds to “BT-768 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT/AWARDED_CONTRACT/CONTRACTORS/AWARDED_TO_GROUP. The expected ontology instances are epo: epo:OrganisationGroup / org:Organization .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasMember ?value }