#title: V.0.1 - nan
#description: “V.0.1 - nan” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT. The expected ontology instances are epo: epo:Contract / epo:Buyer .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:bindsBuyer ?value }