#title: I.0 - nan
#description: “I.0 - nan” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/CONTRACTING_BODY/ADDRESS_CONTRACTING_BODY_ADDITIONAL. The expected ontology instances are epo: epo:OrganisationGroup / org:Organization .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasMember ?value }