#title: II.1.7.1 - Value
#description: “II.1.7.1 - Value” in SF corresponds to “BT-27 Estimated Value” in eForms. The corresponding XML element is nanVAL_TOTAL. The expected ontology instances are epo: epo:Procedure / epo:MonetaryValue / epo:Numeric .

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this rdf:type / epo:hasEstimatedValue / epo:hasAmountValue ?value . }