#title: I.6 - Main activity (in the case of a notice published by a contracting entity)
#description: “I.6 - Main activity (in the case of a notice published by a contracting entity)” in SF corresponds to “BT-10 Activity Authority” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F23_2014/CONTRACTING_BODY/CE_ACTIVITY. The expected ontology instances are epo: org:Organization / at-voc:main-activity (from main_activity.csv) .
#xpath: /TED_EXPORT/FORM_SECTION/F23_2014/CONTRACTING_BODY/CE_ACTIVITY

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type org:Organization .
		?this epo:hasMainActivity ?value . }