#title: IV.1.1.2 - Award procedure without prior publication of a concession notice in the cases listed below (please complete Annex D4)
#description: “IV.1.1.2 - Award procedure without prior publication of a concession notice in the cases listed below (please complete Annex D4)” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F23_2014/PROCEDURE/PT_AWARD_CONTRACT_WITHOUT_PUBLICATION. The expected ontology instances are epo: epo:Procedure / at-voc:procurement-procedure-type .
#xpath: /TED_EXPORT/FORM_SECTION/F23_2014/PROCEDURE/PT_AWARD_CONTRACT_WITHOUT_PUBLICATION

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:hasProcedureType <http://publications.europa.eu/resource/authority/procurement-procedure-type/neg-wo-call> . }