#title: I.3.4.3.12.2 - Address of the buyer profile
#description: “I.3.4.3.12.2 - Address of the buyer profile” in SF corresponds to “BT-508 Buyer Profile URL” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F23_2014/CONTRACTING_BODY/ADDRESS_PARTICIPATION/URL_BUYER. The expected ontology instances are epo: epo:AgentInRole (from CL1) / epo:BuyerProfile / xsd:anyURI .
#xpath: /TED_EXPORT/FORM_SECTION/F23_2014/CONTRACTING_BODY/ADDRESS_PARTICIPATION/URL_BUYER

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:TenderReceiver .
		?this epo:hasBuyerProfile / epo:hasURL ?value . }