#title: I.3.1 - The procurement documents are available for unrestricted and full direct access, free of charge
#description: “I.3.1 - The procurement documents are available for unrestricted and full direct access, free of charge” in SF corresponds to “BT-14 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F23_2014/CONTRACTING_BODY/DOCUMENT_FULL. The expected ontology instances are epo: epo:AccessTerm / xsd:boolean .
#xpath: /TED_EXPORT/FORM_SECTION/F23_2014/CONTRACTING_BODY/DOCUMENT_FULL

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AccessTerm .
		?this epo:isProcurementDocumentRestricted false . }