#title: I.3.4.3.7 - Country
#description: “I.3.4.3.7 - Country” in SF corresponds to “BT-514 Organisation Country Code” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F23_2014/CONTRACTING_BODY/ADDRESS_PARTICIPATION/COUNTRY. The expected ontology instances are epo: epo:AgentInRole (from CL1)  / org:Organization (from CL2) / locn:Address / at-voc:country (from country.json) .
#xpath: /TED_EXPORT/FORM_SECTION/F23_2014/CONTRACTING_BODY/ADDRESS_PARTICIPATION/COUNTRY

PREFIX cv: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:TenderReceiver .
		?this epo:playedBy / cv:registeredAddress / epo:hasCountryCode ?value . }