#title: II.1.6.2 - Maximum number of lots that may be awarded to one tenderer
#description: “II.1.6.2 - Maximum number of lots that may be awarded to one tenderer” in SF corresponds to “BT-33 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F23_2014/OBJECT_CONTRACT/LOT_DIVISION/LOT_MAX_ONE_TENDERER. The expected ontology instances are epo: epo:Procedure / epo:ProcedureTerm / xsd:integer .
#xpath: /TED_EXPORT/FORM_SECTION/F23_2014/OBJECT_CONTRACT/LOT_DIVISION/LOT_MAX_ONE_TENDERER

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:isSubjectToProcedureSpecificTerm / epo:hasMaximumNumberOfLotsToBeAwarded ?value }