#title: IV.1.3.2 - In the case of framework agreements, provide justification for any duration exceeding 8 years
#description: “IV.1.3.2 - In the case of framework agreements, provide justification for any duration exceeding 8 years” in SF corresponds to “BT-109 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F21_2014/PROCEDURE/FRAMEWORK/JUSTIFICATION. The expected ontology instances are epo: epo:Procedure /  epo:FrameworkAgreementTerm / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F21_2014/PROCEDURE/FRAMEWORK/JUSTIFICATION

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:isSubjectToProcedureSpecificTerm / epo:hasDurationExtensionJustification ?value . }