#title: II.3 - Estimated date of publication of contract notice
#description: “II.3 - Estimated date of publication of contract notice” in SF corresponds to “BT-127 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F21_2014/OBJECT_CONTRACT/DATE_PUBLICATION_NOTICE. The expected ontology instances are epo: epo:ResultNotice / xsd:date .
#xpath: /TED_EXPORT/FORM_SECTION/F21_2014/OBJECT_CONTRACT/DATE_PUBLICATION_NOTICE

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ResultNotice .
		?this epo:hasPublicationDate ?value }