#title: III.1.5.3 - Participation in the procedure is reserved to organisations pursuing a public service mission and fulfilling the conditions set in Article 94(2) of Directive 2014/25/EU
#description: “III.1.5.3 - Participation in the procedure is reserved to organisations pursuing a public service mission and fulfilling the conditions set in Article 94(2) of Directive 2014/25/EU” in SF corresponds to “BT-71 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F21_2014/LEFTI/RESERVED_ORGANISATIONS_SERVICE_MISSION. The expected ontology instances are epo: epo:Lot  / at-voc:reserved-procurement .
#xpath: /TED_EXPORT/FORM_SECTION/F21_2014/LEFTI/RESERVED_ORGANISATIONS_SERVICE_MISSION

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot  .
		?this epo:hasReservedProcurement <http://publications.europa.eu/resource/authority/reserved-procurement/res-pub-ser> }