#title: IV.2.5 - Scheduled date for start of award procedures
#description: “IV.2.5 - Scheduled date for start of award procedures” in SF corresponds to “no match nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F21_2014/PROCEDURE/DATE_AWARD_SCHEDULED. The expected ontology instances are epo: epo:Procedure / epo:ProcessPlanningTerm / xsd:date .
#xpath: /TED_EXPORT/FORM_SECTION/F21_2014/PROCEDURE/DATE_AWARD_SCHEDULED

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this  epo:isSubjectToTerm / epo:hasAwardDateScheduled ?value }