#title: I.3.3.2 - Another address: (please provide another address)
#description: “I.3.3.2 - Another address: (please provide another address)” in SF corresponds to “no direct match nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F21_2014/CONTRACTING_BODY/ADDRESS_FURTHER_INFO. The expected ontology instances are epo: epo:Notice / epo:AgentInRole (from CL1) .
#xpath: /TED_EXPORT/FORM_SECTION/F21_2014/CONTRACTING_BODY/ADDRESS_FURTHER_INFO

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Notice .
		?this epo:announcesRole ?value }