#title: III.2.3.1 - Obligation to indicate the names and professional qualifications of the staff assigned to performing the contract
#description: “III.2.3.1 - Obligation to indicate the names and professional qualifications of the staff assigned to performing the contract” in SF corresponds to “BT-79 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F21_2014/LEFTI/PERFORMANCE_STAFF_QUALIFICATION. The expected ontology instances are epo: epo:Lot / at-voc:requirement-stage .
#xpath: /TED_EXPORT/FORM_SECTION/F21_2014/LEFTI/PERFORMANCE_STAFF_QUALIFICATION

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:hasPerformingStaffQualificationInformation <http://publications.europa.eu/resource/authority/requirement-stage/t-requ>. }