#title: I.3.3.1 - The above mentioned address
#description: “I.3.3.1 - The above mentioned address” in SF corresponds to “no direct match nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F21_2014/CONTRACTING_BODY/ADDRESS_FURTHER_INFO_IDEM. The expected ontology instances are epo: epo:ResultNotice / epo:AgentInRole (from CL1) .
#xpath: /TED_EXPORT/FORM_SECTION/F21_2014/CONTRACTING_BODY/ADDRESS_FURTHER_INFO_IDEM

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ResultNotice .
		?this epo:announcesRole ?value }