#title: V.3.2 - Information about participants
#description: “V.3.2 - Information about participants” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F13_2014/RESULTS/AWARDED_PRIZE. The expected ontology instances are epo: epo:SubmissionStatisticalInformation / epo:LotAwardOutcome .
#xpath: /TED_EXPORT/FORM_SECTION/F13_2014/RESULTS/AWARDED_PRIZE

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:SubmissionStatisticalInformation .
		?this epo:summarisesInformationForLotAwardOutcome ?value . }