#title: Class type checker for the property
#description: A SPARQL query that checks if the values of the property epo:announcesRole are instances of the class epo:AgentInRole. Currently all the values in our data are instances of the classes epo:Winner, epo:Reviewer, epo:Mediator, epo:ReviewProcedureInformationProvider, epo:ProcurementProcedureInformationProvider, and epo:TenderReciever which are subclasses of the class epo:AgentInRole.

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK {
    ?s epo:announcesRole ?o .
    ?o rdf:type ?type
    FILTER (?type = epo:Reviewer || ?type = epo:Winner || ?type = epo:Mediator || ?type = epo:ReviewProcedureInformationProvider || ?type = epo:ProcurementProcedureInformationProvider || ?type = epo:TenderReciever)
    }