#title: V.0.4 - The contest was terminated without an award or attribution of prizes
#description: “V.0.4 - The contest was terminated without an award or attribution of prizes” in SF corresponds to “BT-142 Winner Chosen” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F13_2014/RESULTS/NO_AWARDED_PRIZE. The expected ontology instances are epo: epo:LotAwardOutcome / at-voc:winner-selection-status .
#xpath: /TED_EXPORT/FORM_SECTION/F13_2014/RESULTS/NO_AWARDED_PRIZE

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:LotAwardOutcome .
		?this epo:hasAwardStatus <http://publications.europa.eu/resource/authority/winner-selection-status/clos-nw> . }