#title: I.2.1 - The contest involves joint procurement
#description: “I.2.1 - The contest involves joint procurement” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F13_2014/CONTRACTING_BODY/JOINT_PROCUREMENT_INVOLVED. The expected ontology instances are epo: epo:ResultNotice / epo:Procedure / xsd:boolean .
#xpath: /TED_EXPORT/FORM_SECTION/F13_2014/CONTRACTING_BODY/JOINT_PROCUREMENT_INVOLVED

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:ResultNotice .
		?this epo:refersToProcedure / epo:isJointProcurement true . }