#title: V.3.2.1 - Number of participants to be contemplated
#description: “V.3.2.1 - Number of participants to be contemplated” in SF corresponds to “BT-759 Received Submissions Count” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F13_2014/RESULTS/AWARDED_PRIZE/PARTICIPANTS/NB_PARTICIPANTS. The expected ontology instances are epo:  epo:SubmissionStatisticalInformation / xsd:integer .
#xpath: /TED_EXPORT/FORM_SECTION/F13_2014/RESULTS/AWARDED_PRIZE/PARTICIPANTS/NB_PARTICIPANTS

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type  epo:SubmissionStatisticalInformation .
		?this epo:hasReceivedTenders ?value . }