site:
  title: TED-SWS artefacts documentation
  start_page: rdf-mapping::index.adoc
content:
#  edit_url: false
  sources:
    - url: https://github.com/OP-TED/ted-rdf-mapping.git
#    - url: /home/lps/work/workspace-charm/ted-sws-artefacts
      branches:
        - main
#        - HEAD
      start_path: docs/antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./antora/supplemental-ui