#title: III.1.5.1 - The contract is reserved to sheltered workshops and economic operators aiming at the social and professional integration of disabled or disadvantaged persons
#description: “III.1.5.1 - The contract is reserved to sheltered workshops and economic operators aiming at the social and professional integration of disabled or disadvantaged persons” in SF corresponds to “BT-71 /” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F22_2014/LEFTI/RESTRICTED_SHELTERED_WORKSHOP. The expected ontology instances are epo: epo:Lot  / at-voc:reserved-procurement .
#xpath: /TED_EXPORT/FORM_SECTION/F22_2014/LEFTI/RESTRICTED_SHELTERED_WORKSHOP

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot  .
		?this epo:hasReservedProcurement <http://publications.europa.eu/resource/authority/reserved-procurement/res-ws> }