#title: IV.1.10.1 - Information about national procedures is available at (URL)
#description: “IV.1.10.1 - Information about national procedures is available at (URL)” in SF corresponds to “no direct match nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F22_2014/PROCEDURE/URL_NATIONAL_PROCEDURE. The expected ontology instances are epo: epo:Procedure / epo:ProcedureTerm / xsd:anyURI .
#xpath: /TED_EXPORT/FORM_SECTION/F22_2014/PROCEDURE/URL_NATIONAL_PROCEDURE

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:isSubjectToProcedureSpecificTerm  /  epo:hasNationalProcedureRules ?value }