#title: II.2.8.1.2 - End
#description: “II.2.8.1.2 - End” in SF corresponds to “BT-536 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F22_2014/OBJECT_CONTRACT/OBJECT_DESCR/QS/DATE_END. The expected ontology instances are epo: epo:Lot / epo:MultipleStageProcedureTerm / epo:Period / xsd:dateTime .
#xpath: /TED_EXPORT/FORM_SECTION/F22_2014/OBJECT_CONTRACT/OBJECT_DESCR/QS/DATE_END

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasQualificationSystemPeriod  / epo:hasEnd ?value }