#title: III.2.2 - Contract performance conditions
#description: “III.2.2 - Contract performance conditions” in SF corresponds to “BT-70 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F22_2014/LEFTI/PERFORMANCE_CONDITIONS. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F22_2014/LEFTI/PERFORMANCE_CONDITIONS

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:hasPerformanceConditions ?value }