#title: II.2.8.5 - Formalities necessary for evaluating if requirements are me
#description: “II.2.8.5 - Formalities necessary for evaluating if requirements are me” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F22_2014/OBJECT_CONTRACT/OBJECT_DESCR/RENEWAL_DESC. The expected ontology instances are epo: epo:Lot / epo:MupltipleStageProcedureTerm / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F22_2014/OBJECT_CONTRACT/OBJECT_DESCR/RENEWAL_DESC

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:isSubjectToLotSpecificTerm / epo:hasQualificationSystemRenewalDescription ?value }