#title: I.3.4 - Tenders or requests to participate must be submitted 
#description: “I.3.4 - Tenders or requests to participate must be submitted ” in SF corresponds to “nan nan” in eForms. The corresponding XML element is . The expected ontology instances are epo: epo:Procedure / epo:SubmissionTerm .
#xpath: 

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:isSubjectToProcedureSpecificTerm ?value . }