#title: VI.2.2 - Electronic invoicing will be accepted
#description: “VI.2.2 - Electronic invoicing will be accepted” in SF corresponds to “BT-743 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F22_2014/COMPLEMENTARY_INFO/EINVOICING. The expected ontology instances are epo: epo:Procedure / epo:ContractTerm / xsd:boolean .
#xpath: /TED_EXPORT/FORM_SECTION/F22_2014/COMPLEMENTARY_INFO/EINVOICING

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:foreseesContractSpecificTerm / epo:hasEInvoicing true . }