#title: III.1.9.1 - Conditions to be fulfilled by economic operators in view of their qualification
#description: “III.1.9.1 - Conditions to be fulfilled by economic operators in view of their qualification” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F22_2014/LEFTI/QUALIFICATION/CONDITIONS. The expected ontology instances are epo: epo:Lot / epo:SelectionCriterion / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F22_2014/LEFTI/QUALIFICATION/CONDITIONS

PREFIX cccev: <http://data.europa.eu/m8g/>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:specifiesSelectionCriterion / cccev:name ?value }