#title: II.1.6.3 - The contracting authority reserves the right to award contracts combining the following lots or groups of lots
#description: “II.1.6.3 - The contracting authority reserves the right to award contracts combining the following lots or groups of lots” in SF corresponds to “no direct match nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F22_2014/OBJECT_CONTRACT/LOT_DIVISION/LOT_COMBINING_CONTRACT_RIGHT. The expected ontology instances are epo: epo:Procedure / epo:ProcedureTerm / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F22_2014/OBJECT_CONTRACT/LOT_DIVISION/LOT_COMBINING_CONTRACT_RIGHT

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Procedure .
		?this epo:isSubjectToProcedureSpecificTerm / epo:hasLotAwardCombination ?value }