#title: I.3.2 - Access to the procurement documents is restricted
#description: “I.3.2 - Access to the procurement documents is restricted” in SF corresponds to “BT-14 nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F22_2014/CONTRACTING_BODY/DOCUMENT_RESTRICTED. The expected ontology instances are epo: epo:AccessTerm / xsd:boolean .
#xpath: /TED_EXPORT/FORM_SECTION/F22_2014/CONTRACTING_BODY/DOCUMENT_RESTRICTED

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:AccessTerm .
		?this epo:isProcurementDocumentRestricted true . }