#title: D1.3.1 - Please explain in a clear and comprehensive manner why the award of the contract without prior publication in the Official Journal of the European Union is lawful, by stating the relevant facts and, as appropriate, the conclusions of law in accordance with the directive
#description: “D1.3.1 - Please explain in a clear and comprehensive manner why the award of the contract without prior publication in the Official Journal of the European Union is lawful, by stating the relevant facts and, as appropriate, the conclusions of law in accordance with the directive” in SF corresponds to “BT-135 Direct Award Justification Text” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/PT_AWARD_CONTRACT_WITHOUT_CALL/D_JUSTIFICATION. The expected ontology instances are epo: epo:Procedure / epo:DirectAwardTerm / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:isSubjectToProcedureSpecificTerm / epo:hasJustification ?value }