#title: II.2.11.2 - Description of options
#description: “II.2.11.2 - Description of options” in SF corresponds to “BT-54 Options Description” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/OPTIONS_DESCR. The expected ontology instances are epo: epo:Lot / epo:ContractTerm / rdf:langString .
#xpath: /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/OPTIONS_DESCR

PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		?this rdf:type epo:Lot .
		?this epo:foreseesContractSpecificTerm / epo:hasOptionsDescription ?value . }