#title: II.1.1 - Title
#description: “II.1.1 - Title” in SF corresponds to “BT-21 Title” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/TITLE. The expected ontology instances are epo: epo:Procedure / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasTitle ?value . }