#title: I.1.2 - National registration number
#description: “I.1.2 - National registration number” in SF corresponds to “BT-501 Organisation Identifier” in eForms. The corresponding XML element is nanADDRESS_CONTRACTING_BODY/NATIONALID. The expected ontology instances are epo: epo:Role (from CL1) / epo:Organisation (from CL2) / epo:Identifier / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:playedBy / epo:hasID / epo:hasIdentifierValue ?value . }