#title: IV.2.1 - Previous publication concerning this procedure
#description: “IV.2.1 - Previous publication concerning this procedure” in SF corresponds to “BT-125 Previous Planning Identifier” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/NOTICE_NUMBER_OJ. The expected ontology instances are epo: epo:ResultNotice / epo:Notice /  epo:Identifier / xsd:string .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:refersToPrevious / epo:hasID / epo:hasIdentifierValue ?value . }