#title: I.1.8 - Contact person
#description: “I.1.8 - Contact person” in SF corresponds to “BT-502 Organisation Contact Point” in eForms. The corresponding XML element is nanADDRESS_CONTRACTING_BODY/CONTACT_POINT. The expected ontology instances are epo: epo:Role (from CL1)  / epo:Organisation (from CL2) / epo:ContactPoint / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:playedBy / epo:hasPrimaryContactPoint / epo:hasDescription ?value . }