#title: I.1.12 - Internet Addresses
#description: “I.1.12 - Internet Addresses” in SF corresponds to “nan nan” in eForms. The corresponding XML element is . The expected ontology instances are epo: epo:AgentInRole (from CL1) / cpov:ContactPoint / xsd:anyURI .
#xpath: 

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK WHERE { 
		
		?value rdf:type xsd:anyURI .
		?this epo:hasContactPointInRole / epo:hasInternetAddress ?value . }