#title: IV.1.1.2 - Restricted procedure 
#description: “IV.1.1.2 - Restricted procedure ” in SF corresponds to “BT-105 Procedure Type” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/PT_RESTRICTED. The expected ontology instances are epo: epo:Procedure / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasProcedureType <http://publications.europa.eu/resource/authority/procurement-procedure-type/restricted> . }