#title: II.2.13.1 - The procurement is related to a project and/or programme financed by European Union funds
#description: “II.2.13.1 - The procurement is related to a project and/or programme financed by European Union funds” in SF corresponds to “BT-60 EU Funds” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/EU_PROGR_RELATED. The expected ontology instances are epo: epo:Lot / xsd:boolean .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:isUsingEUFunds ?value . }