#title: V.2.2 - Information about tenders
#description: “V.2.2 - Information about tenders” in SF corresponds to “nan nan” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/AWARD_CONTRACT. The expected ontology instances are epo: epo:SubmissionStatisticalInformation / epo:Lot .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:concernsSubmissionsForLot ?value . }