#title: II.2.1.1 - Lot no
#description: “II.2.1.1 - Lot no” in SF corresponds to “BT-137 Purpose Lot Identifier” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/OBJECT_CONTRACT/OBJECT_DESCR/LOT_NO. The expected ontology instances are epo: epo:Lot / epo:Identifier / xsd:string .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasID / epo:hasIdentifierValue ?value . }