#title: IV.1.1.1.2 - Justification:
#description: “IV.1.1.1.2 - Justification:” in SF corresponds to “BT-1351 Procedure Accelerated Justification” in eForms. The corresponding XML element is /TED_EXPORT/FORM_SECTION/F03_2014/PROCEDURE/ACCELERATED_PROC/P. The expected ontology instances are epo: epo:Procedure / rdf:langString .

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK WHERE { ?this epo:hasAcceleratedProcedureJustification ?value . }