#title: TED-929/TED-1179
#Link: https://meaningfy.atlassian.net/browse/TED-1179
#description: Generic ask SPARQL validation Query for all translations

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

ASK {
	?s1 ?p1 ?o1L1.
	?s1 ?p1 ?o1L2.
	?s2 ?p2 ?o2L1.
	?s2 ?p2 ?o2L2.
    FILTER (lang(?o1L1) = lang(?o2L1))
    FILTER (lang(?o1L2) = lang(?o2L2))
    }