#title: TED-929/TED-1178 GH issue #286
#description: Ask if all the epo:hasDurationExtensionJustification values have a language tag. Return True if it does, False if it does not.

PREFIX epo: <http://data.europa.eu/a4g/ontology#>

ASK {
  {
    SELECT (COUNT(?s) AS ?cNoLangTag) WHERE {
      VALUES ?property {epo:hasDurationExtensionJustification}
      ?s ?property ?value
      FILTER (lang(?value) = "")
    }
  }
  FILTER (?cNoLangTag = 0)
}

